using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.OpenAI;
using Platform.Engineering.Copilot.Core.Interfaces.Agents;
using Platform.Engineering.Copilot.Core.Models.Agents;
using Platform.Engineering.Copilot.Core.Models.IntelligentChat;
using Platform.Engineering.Copilot.Core.Plugins;
using Platform.Engineering.Copilot.Core.Services.Chat;
using Platform.Engineering.Copilot.Core.Interfaces;

namespace Platform.Engineering.Copilot.Core.Services.Agents;

/// <summary>
/// Specialized agent for environment management (lifecycle, cloning, scaling)
/// </summary>
public class EnvironmentAgent : ISpecializedAgent
{
    public AgentType AgentType => AgentType.Environment;

    private readonly Kernel _kernel;
    private readonly IChatCompletionService _chatCompletion;
    private readonly ILogger<EnvironmentAgent> _logger;
    private readonly EnvironmentManagementPlugin _environmentPlugin;

    public EnvironmentAgent(
        ISemanticKernelService semanticKernelService,
        ILogger<EnvironmentAgent> logger,
        EnvironmentManagementPlugin environmentPlugin)
    {
        _logger = logger;
        _environmentPlugin = environmentPlugin;
        
        // Create specialized kernel for environment operations
        _kernel = semanticKernelService.CreateSpecializedKernel(AgentType.Environment);
        _chatCompletion = _kernel.GetRequiredService<IChatCompletionService>();

        // Register environment management plugin
        _kernel.Plugins.Add(KernelPluginFactory.CreateFromObject(environmentPlugin, "EnvironmentManagementPlugin"));

        _logger.LogInformation("✅ Environment Agent initialized with specialized kernel");
    }

    public async Task<AgentResponse> ProcessAsync(AgentTask task, SharedMemory memory)
    {
        _logger.LogInformation("🌍 Environment Agent processing task: {TaskId}", task.TaskId);

        var startTime = DateTime.UtcNow;
        var response = new AgentResponse
        {
            TaskId = task.TaskId,
            AgentType = AgentType.Environment,
            Success = false
        };

        try
        {
            // Get conversation context from shared memory
            var context = memory.GetContext(task.ConversationId ?? "default");
            var previousResults = context?.PreviousResults ?? new List<AgentResponse>();

            // Build system prompt for environment management expertise
            var systemPrompt = BuildSystemPrompt();

            // Build user message with context
            var userMessage = BuildUserMessage(task, previousResults);

            // Create chat history
            var chatHistory = new ChatHistory();
            chatHistory.AddSystemMessage(systemPrompt);
            chatHistory.AddUserMessage(userMessage);

            // 🔥 Set conversation ID in plugin so it can retrieve files from SharedMemory
            // This enables EnvironmentAgent to retrieve Bicep templates generated by InfrastructureAgent
            _environmentPlugin.SetConversationId(task.ConversationId ?? "default");
            _logger.LogInformation(
                "🔗 EnvironmentAgent: ConversationId set to {ConversationId} for SharedMemory file retrieval",
                task.ConversationId ?? "default");

            // Execute with moderate temperature for environment operations
            var executionSettings = new OpenAIPromptExecutionSettings
            {
                Temperature = 0.3, // Moderate temperature for precise operations
                MaxTokens = 4000,
                ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
            };

            var result = await _chatCompletion.GetChatMessageContentAsync(
                chatHistory,
                executionSettings,
                _kernel);

            response.Content = result.Content ?? "";
            response.Success = true;

            // Extract metadata
            response.Metadata = ExtractMetadata(result, task);

            // Store result in shared memory for other agents
            memory.AddAgentCommunication(
                task.ConversationId ?? "default",
                AgentType.Environment,
                AgentType.Orchestrator,
                $"Environment operation completed: {task.Description}",
                new Dictionary<string, object>
                {
                    ["result"] = result.Content ?? ""
                }
            );

            _logger.LogInformation("✅ Environment Agent completed task: {TaskId}", task.TaskId);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "❌ Environment Agent failed on task: {TaskId}", task.TaskId);
            response.Success = false;
            response.Errors = new List<string> { ex.Message };
        }

        response.ExecutionTimeMs = (int)(DateTime.UtcNow - startTime).TotalMilliseconds;
        return response;
    }

    private string BuildSystemPrompt()
    {
        return @"You are a specialized Environment Management expert with deep expertise in:

**Environment Lifecycle Management:**
- Environment provisioning and de-provisioning
- Environment cloning and replication
- Environment scaling (up/down, in/out)
- Environment health monitoring
- Environment state management

**Environment Types:**
- Development, Test, Staging, Production
- Sandbox and demo environments
- CI/CD pipeline environments
- Training and disaster recovery environments

**Best Practices:**
- Environment isolation and security boundaries
- Configuration management across environments
- Secrets and credentials management
- Environment naming conventions
- Resource tagging strategies

**Operations:**
- Clone existing environments with data/configuration
- Scale environments based on load and requirements
- Refresh environments with production data (sanitized)
- Environment status checks and health validation
- Environment cleanup and resource optimization

**CRITICAL: ALWAYS CALL FUNCTIONS - NEVER JUST RESPOND CONVERSATIONALLY!**

When your task description includes ANY of these keywords:
- ""Manage the environment lifecycle""
- ""Track the deployment""  
- ""Deploy"" or ""Provision""
- ""Create environment""
- ""Scale environment""
- ""Clone environment""

You MUST call the appropriate function! DO NOT just write a conversational response.

**ACTUAL DEPLOYMENT WORKFLOW:**
When your task is to ""Manage the environment lifecycle and track the deployment of the new resources"":

1. **YOU MUST CALL create_environment** - This is not optional!
2. The InfrastructureAgent already generated the Bicep templates in the previous step
3. Those templates are stored in SharedMemory and will be retrieved automatically
4. Your job is to ACTUALLY DEPLOY them by calling create_environment

**REQUIRED PARAMETERS FOR create_environment:**
- environmentName: Extract from task description (e.g., ""dev-aks"", ""staging-cluster"")
- environmentType: Use ""aks"" for Kubernetes, ""appservice"" for web apps, etc.
- resourceGroup: Extract from task or generate name (e.g., ""rg-dev-aks"")
- location: Extract from conversation (e.g., ""usgovvirginia"", ""eastus"")
- subscriptionId: **ALWAYS REQUIRED** - Extract from task description or conversation

**CRITICAL: Subscription ID Requirement**
When creating environments with the create_environment function, you MUST ALWAYS provide the subscriptionId parameter.
- Extract the subscription ID from the user's request or previous conversation
- The subscription ID should be a valid Azure subscription GUID (format: 453c2549-4cc5-464f-ba66-acad920823e8)
- Never use placeholder values like 'default-subscription'
- The subscription ID will be visible in your task description or parameters

**Example - WRONG (Don't do this):**
Task: ""Manage the environment lifecycle and track the deployment of the new AKS cluster""
Response: ""I will manage the environment lifecycle and track the deployment...""  ❌ WRONG - No function call!

**Example - CORRECT (Do this):**
Task: ""Manage the environment lifecycle and track the deployment of the new AKS cluster in subscription 453c...""
Response: [Calls create_environment with environmentName=""dev-aks"", environmentType=""aks"", resourceGroup=""rg-dev-aks"", location=""usgovvirginia"", subscriptionId=""453c2549-4cc5-464f-ba66-acad920823e8""] ✅ CORRECT

**DO NOT:**
- Write conversational responses without calling functions
- Say ""I will track..."" or ""I will manage..."" without actually calling create_environment
- Ask for more information if the subscription ID and basic details are in the task description
- Respond with status updates without first calling the deployment function

**DO:**
- Call create_environment IMMEDIATELY when your task is about deployment/provisioning
- Extract all necessary parameters from the task description and previous conversation context
- Trust that the Bicep templates are already in SharedMemory from InfrastructureAgent
- Actually execute the deployment by calling the function

Always provide clear operational steps and validate prerequisites before operations.";
    }

    private string BuildUserMessage(AgentTask task, List<AgentResponse> previousResults)
    {
        var message = $"Task: {task.Description}\n\n";

        // Add parameters if provided
        if (task.Parameters != null && task.Parameters.Any())
        {
            message += "Parameters:\n";
            foreach (var param in task.Parameters)
            {
                message += $"- {param.Key}: {param.Value}\n";
            }
            message += "\n";
        }

        // Add context from previous agent results
        if (previousResults.Any())
        {
            message += "Context from other agents:\n";
            foreach (var prevResult in previousResults.TakeLast(3))
            {
                var contentLength = prevResult.Content?.Length ?? 0;
                if (contentLength > 0)
                {
                    message += $"- {prevResult.AgentType}: {prevResult.Content?.Substring(0, Math.Min(200, contentLength))}...\n";
                }
            }
            message += "\n";
        }

        message += "Please perform the environment management operation with detailed status updates.";

        return message;
    }

    private Dictionary<string, object> ExtractMetadata(ChatMessageContent result, AgentTask task)
    {
        var metadata = new Dictionary<string, object>
        {
            ["timestamp"] = DateTime.UtcNow.ToString("O"),
            ["agentType"] = AgentType.Environment.ToString()
        };

        // Extract tool calls if any
        if (result.Metadata != null && result.Metadata.ContainsKey("ChatCompletionMessage"))
        {
            metadata["toolsInvoked"] = "EnvironmentManagementPlugin functions";
        }

        return metadata;
    }
}
