using System.Text;
using System.Linq;
using System.Collections.Generic;
using Platform.Engineering.Copilot.Core.Models;

namespace Platform.Engineering.Copilot.Core.Services.Generators.Containers;

/// <summary>
/// Generates Azure Container Apps Bicep module files
/// Implements Azure best practices including DAPR, scaling rules, and managed environment
/// </summary>
public class BicepContainerAppsModuleGenerator
{
    // Cache for delegated module generators to avoid regenerating multiple times
    private Dictionary<string, string>? _cachedKeyVaultFiles;
    private Dictionary<string, string>? _cachedNetworkFiles;

    /// <summary>
    /// Generate complete Container Apps module with environment, container app, and monitoring
    /// </summary>
    public Dictionary<string, string> GenerateContainerAppsModule(TemplateGenerationRequest request)
    {
        var files = new Dictionary<string, string>();
        var serviceName = request.ServiceName.ToLowerInvariant();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        
        var modulePath = "modules/containerapps";
        
        // Generate module files
        files["main.bicep"] = GenerateMainBicep(request);
        files[$"{modulePath}/environment.bicep"] = GenerateEnvironmentBicep(request);
        files[$"{modulePath}/container-app.bicep"] = GenerateContainerAppBicep(request);
        files[$"{modulePath}/ingress.bicep"] = GenerateIngressBicep(request);
        files[$"{modulePath}/dapr.bicep"] = GenerateDaprBicep(request);
        files[$"{modulePath}/monitoring.bicep"] = GenerateMonitoringBicep(request);
        files[$"{modulePath}/private-endpoint.bicep"] = GeneratePrivateEndpointBicep(request);
        files["parameters.json"] = GenerateParametersJson(request);
        
        // Optional: Networking
        if (infrastructure.IncludeNetworking == true)
        {
            files[$"{modulePath}/network.bicep"] = GenerateNetworkBicep(request);
        }
        
        return files;
    }
    
    private string GenerateMainBicep(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName.ToLowerInvariant();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var includeNetworking = infrastructure.IncludeNetworking == true;
        
        return $@"// Container Apps Module - Main Entry Point - FedRAMP Compliant
// Implements: SC-7 (Network Isolation), AC-3 (Managed Identity), AU-2 (Logging), SC-8 (TLS Encryption)
// Generated by Platform Engineering Copilot

targetScope = 'resourceGroup'

@description('Name of the service')
param serviceName string

@description('Environment (dev, staging, prod)')
param environment string

@description('Azure region')
param location string = resourceGroup().location

@description('Container image')
param containerImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Container port')
param containerPort int = 80

@description('Enable DAPR')
param enableDapr bool = true

@description('Enable monitoring')
param enableMonitoring bool = true

@description('Minimum replicas')
param minReplicas int = 1

@description('Maximum replicas')
param maxReplicas int = 10

@description('CPU cores')
param cpuCores string = '0.5'

@description('Memory in GB')
param memorySize string = '1'

@description('Enable Managed Identity')
param enableManagedIdentity bool = true

@description('Allow insecure connections')
param allowInsecure bool = false

@description('External ingress')
param externalIngress bool = true

@description('Target port for ingress')
param targetPort int = 80

@description('Transport protocol')
@allowed(['auto', 'http', 'http2', 'tcp'])
param transport string = 'auto'

@description('Enable VNet Integration')
param enableVnetIntegration bool = false

@description('VNet Subnet ID for app')
param vnetSubnetId string = ''

@description('Infrastructure Subnet ID for Container Apps Environment')
param infrastructureSubnetId string = ''

@description('DAPR App ID')
param daprAppId string = ''

@description('DAPR App Port')
param daprAppPort int = 80

@description('Enable DAPR API Logging')
param daprEnableApiLogging bool = false

@description('Log Analytics Workspace ID')
param logAnalyticsWorkspaceId string = ''

@description('Maximum inactive revisions')
param maxInactiveRevisions int = 5

@description('Revision mode')
@allowed(['Single', 'Multiple'])
param revisionMode string = 'Single'

@description('Enable IP Restrictions')
param enableIPRestrictions bool = false

@description('Allowed IP Ranges')
param allowedIPRanges array = []

@description('Enable Private Endpoint for Container Apps Environment')
param enablePrivateEndpoint bool = false

var commonTags = {{
  Environment: environment
  Service: serviceName
  ManagedBy: 'bicep'
  Platform: 'ContainerApps'
}}

{(includeNetworking ? @"
// Network Infrastructure
module network './network.bicep' = {
  name: '${serviceName}-${environment}-network'
  params: {
    serviceName: serviceName
    location: location
    tags: commonTags
  }
}
" : "")}

// Monitoring (Log Analytics Workspace)
module monitoring './monitoring.bicep' = if (enableMonitoring) {{
  name: '${{serviceName}}-${{environment}}-monitoring'
  params: {{
    serviceName: serviceName
    environment: environment
    location: location
    tags: commonTags
  }}
}}

// Container Apps Environment
module containerAppsEnvironment './environment.bicep' = {{
  name: '${{serviceName}}-${{environment}}-env'
  params: {{
    serviceName: serviceName
    environment: environment
    location: location
    workspaceId: enableMonitoring ? monitoring.outputs.workspaceId : (logAnalyticsWorkspaceId != '' ? logAnalyticsWorkspaceId : '')
    workspaceKey: enableMonitoring ? monitoring.outputs.workspaceKey : ''
    enableDapr: enableDapr
    enableVnetIntegration: enableVnetIntegration
    infrastructureSubnetId: {(includeNetworking ? "enableVnetIntegration ? network.outputs.containerAppsSubnetId : infrastructureSubnetId" : "infrastructureSubnetId")}
    tags: commonTags
  }}
}}

// DAPR Components (if enabled)
module dapr './dapr.bicep' = if (enableDapr) {{
  name: '${{serviceName}}-${{environment}}-dapr'
  params: {{
    serviceName: serviceName
    environment: environment
    containerAppsEnvironmentName: containerAppsEnvironment.outputs.environmentName
    daprAppId: daprAppId != '' ? daprAppId : serviceName
    daprAppPort: daprAppPort
    daprEnableApiLogging: daprEnableApiLogging
  }}
  dependsOn: [
    containerAppsEnvironment
  ]
}}

// Container App
module containerApp './container-app.bicep' = {{
  name: '${{serviceName}}-${{environment}}-app'
  params: {{
    serviceName: serviceName
    environment: environment
    location: location
    containerAppsEnvironmentId: containerAppsEnvironment.outputs.environmentId
    containerImage: containerImage
    containerPort: containerPort
    enableDapr: enableDapr
    minReplicas: minReplicas
    maxReplicas: maxReplicas
    cpuCores: cpuCores
    memorySize: memorySize
    enableManagedIdentity: enableManagedIdentity
    allowInsecure: allowInsecure
    externalIngress: externalIngress
    targetPort: targetPort
    transport: transport
    maxInactiveRevisions: maxInactiveRevisions
    revisionMode: revisionMode
    enableIPRestrictions: enableIPRestrictions
    allowedIPRanges: allowedIPRanges
    tags: commonTags
  }}
  dependsOn: [
    dapr
  ]
}}

{(includeNetworking ? @"
// Private Endpoint for Container Apps Environment (if enabled)
module privateEndpoint './private-endpoint.bicep' = if (enablePrivateEndpoint) {
  name: '${serviceName}-${environment}-pe'
  params: {
    serviceName: serviceName
    environment: environment
    location: location
    containerAppsEnvironmentId: containerAppsEnvironment.outputs.environmentId
    subnetId: network.outputs.privateEndpointSubnetId
    virtualNetworkId: network.outputs.vnetId
    tags: commonTags
  }
  dependsOn: [
    containerAppsEnvironment
  ]
}
" : "")}

// Outputs
output containerAppUrl string = containerApp.outputs.fqdn
output containerAppName string = containerApp.outputs.name
output environmentName string = containerAppsEnvironment.outputs.environmentName
output environmentId string = containerAppsEnvironment.outputs.environmentId
output workspaceId string = enableMonitoring ? monitoring.outputs.workspaceId : ''
{(includeNetworking ? @"output vnetId string = network.outputs.vnetId
output vnetName string = network.outputs.vnetName" : "")}
";
    }
    
    private string GenerateEnvironmentBicep(TemplateGenerationRequest request)
    {
        return @"// Container Apps Environment Configuration
// Implements managed environment with DAPR and monitoring

targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param workspaceId string
param workspaceKey string
param enableDapr bool
param enableVnetIntegration bool = false
param infrastructureSubnetId string = ''
param tags object

var environmentName = '${serviceName}-${environment}-env'

resource containerAppsEnvironment 'Microsoft.App/managedEnvironments@2023-05-01' = {
  name: environmentName
  location: location
  tags: tags
  properties: {
    // VNet Configuration
    vnetConfiguration: enableVnetIntegration && !empty(infrastructureSubnetId) ? {
      infrastructureSubnetId: infrastructureSubnetId
      internal: true
    } : null
    
    // Log Analytics integration
    appLogsConfiguration: !empty(workspaceId) ? {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: workspaceId
        sharedKey: workspaceKey
      }
    } : null
    
    // DAPR configuration
    daprAIInstrumentationKey: enableDapr ? '' : null
    daprAIConnectionString: enableDapr ? '' : null
    
    // Zone redundancy (available in supported regions)
    zoneRedundant: false
    
    // Workload profiles (consumption by default)
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
  }
}

// Virtual Network (optional - for VNET integration)
/* Uncomment for VNET integration
resource vnet 'Microsoft.Network/virtualNetworks@2023-05-01' = {
  name: '${serviceName}-${environment}-vnet'
  location: location
  tags: tags
  properties: {
    addressSpace: {
      addressPrefixes: [
        '10.0.0.0/16'
      ]
    }
    subnets: [
      {
        name: 'containerapps-subnet'
        properties: {
          addressPrefix: '10.0.0.0/23'
          delegations: [
            {
              name: 'Microsoft.App/environments'
              properties: {
                serviceName: 'Microsoft.App/environments'
              }
            }
          ]
        }
      }
    ]
  }
}
*/

output environmentId string = containerAppsEnvironment.id
output environmentName string = containerAppsEnvironment.name
output defaultDomain string = containerAppsEnvironment.properties.defaultDomain
output staticIp string = containerAppsEnvironment.properties.staticIp
";
    }
    
    private string GenerateContainerAppBicep(TemplateGenerationRequest request)
    {
        return @"// Container App Configuration
// Implements auto-scaling, health checks, and managed identity

targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param containerAppsEnvironmentId string
param containerImage string
param containerPort int
param enableDapr bool
param minReplicas int
param maxReplicas int
param cpuCores string
param memorySize string
param enableManagedIdentity bool = true
param allowInsecure bool = false
param externalIngress bool = true
param targetPort int = 80
param transport string = 'auto'
param maxInactiveRevisions int = 5
param revisionMode string = 'Single'
param enableIPRestrictions bool = false
param allowedIPRanges array = []
param tags object

var appName = '${serviceName}-${environment}'

resource containerApp 'Microsoft.App/containerApps@2023-05-01' = {
  name: appName
  location: location
  tags: tags
  identity: enableManagedIdentity ? {
    type: 'SystemAssigned'
  } : null
  properties: {
    managedEnvironmentId: containerAppsEnvironmentId
    
    configuration: {
      // Ingress configuration
      ingress: {
        external: externalIngress
        targetPort: targetPort
        transport: transport
        allowInsecure: allowInsecure
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
        // IP Security Restrictions
        ipSecurityRestrictions: enableIPRestrictions && !empty(allowedIPRanges) ? allowedIPRanges : []
      }
      
      // DAPR configuration
      dapr: enableDapr ? {
        enabled: true
        appId: appName
        appPort: containerPort
        appProtocol: 'http'
        enableApiLogging: true
        logLevel: 'info'
      } : null
      
      // Secrets (for container registry, connection strings, etc.)
      secrets: [
        /* Example:
        {
          name: 'registry-password'
          value: 'placeholder'
        }
        */
      ]
      
      // Registries (for private container registries)
      registries: [
        /* Example:
        {
          server: 'myregistry.azurecr.io'
          username: 'myregistry'
          passwordSecretRef: 'registry-password'
        }
        */
      ]
      
      // Revision configuration
      activeRevisionsMode: revisionMode
      maxInactiveRevisions: maxInactiveRevisions
    }
    
    template: {
      // Scaling rules
      scale: {
        minReplicas: minReplicas
        maxReplicas: maxReplicas
        rules: [
          {
            name: 'http-scaling-rule'
            http: {
              metadata: {
                concurrentRequests: '10'
              }
            }
          }
          {
            name: 'cpu-scaling-rule'
            custom: {
              type: 'cpu'
              metadata: {
                type: 'Utilization'
                value: '70'
              }
            }
          }
          {
            name: 'memory-scaling-rule'
            custom: {
              type: 'memory'
              metadata: {
                type: 'Utilization'
                value: '80'
              }
            }
          }
        ]
      }
      
      // Container configuration
      containers: [
        {
          name: appName
          image: containerImage
          resources: {
            cpu: json(cpuCores)
            memory: '${memorySize}Gi'
          }
          
          // Environment variables
          env: [
            {
              name: 'ASPNETCORE_ENVIRONMENT'
              value: environment
            }
            {
              name: 'NODE_ENV'
              value: environment == 'prod' ? 'production' : 'development'
            }
            {
              name: 'PORT'
              value: string(containerPort)
            }
          ]
          
          // Health probes
          probes: [
            {
              type: 'Liveness'
              httpGet: {
                path: '/health'
                port: containerPort
                scheme: 'HTTP'
              }
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            }
            {
              type: 'Readiness'
              httpGet: {
                path: '/ready'
                port: containerPort
                scheme: 'HTTP'
              }
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 3
            }
            {
              type: 'Startup'
              httpGet: {
                path: '/startup'
                port: containerPort
                scheme: 'HTTP'
              }
              initialDelaySeconds: 3
              periodSeconds: 3
              timeoutSeconds: 3
              failureThreshold: 30
            }
          ]
        }
      ]
      
      // Revision suffix
      revisionSuffix: ''
    }
  }
}

output name string = containerApp.name
output id string = containerApp.id
output fqdn string = containerApp.properties.configuration.ingress.fqdn
output latestRevisionName string = containerApp.properties.latestRevisionName
output systemAssignedIdentityPrincipalId string = enableManagedIdentity ? containerApp.identity.principalId : ''
";
    }
    
    private string GenerateIngressBicep(TemplateGenerationRequest request)
    {
        return @"// Ingress Configuration
// Implements traffic splitting and custom domains

targetScope = 'resourceGroup'

param serviceName string
param environment string
param containerAppName string
param customDomain string = ''
param certificateId string = ''

// Custom domain binding (if provided)
/* Uncomment when custom domain is available
resource customDomainBinding 'Microsoft.App/containerApps@2023-05-01' = if (!empty(customDomain)) {
  name: containerAppName
  properties: {
    configuration: {
      ingress: {
        customDomains: [
          {
            name: customDomain
            certificateId: certificateId
            bindingType: 'SniEnabled'
          }
        ]
      }
    }
  }
}
*/

// Traffic splitting example (for A/B testing or canary deployments)
/* Uncomment for traffic splitting
output trafficConfig array = [
  {
    revisionName: 'revision-v1'
    weight: 80
    label: 'stable'
  }
  {
    revisionName: 'revision-v2'
    weight: 20
    label: 'canary'
  }
]
*/
";
    }
    
    private string GenerateDaprBicep(TemplateGenerationRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// DAPR Components Configuration");
        sb.AppendLine("// Implements state store, pub/sub, and bindings");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine("param containerAppsEnvironmentName string");
        sb.AppendLine("param daprAppId string = ''");
        sb.AppendLine("param daprAppPort int = 80");
        sb.AppendLine("param daprEnableApiLogging bool = false");
        sb.AppendLine();
        sb.AppendLine("// State Store Component (using Azure Cosmos DB)");
        sb.AppendLine("resource stateStore 'Microsoft.App/managedEnvironments/daprComponents@2023-05-01' = {");
        sb.AppendLine("  name: '${containerAppsEnvironmentName}/statestore'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    componentType: 'state.azure.cosmosdb'");
        sb.AppendLine("    version: 'v1'");
        sb.AppendLine("    metadata: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'url'");
        sb.AppendLine("        value: '' // Set via secret or environment variable");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'masterKey'");
        sb.AppendLine("        secretRef: 'cosmos-master-key'");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'database'");
        sb.AppendLine("        value: '${serviceName}-db'");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'collection'");
        sb.AppendLine("        value: 'state'");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("    scopes: [");
        sb.AppendLine("      '${serviceName}-${environment}'");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Pub/Sub Component (using Azure Service Bus)");
        sb.AppendLine("resource pubSub 'Microsoft.App/managedEnvironments/daprComponents@2023-05-01' = {");
        sb.AppendLine("  name: '${containerAppsEnvironmentName}/pubsub'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    componentType: 'pubsub.azure.servicebus'");
        sb.AppendLine("    version: 'v1'");
        sb.AppendLine("    metadata: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'connectionString'");
        sb.AppendLine("        secretRef: 'servicebus-connection-string'");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("    scopes: [");
        sb.AppendLine("      '${serviceName}-${environment}'");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Binding Component (using Azure Blob Storage)");
        sb.AppendLine("resource binding 'Microsoft.App/managedEnvironments/daprComponents@2023-05-01' = {");
        sb.AppendLine("  name: '${containerAppsEnvironmentName}/blobstorage'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    componentType: 'bindings.azure.blobstorage'");
        sb.AppendLine("    version: 'v1'");
        sb.AppendLine("    metadata: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'storageAccount'");
        sb.AppendLine("        value: '${serviceName}${environment}storage'");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'storageAccessKey'");
        sb.AppendLine("        secretRef: 'storage-access-key'");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'container'");
        sb.AppendLine("        value: 'uploads'");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("    scopes: [");
        sb.AppendLine("      '${serviceName}-${environment}'");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Configuration Component (using Azure App Configuration)");
        sb.AppendLine("resource configuration 'Microsoft.App/managedEnvironments/daprComponents@2023-05-01' = {");
        sb.AppendLine("  name: '${containerAppsEnvironmentName}/configuration'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    componentType: 'configuration.azure.appconfig'");
        sb.AppendLine("    version: 'v1'");
        sb.AppendLine("    metadata: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'connectionString'");
        sb.AppendLine("        secretRef: 'appconfig-connection-string'");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("    scopes: [");
        sb.AppendLine("      '${serviceName}-${environment}'");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("output stateStoreName string = stateStore.name");
        sb.AppendLine("output pubSubName string = pubSub.name");
        sb.AppendLine("output bindingName string = binding.name");
        sb.AppendLine("output configurationName string = configuration.name");
        
        return sb.ToString();
    }
    
    private string GenerateMonitoringBicep(TemplateGenerationRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Monitoring Configuration");
        sb.AppendLine("// Implements Log Analytics workspace for Container Apps");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine("param location string");
        sb.AppendLine("param tags object");
        sb.AppendLine();
        sb.AppendLine("var workspaceName = '${serviceName}-${environment}-logs'");
        sb.AppendLine();
        sb.AppendLine("// Log Analytics Workspace");
        sb.AppendLine("resource workspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {");
        sb.AppendLine("  name: workspaceName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    sku: {");
        sb.AppendLine("      name: 'PerGB2018'");
        sb.AppendLine("    }");
        sb.AppendLine("    retentionInDays: 30");
        sb.AppendLine("    features: {");
        sb.AppendLine("      enableLogAccessUsingOnlyResourcePermissions: true");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Application Insights (optional - for deeper application monitoring)");
        sb.AppendLine("resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {");
        sb.AppendLine("  name: '${serviceName}-${environment}-ai'");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  kind: 'web'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    Application_Type: 'web'");
        sb.AppendLine("    WorkspaceResourceId: workspace.id");
        sb.AppendLine("    IngestionMode: 'LogAnalytics'");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("output workspaceId string = workspace.properties.customerId");
        sb.AppendLine("output workspaceKey string = workspace.listKeys().primarySharedKey");
        sb.AppendLine("output workspaceName string = workspace.name");
        sb.AppendLine("output applicationInsightsId string = applicationInsights.id");
        sb.AppendLine("output applicationInsightsInstrumentationKey string = applicationInsights.properties.InstrumentationKey");
        sb.AppendLine("output applicationInsightsConnectionString string = applicationInsights.properties.ConnectionString");
        
        return sb.ToString();
    }
    
    private string GeneratePrivateEndpointBicep(TemplateGenerationRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Private Endpoint for Container Apps Environment");
        sb.AppendLine("// Allows environment to be accessible only via private network");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine("param location string");
        sb.AppendLine("param containerAppsEnvironmentId string");
        sb.AppendLine("param subnetId string");
        sb.AppendLine("param virtualNetworkId string");
        sb.AppendLine("param tags object");
        sb.AppendLine();
        sb.AppendLine("var privateEndpointName = '${serviceName}-${environment}-cae-pe'");
        sb.AppendLine("var privateDnsZoneName = 'privatelink.azurecontainerapps.io'");
        sb.AppendLine("var pvtEndpointDnsGroupName = '${privateEndpointName}/default'");
        sb.AppendLine();
        sb.AppendLine("resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = {");
        sb.AppendLine("  name: privateEndpointName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    subnet: {");
        sb.AppendLine("      id: subnetId");
        sb.AppendLine("    }");
        sb.AppendLine("    privateLinkServiceConnections: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: '${serviceName}-${environment}-cae-plsc'");
        sb.AppendLine("        properties: {");
        sb.AppendLine("          privateLinkServiceId: containerAppsEnvironmentId");
        sb.AppendLine("          groupIds: ['managedEnvironments']");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' = {");
        sb.AppendLine("  name: privateDnsZoneName");
        sb.AppendLine("  location: 'global'");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {");
        sb.AppendLine("  parent: privateDnsZone");
        sb.AppendLine("  name: '${serviceName}-${environment}-cae-dns-link'");
        sb.AppendLine("  location: 'global'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    registrationEnabled: false");
        sb.AppendLine("    virtualNetwork: {");
        sb.AppendLine("      id: virtualNetworkId");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("resource pvtEndpointDnsGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = {");
        sb.AppendLine("  name: pvtEndpointDnsGroupName");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    privateDnsZoneConfigs: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'config1'");
        sb.AppendLine("        properties: {");
        sb.AppendLine("          privateDnsZoneId: privateDnsZone.id");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("  dependsOn: [");
        sb.AppendLine("    privateEndpoint");
        sb.AppendLine("  ]");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("output privateEndpointId string = privateEndpoint.id");
        sb.AppendLine("output privateDnsZoneId string = privateDnsZone.id");
        sb.AppendLine("output privateEndpointIP string = privateEndpoint.properties.customDnsConfigs[0].ipAddresses[0]");
        
        return sb.ToString();
    }
    
    private string GenerateParametersJson(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName.ToLowerInvariant();
        var application = request.Application ?? new ApplicationSpec();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var observability = request.Observability ?? new ObservabilitySpec();
        var security = request.Security ?? new SecuritySpec();
        
        // Determine intelligent defaults
        var isProduction = request.TemplateType?.ToLower().Contains("prod") ?? false;
        var enableMonitoring = observability.ApplicationInsights || observability.StructuredLogging;
        
        return $@"{{
  ""$schema"": ""https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#"",
  ""contentVersion"": ""1.0.0.0"",
  ""parameters"": {{
    ""serviceName"": {{
      ""value"": ""{serviceName}""
    }},
    ""environment"": {{
      ""value"": ""dev""
    }},
    ""location"": {{
      ""value"": ""{infrastructure.Region}""
    }},
    ""containerImage"": {{
      ""value"": ""mcr.microsoft.com/azuredocs/containerapps-helloworld:latest""
    }},
    ""containerPort"": {{
      ""value"": {application.Port}
    }},
    
    // === Container Apps Configuration ===
    ""minReplicas"": {{
      ""value"": {(isProduction ? 2 : 1)}
    }},
    ""maxReplicas"": {{
      ""value"": {(isProduction ? 30 : 10)}
    }},
    ""cpuCores"": {{
      ""value"": ""0.5""
    }},
    ""memorySize"": {{
      ""value"": ""1""
    }},
    
    // === Security Parameters ===
    ""enableManagedIdentity"": {{
      ""value"": true
    }},
    ""allowInsecure"": {{
      ""value"": false
    }},
    ""externalIngress"": {{
      ""value"": {(!isProduction).ToString().ToLower()}
    }},
    ""targetPort"": {{
      ""value"": {application.Port}
    }},
    ""transport"": {{
      ""value"": ""auto""
    }},
    
    // === VNet Integration ===
    ""enableVnetIntegration"": {{
      ""value"": {isProduction.ToString().ToLower()}
    }},
    ""vnetSubnetId"": {{
      ""value"": """"
    }},
    ""infrastructureSubnetId"": {{
      ""value"": """"
    }},
    ""enablePrivateEndpoint"": {{
      ""value"": {isProduction.ToString().ToLower()}
    }},
    
    // === DAPR & Service Mesh ===
    ""enableDapr"": {{
      ""value"": true
    }},
    ""daprAppId"": {{
      ""value"": ""{serviceName}""
    }},
    ""daprAppPort"": {{
      ""value"": {application.Port}
    }},
    ""daprEnableApiLogging"": {{
      ""value"": {enableMonitoring.ToString().ToLower()}
    }},
    
    // === Monitoring Parameters ===
    ""enableMonitoring"": {{
      ""value"": {enableMonitoring.ToString().ToLower()}
    }},
    ""logAnalyticsWorkspaceId"": {{
      ""value"": """"
    }},
    
    // === Advanced Security ===
    ""maxInactiveRevisions"": {{
      ""value"": 5
    }},
    ""revisionMode"": {{
      ""value"": ""Single""
    }},
    ""enableIPRestrictions"": {{
      ""value"": false
    }},
    ""allowedIPRanges"": {{
      ""value"": []
    }}
  }}
}}
";
    }
    
    private Dictionary<string, string> GetOrGenerateKeyVaultFiles(TemplateGenerationRequest request)
    {
        if (_cachedKeyVaultFiles == null)
        {
            var kvGenerator = new KeyVault.BicepKeyVaultModuleGenerator();
            _cachedKeyVaultFiles = kvGenerator.GenerateModule(request);
        }
        return _cachedKeyVaultFiles;
    }
    
    private Dictionary<string, string> GetOrGenerateNetworkFiles(TemplateGenerationRequest request)
    {
        if (_cachedNetworkFiles == null)
        {
            var networkGenerator = new Infrastructure.BicepNetworkResourceModuleGenerator();
            _cachedNetworkFiles = networkGenerator.GenerateModule(request);
        }
        return _cachedNetworkFiles;
    }
    
    private string GenerateNetworkBicep(TemplateGenerationRequest request)
    {
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var networkConfig = infrastructure.NetworkConfig ?? CreateDefaultContainerAppsNetworkConfig();
        
        // Check if using existing network or creating new
        if (networkConfig.Mode == NetworkMode.UseExisting)
        {
            return GenerateExistingNetworkReferencesBicep(networkConfig);
        }
        
        // Delegate to specialized BicepNetworkModuleGenerator for consistency and use cached results
        return GetOrGenerateNetworkFiles(request)["modules/network/main.bicep"];
    }
    
    private string GenerateExistingNetworkReferencesBicep(NetworkingConfiguration networkConfig)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Reference Existing Network Resources for Container Apps");
        sb.AppendLine("// Generated by Platform Engineering Copilot");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        
        // Parameters
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine($"param vnetName string = '{networkConfig.ExistingVNetName}'");
        sb.AppendLine($"param vnetResourceGroup string = '{networkConfig.ExistingVNetResourceGroup}'");
        sb.AppendLine("param location string = resourceGroup().location");
        sb.AppendLine("param tags object = {}");
        sb.AppendLine();
        
        // Reference existing VNet
        sb.AppendLine("// Reference existing Virtual Network");
        sb.AppendLine($"resource vnet 'Microsoft.Network/virtualNetworks@2023-05-01' existing = {{");
        sb.AppendLine($"  name: vnetName");
        sb.AppendLine($"  scope: resourceGroup(vnetResourceGroup)");
        sb.AppendLine("}");
        sb.AppendLine();
        
        // Find Container Apps subnet
        var containerAppsSubnet = networkConfig.ExistingSubnets.FirstOrDefault(s => 
            s.Purpose == SubnetPurpose.Application || s.Name.Contains("container") || s.Name.Contains("app"));
        
        if (containerAppsSubnet != null)
        {
            sb.AppendLine("// Reference existing Container Apps subnet");
            sb.AppendLine($"resource containerAppsSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {{");
            sb.AppendLine($"  parent: vnet");
            sb.AppendLine($"  name: '{containerAppsSubnet.Name}'");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("// WARNING: No Container Apps subnet found");
            sb.AppendLine("// Container Apps require a subnet with Microsoft.App/environments delegation");
            sb.AppendLine();
        }
        
        // Optionally create NSG if needed
        if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
        {
            sb.AppendLine("// Network Security Group for Container Apps");
            sb.AppendLine($"resource nsg 'Microsoft.Network/networkSecurityGroups@2023-05-01' = {{");
            sb.AppendLine($"  name: 'nsg-${{serviceName}}-${{environment}}-containerapps'");
            sb.AppendLine($"  location: location");
            sb.AppendLine($"  tags: tags");
            sb.AppendLine($"  properties: {{");
            sb.AppendLine($"    securityRules: [");
            
            foreach (var rule in networkConfig.NsgRules)
            {
                sb.AppendLine($"      {{");
                sb.AppendLine($"        name: '{rule.Name}'");
                sb.AppendLine($"        properties: {{");
                sb.AppendLine($"          priority: {rule.Priority}");
                sb.AppendLine($"          direction: '{rule.Direction}'");
                sb.AppendLine($"          access: '{rule.Access}'");
                sb.AppendLine($"          protocol: '{rule.Protocol}'");
                sb.AppendLine($"          sourcePortRange: '{rule.SourcePortRange}'");
                sb.AppendLine($"          destinationPortRange: '{rule.DestinationPortRange}'");
                sb.AppendLine($"          sourceAddressPrefix: '{rule.SourceAddressPrefix}'");
                sb.AppendLine($"          destinationAddressPrefix: '{rule.DestinationAddressPrefix}'");
                sb.AppendLine($"          description: '{rule.Description}'");
                sb.AppendLine($"        }}");
                sb.AppendLine($"      }}");
            }
            
            sb.AppendLine($"    ]");
            sb.AppendLine($"  }}");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Outputs
        sb.AppendLine("// Outputs");
        sb.AppendLine("output vnetId string = vnet.id");
        
        if (containerAppsSubnet != null)
        {
            sb.AppendLine("output containerAppsSubnetId string = containerAppsSubnet.id");
        }
        
        if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
        {
            sb.AppendLine("output nsgId string = nsg.id");
        }
        
        return sb.ToString();
    }
    
    private NetworkingConfiguration CreateDefaultContainerAppsNetworkConfig()
    {
        return new NetworkingConfiguration
        {
            Mode = NetworkMode.CreateNew,
            VNetName = "${serviceName}-${environment}-vnet",
            VNetAddressSpace = "10.0.0.0/16",
            Subnets = new List<SubnetConfiguration>
            {
                new SubnetConfiguration
                {
                    Name = "containerapps-subnet",
                    AddressPrefix = "10.0.0.0/23",
                    Delegation = "Microsoft.App/environments",
                    Purpose = SubnetPurpose.Application
                }
            },
            EnableNetworkSecurityGroup = true,
            EnablePrivateEndpoint = false,
            EnableServiceEndpoints = false,
            EnableDDoSProtection = false,
            EnablePrivateDns = false
        };
    }
}

