using System.Text;
using Platform.Engineering.Copilot.Core.Interfaces;
using Platform.Engineering.Copilot.Core.Interfaces.TemplateGeneration;
using Platform.Engineering.Copilot.Core.Models;
using Platform.Engineering.Copilot.Core.Models.TemplateGeneration;

namespace Platform.Engineering.Copilot.Core.Services.Generators.Containers;

/// <summary>
/// Bicep module generator for Azure Container Apps infrastructure
/// Implements IResourceModuleGenerator for composition-based generation
/// Cross-cutting concerns (PE, diagnostics, RBAC) are handled by reusable generators
/// </summary>
public class BicepContainerAppsResourceModuleGenerator : IResourceModuleGenerator
{    
    public InfrastructureFormat Format => InfrastructureFormat.Bicep;
    public ComputePlatform Platform => ComputePlatform.ContainerApps;
    public CloudProvider Provider => CloudProvider.Azure;
    
    /// <summary>
    /// Resource types this generator handles
    /// </summary>
    public string[] SupportedResourceTypes => new[] 
    { 
        "container-apps", 
        "containerapps", 
        "aca",
        "azure-container-apps"
    };
    
    /// <summary>
    /// Cross-cutting capabilities supported by Container Apps
    /// </summary>
    public CrossCuttingType[] SupportedCrossCutting => new[]
    {
        CrossCuttingType.PrivateEndpoint,
        CrossCuttingType.DiagnosticSettings,
        CrossCuttingType.RBACAssignment,
        CrossCuttingType.ManagedIdentity
    };
    
    /// <summary>
    /// Azure resource type for Container Apps Environment
    /// (The environment is the resource that supports Private Endpoints)
    /// </summary>
    public string AzureResourceType => "Microsoft.App/managedEnvironments";

    /// <summary>
    /// Generate ONLY the core Container Apps resource - cross-cutting modules are composed by orchestrator
    /// </summary>
    public ResourceModuleResult GenerateCoreResource(TemplateGenerationRequest request)
    {
        var files = new Dictionary<string, string>();
        var serviceName = request.ServiceName ?? "containerapp";

        // Generate core Container Apps module files
        files["container-app-environment.bicep"] = GenerateEnvironmentBicep(request);
        files["container-app.bicep"] = GenerateContainerAppBicep(request);
        files["main.bicep"] = GenerateCoreMainBicep(request);
        files["README.md"] = GenerateReadme(request);

        return new ResourceModuleResult
        {
            Files = files,
            ResourceReference = "containerAppEnvironment", // Module name for cross-cutting references
            ResourceType = "Microsoft.App/managedEnvironments",
            OutputNames = new List<string>
            {
                "environmentId",
                "environmentName",
                "containerAppId",
                "containerAppName",
                "containerAppFqdn",
                "principalId",
                "resourceId",
                "resourceName"
            },
            SupportedCrossCutting = new List<CrossCuttingType>
            {
                CrossCuttingType.PrivateEndpoint,
                CrossCuttingType.DiagnosticSettings,
                CrossCuttingType.RBACAssignment,
                CrossCuttingType.ManagedIdentity
            }
        };
    }

    /// <summary>
    /// Legacy GenerateModule - delegates to legacy generator for full template generation
    /// </summary>
    public Dictionary<string, string> GenerateModule(TemplateGenerationRequest request)
    {
        var result = GenerateCoreResource(request);
        return result.Files;
    }
    
    /// <summary>
    /// Check if this generator can handle the request
    /// </summary>
    public bool CanGenerate(TemplateGenerationRequest request)
    {
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        return infrastructure.Format == InfrastructureFormat.Bicep &&
               infrastructure.Provider == CloudProvider.Azure &&
               infrastructure.ComputePlatform == ComputePlatform.ContainerApps;
    }

    /// <summary>
    /// Generate Container Apps Environment Bicep module
    /// </summary>
    private string GenerateEnvironmentBicep(TemplateGenerationRequest request)
    {
        return @"// Azure Container Apps Environment - Core Resource Module
// FedRAMP Controls: SC-7 (Network Isolation), AU-2 (Logging)
// Generated by Platform Engineering Copilot

@description('Name of the Container Apps Environment')
param environmentName string

@description('Azure region')
param location string = resourceGroup().location

@description('Log Analytics Workspace ID (optional)')
param logAnalyticsWorkspaceId string = ''

@description('Subnet ID for VNet integration (optional)')
param subnetId string = ''

@description('Enable internal load balancer')
param internal bool = true

@description('Tags')
param tags object = {}

// Container Apps Environment
resource containerAppEnvironment 'Microsoft.App/managedEnvironments@2023-05-01' = {
  name: environmentName
  location: location
  tags: tags
  properties: {
    // FedRAMP SC-7: Internal mode for network isolation
    vnetConfiguration: !empty(subnetId) ? {
      internal: internal
      infrastructureSubnetId: subnetId
    } : null
    // FedRAMP AU-2: Logging to Log Analytics
    appLogsConfiguration: !empty(logAnalyticsWorkspaceId) ? {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: reference(logAnalyticsWorkspaceId, '2022-10-01').customerId
        sharedKey: listKeys(logAnalyticsWorkspaceId, '2022-10-01').primarySharedKey
      }
    } : {
      destination: 'azure-monitor'
    }
    // Zone redundancy for production
    zoneRedundant: true
  }
}

// Outputs for cross-cutting module composition
@description('Container Apps Environment ID')
output environmentId string = containerAppEnvironment.id

@description('Container Apps Environment Name')
output environmentName string = containerAppEnvironment.name

@description('Default Domain')
output defaultDomain string = containerAppEnvironment.properties.defaultDomain

@description('Static IP (for internal environments)')
output staticIp string = containerAppEnvironment.properties.staticIp ?? ''

@description('Resource ID (alias)')
output resourceId string = containerAppEnvironment.id

@description('Resource Name (alias)')
output resourceName string = containerAppEnvironment.name
";
    }

    /// <summary>
    /// Generate Container App Bicep module
    /// </summary>
    private string GenerateContainerAppBicep(TemplateGenerationRequest request)
    {
        return @"// Azure Container App - Core Resource Module
// FedRAMP Controls: SC-8 (TLS), AC-3 (Managed Identity), SC-7 (Ingress Control)
// Generated by Platform Engineering Copilot

@description('Name of the Container App')
param containerAppName string

@description('Container Apps Environment ID')
param environmentId string

@description('Azure region')
param location string = resourceGroup().location

@description('Container image')
param containerImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Container port')
param containerPort int = 80

@description('CPU cores')
param cpuCores string = '0.5'

@description('Memory in GB')
param memorySize string = '1'

@description('Minimum replicas')
param minReplicas int = 1

@description('Maximum replicas')
param maxReplicas int = 10

@description('Enable managed identity')
param enableManagedIdentity bool = true

@description('External ingress')
param externalIngress bool = false

@description('Allow insecure connections')
param allowInsecure bool = false

@description('Tags')
param tags object = {}

// Container App Resource
resource containerApp 'Microsoft.App/containerApps@2023-05-01' = {
  name: containerAppName
  location: location
  tags: tags
  identity: enableManagedIdentity ? {
    type: 'SystemAssigned'
  } : null
  properties: {
    managedEnvironmentId: environmentId
    configuration: {
      // FedRAMP SC-7: Ingress control
      ingress: {
        external: externalIngress
        targetPort: containerPort
        // FedRAMP SC-8: TLS enforcement
        transport: 'http'
        allowInsecure: allowInsecure
        traffic: [
          {
            latestRevision: true
            weight: 100
          }
        ]
      }
      // No secrets in code - use Key Vault references
      secrets: []
    }
    template: {
      containers: [
        {
          name: containerAppName
          image: containerImage
          resources: {
            cpu: json(cpuCores)
            memory: '${memorySize}Gi'
          }
        }
      ]
      scale: {
        minReplicas: minReplicas
        maxReplicas: maxReplicas
        rules: [
          {
            name: 'http-scaling'
            http: {
              metadata: {
                concurrentRequests: '100'
              }
            }
          }
        ]
      }
    }
  }
}

// Outputs for cross-cutting module composition
@description('Container App ID')
output containerAppId string = containerApp.id

@description('Container App Name')
output containerAppName string = containerApp.name

@description('Container App FQDN')
output containerAppFqdn string = containerApp.properties.configuration.ingress != null ? containerApp.properties.configuration.ingress.fqdn : ''

@description('Latest Revision Name')
output latestRevisionName string = containerApp.properties.latestRevisionName

@description('Principal ID for RBAC assignments')
output principalId string = enableManagedIdentity ? containerApp.identity.principalId : ''

@description('Resource ID (alias)')
output resourceId string = containerApp.id

@description('Resource Name (alias)')
output resourceName string = containerApp.name
";
    }

    /// <summary>
    /// Generate core main.bicep that composes the Container Apps modules
    /// </summary>
    private string GenerateCoreMainBicep(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "containerapp";

        return $@"// Container Apps - Main Module (Core Resources Only)
// Cross-cutting concerns are composed by CompositeInfrastructureGenerator
// Generated by Platform Engineering Copilot

targetScope = 'resourceGroup'

@description('Service name')
param serviceName string = '{serviceName}'

@description('Environment')
param environment string = 'dev'

@description('Azure region')
param location string = resourceGroup().location

@description('Container image')
param containerImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Container port')
param containerPort int = 80

@description('Enable managed identity')
param enableManagedIdentity bool = true

@description('External ingress')
param externalIngress bool = false

@description('Log Analytics Workspace ID (optional)')
param logAnalyticsWorkspaceId string = ''

@description('Subnet ID for VNet integration (optional)')
param subnetId string = ''

// Variables
var resourcePrefix = '${{serviceName}}-${{environment}}'
var environmentName = '${{resourcePrefix}}-env'
var containerAppName = '${{resourcePrefix}}-app'

var tags = {{
  service: serviceName
  environment: environment
  managedBy: 'platform-engineering-copilot'
}}

// Container Apps Environment
module containerAppEnvironment 'container-app-environment.bicep' = {{
  name: 'deploy-container-app-environment'
  params: {{
    environmentName: environmentName
    location: location
    logAnalyticsWorkspaceId: logAnalyticsWorkspaceId
    subnetId: subnetId
    tags: tags
  }}
}}

// Container App
module containerApp 'container-app.bicep' = {{
  name: 'deploy-container-app'
  params: {{
    containerAppName: containerAppName
    environmentId: containerAppEnvironment.outputs.environmentId
    location: location
    containerImage: containerImage
    containerPort: containerPort
    enableManagedIdentity: enableManagedIdentity
    externalIngress: externalIngress
    tags: tags
  }}
}}

// Outputs for cross-cutting module composition
output environmentId string = containerAppEnvironment.outputs.environmentId
output environmentName string = containerAppEnvironment.outputs.environmentName
output containerAppId string = containerApp.outputs.containerAppId
output containerAppName string = containerApp.outputs.containerAppName
output containerAppFqdn string = containerApp.outputs.containerAppFqdn
output principalId string = containerApp.outputs.principalId
output resourceId string = containerAppEnvironment.outputs.resourceId
output resourceName string = containerAppEnvironment.outputs.resourceName
";
    }

    /// <summary>
    /// Generate README for the module
    /// </summary>
    private string GenerateReadme(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "containerapp";

        return $@"# Azure Container Apps Bicep Module

## Overview
This module deploys Azure Container Apps with FedRAMP-compliant security controls.

## Resources Created
- Container Apps Environment (Microsoft.App/managedEnvironments)
- Container App (Microsoft.App/containerApps)

## FedRAMP Controls Implemented
- **SC-7**: Internal mode, VNet integration, ingress control
- **SC-8**: TLS enforcement, insecure connections disabled
- **AC-3**: Managed Identity for authentication
- **AU-2**: Log Analytics integration
- **SC-5**: Zone redundancy, auto-scaling

## Cross-Cutting Concerns
This module exposes outputs for composition with:
- Private Endpoint (network isolation for environment)
- Diagnostic Settings (Log Analytics integration)
- RBAC Assignments (access control)

## Usage
```bicep
module containerApps 'main.bicep' = {{
  name: 'deploy-{serviceName}'
  params: {{
    serviceName: '{serviceName}'
    environment: 'dev'
    containerImage: 'myregistry.azurecr.io/myapp:latest'
    containerPort: 8080
    enableManagedIdentity: true
    externalIngress: false
  }}
}}
```

## Outputs
| Name | Description |
|------|-------------|
| environmentId | Resource ID of the Container Apps Environment |
| environmentName | Name of the Container Apps Environment |
| containerAppId | Resource ID of the Container App |
| containerAppName | Name of the Container App |
| containerAppFqdn | FQDN for the Container App |
| principalId | Managed Identity principal ID |
";
    }
}
