using System.Text;
using Platform.Engineering.Copilot.Core.Interfaces;
using Platform.Engineering.Copilot.Core.Interfaces.TemplateGeneration;
using Platform.Engineering.Copilot.Core.Models;
using Platform.Engineering.Copilot.Core.Models.TemplateGeneration;

namespace Platform.Engineering.Copilot.Core.Services.Generators.Containers;

/// <summary>
/// Terraform module generator for Azure Container Instances infrastructure
/// Implements IResourceModuleGenerator for composition-based generation
/// Cross-cutting concerns (PE, diagnostics, RBAC) are handled by reusable generators
/// </summary>
public class TerraformContainerInstancesResourceModuleGenerator : IResourceModuleGenerator
{
    public InfrastructureFormat Format => InfrastructureFormat.Terraform;
    public ComputePlatform Platform => ComputePlatform.ContainerApps; // ACI is mapped to ContainerApps platform
    public CloudProvider Provider => CloudProvider.Azure;

    /// <summary>
    /// Resource types this generator handles
    /// </summary>
    public string[] SupportedResourceTypes => new[]
    {
        "container-instances",
        "aci",
        "azure-container-instances",
        "containerinstances"
    };

    /// <summary>
    /// Cross-cutting capabilities supported by Container Instances
    /// </summary>
    public CrossCuttingType[] SupportedCrossCutting => new[]
    {
        CrossCuttingType.PrivateEndpoint,
        CrossCuttingType.DiagnosticSettings,
        CrossCuttingType.RBACAssignment,
        CrossCuttingType.ManagedIdentity
    };

    /// <summary>
    /// Azure resource type for Container Instances
    /// </summary>
    public string AzureResourceType => "Microsoft.ContainerInstance/containerGroups";

    /// <summary>
    /// Generate ONLY the core Container Instances resource - cross-cutting modules are composed by orchestrator
    /// </summary>
    public ResourceModuleResult GenerateCoreResource(TemplateGenerationRequest request)
    {
        var files = new Dictionary<string, string>();
        var serviceName = request.ServiceName ?? "aci";

        // Generate core Container Instances module files
        files["modules/container-group/main.tf"] = GenerateCoreMainTf(request);
        files["modules/container-group/variables.tf"] = GenerateCoreVariablesTf(request);
        files["modules/container-group/outputs.tf"] = GenerateCoreOutputsTf(request);
        files["main.tf"] = GenerateRootMainTf(request);
        files["README.md"] = GenerateReadme(request);

        return new ResourceModuleResult
        {
            Files = files,
            ResourceReference = "azurerm_container_group.main", // Terraform resource reference
            ResourceType = "Microsoft.ContainerInstance/containerGroups",
            OutputNames = new List<string>
            {
                "container_group_id",
                "container_group_name",
                "container_group_fqdn",
                "container_group_ip_address",
                "principal_id"
            },
            SupportedCrossCutting = new List<CrossCuttingType>
            {
                CrossCuttingType.PrivateEndpoint,
                CrossCuttingType.DiagnosticSettings,
                CrossCuttingType.RBACAssignment,
                CrossCuttingType.ManagedIdentity
            }
        };
    }

    /// <summary>
    /// GenerateModule - generates the full module files
    /// </summary>
    public Dictionary<string, string> GenerateModule(TemplateGenerationRequest request)
    {
        var result = GenerateCoreResource(request);
        return result.Files;
    }

    /// <summary>
    /// Check if this generator can handle the request
    /// </summary>
    public bool CanGenerate(TemplateGenerationRequest request)
    {
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        return infrastructure.Format == InfrastructureFormat.Terraform &&
               infrastructure.Provider == CloudProvider.Azure &&
               infrastructure.ComputePlatform == ComputePlatform.ContainerApps;
    }

    /// <summary>
    /// Generate core Container Group main.tf
    /// </summary>
    private string GenerateCoreMainTf(TemplateGenerationRequest request)
    {
        return @"# Azure Container Instances - Core Resource Module
# FedRAMP Controls: SC-7 (Network Isolation), AC-3 (Managed Identity), AU-2 (Logging), SC-8 (TLS)
# Generated by Platform Engineering Copilot

resource ""azurerm_container_group"" ""main"" {
  name                = var.container_group_name
  resource_group_name = var.resource_group_name
  location            = var.location
  os_type             = var.os_type

  # FedRAMP AC-3: Managed Identity
  dynamic ""identity"" {
    for_each = var.enable_managed_identity ? [1] : []
    content {
      type = ""SystemAssigned""
    }
  }

  # Container definition
  container {
    name   = var.container_name
    image  = var.container_image
    cpu    = var.cpu_cores
    memory = var.memory_gb

    ports {
      port     = var.container_port
      protocol = ""TCP""
    }

    # Environment variables
    dynamic ""environment_variables"" {
      for_each = var.environment_variables
      content {
        name  = environment_variables.key
        value = environment_variables.value
      }
    }

    # Health probe
    dynamic ""liveness_probe"" {
      for_each = var.enable_health_probe ? [1] : []
      content {
        http_get {
          path   = var.health_probe_path
          port   = var.container_port
          scheme = ""Http""
        }
        initial_delay_seconds = 30
        period_seconds        = 10
        failure_threshold     = 3
      }
    }
  }

  # FedRAMP SC-7: Network configuration for VNet integration
  dynamic ""subnet_ids"" {
    for_each = var.subnet_id != """" ? [var.subnet_id] : []
    content {
      # Network isolation via subnet
    }
  }

  # DNS configuration
  dns_config {
    nameservers = var.dns_nameservers
  }

  # Restart policy
  restart_policy = var.restart_policy

  tags = var.tags
}
";
    }

    /// <summary>
    /// Generate core Container Group variables.tf
    /// </summary>
    private string GenerateCoreVariablesTf(TemplateGenerationRequest request)
    {
        return @"# Container Group Variables

variable ""container_group_name"" {
  description = ""Name of the Container Group""
  type        = string
}

variable ""container_name"" {
  description = ""Name of the container""
  type        = string
}

variable ""resource_group_name"" {
  description = ""Name of the resource group""
  type        = string
}

variable ""location"" {
  description = ""Azure region""
  type        = string
}

variable ""os_type"" {
  description = ""OS type (Linux or Windows)""
  type        = string
  default     = ""Linux""
}

variable ""container_image"" {
  description = ""Container image to deploy""
  type        = string
}

variable ""container_port"" {
  description = ""Port exposed by the container""
  type        = number
  default     = 80
}

variable ""cpu_cores"" {
  description = ""CPU cores for the container""
  type        = string
  default     = ""1.0""
}

variable ""memory_gb"" {
  description = ""Memory in GB for the container""
  type        = string
  default     = ""1.5""
}

variable ""enable_managed_identity"" {
  description = ""Enable system-assigned managed identity""
  type        = bool
  default     = true
}

variable ""environment_variables"" {
  description = ""Environment variables for the container""
  type        = map(string)
  default     = {}
}

variable ""enable_health_probe"" {
  description = ""Enable liveness health probe""
  type        = bool
  default     = true
}

variable ""health_probe_path"" {
  description = ""Path for health probe""
  type        = string
  default     = ""/health""
}

variable ""subnet_id"" {
  description = ""Subnet ID for VNet integration""
  type        = string
  default     = """"
}

variable ""dns_nameservers"" {
  description = ""DNS nameservers""
  type        = list(string)
  default     = []
}

variable ""restart_policy"" {
  description = ""Restart policy (Always, OnFailure, Never)""
  type        = string
  default     = ""Always""
}

variable ""tags"" {
  description = ""Tags to apply to resources""
  type        = map(string)
  default     = {}
}
";
    }

    /// <summary>
    /// Generate core Container Group outputs.tf
    /// </summary>
    private string GenerateCoreOutputsTf(TemplateGenerationRequest request)
    {
        return @"# Container Group Outputs

output ""container_group_id"" {
  description = ""ID of the Container Group""
  value       = azurerm_container_group.main.id
}

output ""container_group_name"" {
  description = ""Name of the Container Group""
  value       = azurerm_container_group.main.name
}

output ""container_group_fqdn"" {
  description = ""FQDN of the Container Group""
  value       = try(azurerm_container_group.main.fqdn, """")
}

output ""container_group_ip_address"" {
  description = ""IP address of the Container Group""
  value       = try(azurerm_container_group.main.ip_address, """")
}

output ""principal_id"" {
  description = ""Principal ID of the managed identity""
  value       = try(azurerm_container_group.main.identity[0].principal_id, """")
}

output ""resource_id"" {
  description = ""Resource ID (alias for container_group_id)""
  value       = azurerm_container_group.main.id
}
";
    }

    /// <summary>
    /// Generate root main.tf that composes the modules
    /// </summary>
    private string GenerateRootMainTf(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "aci";
        var application = request.Application ?? new ApplicationSpec();

        return $@"# Container Instances - Main Terraform Configuration (Core Resources Only)
# Cross-cutting concerns are composed by CompositeInfrastructureGenerator
# Generated by Platform Engineering Copilot

terraform {{
  required_version = "">= 1.5.0""

  required_providers {{
    azurerm = {{
      source  = ""hashicorp/azurerm""
      version = ""~> 3.0""
    }}
  }}
}}

provider ""azurerm"" {{
  features {{}}
}}

# Variables
variable ""service_name"" {{
  description = ""Name of the service""
  type        = string
  default     = ""{serviceName}""
}}

variable ""environment"" {{
  description = ""Environment (dev, staging, prod)""
  type        = string
  default     = ""dev""
}}

variable ""location"" {{
  description = ""Azure region""
  type        = string
  default     = ""eastus""
}}

variable ""resource_group_name"" {{
  description = ""Name of the resource group""
  type        = string
}}

variable ""container_image"" {{
  description = ""Container image to deploy""
  type        = string
  default     = ""mcr.microsoft.com/azuredocs/aci-helloworld:latest""
}}

variable ""container_port"" {{
  description = ""Port exposed by the container""
  type        = number
  default     = {(application.Port > 0 ? application.Port : 80)}
}}

# Local variables
locals {{
  resource_prefix      = ""${{var.service_name}}-${{var.environment}}""
  container_group_name = ""aci-${{local.resource_prefix}}""
  container_name       = var.service_name

  tags = {{
    service     = var.service_name
    environment = var.environment
    managed_by  = ""platform-engineering-copilot""
  }}
}}

# Container Group
module ""container_group"" {{
  source = ""./modules/container-group""

  container_group_name = local.container_group_name
  container_name       = local.container_name
  resource_group_name  = var.resource_group_name
  location             = var.location
  container_image      = var.container_image
  container_port       = var.container_port
  tags                 = local.tags
}}

# Outputs for cross-cutting module composition
output ""container_group_id"" {{
  value = module.container_group.container_group_id
}}

output ""container_group_name"" {{
  value = module.container_group.container_group_name
}}

output ""container_group_fqdn"" {{
  value = module.container_group.container_group_fqdn
}}

output ""container_group_ip_address"" {{
  value = module.container_group.container_group_ip_address
}}

output ""principal_id"" {{
  value = module.container_group.principal_id
}}
";
    }

    /// <summary>
    /// Generate README for the module
    /// </summary>
    private string GenerateReadme(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "aci";

        return $@"# Azure Container Instances Terraform Module

## Overview
This module deploys Azure Container Instances with FedRAMP-compliant security controls.

## Resources Created
- Container Group (azurerm_container_group)

## FedRAMP Controls Implemented
- **SC-7**: VNet integration, network isolation
- **SC-8**: TLS for container communication
- **AC-3**: Managed Identity for authentication
- **AU-2**: Logging to Azure Monitor
- **SC-5**: Health probes, restart policies

## Cross-Cutting Concerns
This module exposes outputs for composition with:
- Private Endpoint (network isolation)
- Diagnostic Settings (Log Analytics integration)
- RBAC Assignments (access control)

## Usage
```hcl
module ""container_instances"" {{
  source = ""./modules/container-group""

  service_name        = ""{serviceName}""
  environment         = ""dev""
  resource_group_name = azurerm_resource_group.main.name
  location            = ""eastus""
  container_image     = ""myregistry.azurecr.io/myapp:latest""
  container_port      = 8080
}}
```

## Outputs
| Name | Description |
|------|-------------|
| container_group_id | Resource ID of the Container Group |
| container_group_name | Name of the Container Group |
| container_group_fqdn | FQDN of the Container Group |
| container_group_ip_address | IP address |
| principal_id | Managed Identity principal ID |
";
    }
}
