using System.Text;
using System.Linq;
using System.Collections.Generic;
using Platform.Engineering.Copilot.Core.Models;

namespace Platform.Engineering.Copilot.Core.Services.Generators.AppService;

/// <summary>
/// Generates Azure App Service Bicep module files
/// Implements Azure best practices including Application Insights, Key Vault integration, and managed identity
/// </summary>
public class BicepAppServiceModuleGenerator
{
    // Cache for delegated module generators to avoid regenerating multiple times
    private Dictionary<string, string>? _cachedKeyVaultFiles;
    private Dictionary<string, string>? _cachedNetworkFiles;

    /// <summary>
    /// Generate complete App Service module with app service plan, web app, and monitoring
    /// </summary>
    public Dictionary<string, string> GenerateAppServiceModule(TemplateGenerationRequest request)
    {
        var files = new Dictionary<string, string>();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        
        var modulePath = "modules";
        
        // Generate module files - each module is a single .bicep file following Bicep best practices
        files["main.bicep"] = GenerateMainBicep(request);
        files[$"{modulePath}/app-service-plan.bicep"] = GenerateAppServicePlanBicep(request);
        files[$"{modulePath}/web-app.bicep"] = GenerateWebAppBicep(request);
        files[$"{modulePath}/application-insights.bicep"] = GenerateApplicationInsightsBicep(request);
        files[$"{modulePath}/key-vault.bicep"] = GenerateKeyVaultBicep(request);
        files[$"{modulePath}/private-endpoint.bicep"] = GeneratePrivateEndpointBicep(request);
        files["parameters.json"] = GenerateParametersJson(request);
        
        // Optional: Networking
        if (infrastructure.IncludeNetworking == true)
        {
            files[$"{modulePath}/network.bicep"] = GenerateNetworkBicep(request);
        }
        
        return files;
    }
    
    private string GenerateMainBicep(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName.ToLowerInvariant();
        var application = request.Application ?? new ApplicationSpec();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var runtime = GetRuntimeStack(application.Language);
        var includeNetworking = infrastructure.IncludeNetworking == true;
        
        var sb = new StringBuilder();
        
        sb.AppendLine("// App Service Module - Main Entry Point - FedRAMP Compliant");
        sb.AppendLine("// Implements: SC-8 (TLS Encryption), AC-3 (Managed Identity), AU-2 (Logging), SC-7 (Network Isolation)");
        sb.AppendLine("// Generated by Platform Engineering Copilot");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("@description('Name of the service')");
        sb.AppendLine("param serviceName string");
        sb.AppendLine();
        sb.AppendLine("@description('Environment (dev, staging, prod)')");
        sb.AppendLine("param environment string");
        sb.AppendLine();
        sb.AppendLine("@description('Azure region')");
        sb.AppendLine("param location string = resourceGroup().location");
        sb.AppendLine();
        sb.AppendLine("@description('App Service Plan SKU')");
        sb.AppendLine("@allowed([");
        sb.AppendLine("  'B1'");
        sb.AppendLine("  'B2'");
        sb.AppendLine("  'B3'");
        sb.AppendLine("  'S1'");
        sb.AppendLine("  'S2'");
        sb.AppendLine("  'S3'");
        sb.AppendLine("  'P1v2'");
        sb.AppendLine("  'P2v2'");
        sb.AppendLine("  'P3v2'");
        sb.AppendLine("  'P1v3'");
        sb.AppendLine("  'P2v3'");
        sb.AppendLine("  'P3v3'");
        sb.AppendLine("])");
        sb.AppendLine("param appServicePlanSku string = 'P1v3'");
        sb.AppendLine();
        sb.AppendLine("@description('Runtime stack')");
        sb.AppendLine($"param runtimeStack string = '{runtime}'");
        sb.AppendLine();
        sb.AppendLine("@description('Enable Application Insights')");
        sb.AppendLine("param enableApplicationInsights bool = true");
        sb.AppendLine();
        sb.AppendLine("@description('Enable Always On')");
        sb.AppendLine("param alwaysOn bool = true");
        sb.AppendLine();
        sb.AppendLine("@description('Enable HTTPS only')");
        sb.AppendLine("param httpsOnly bool = true");
        sb.AppendLine();
        sb.AppendLine("@description('Enable VNet Integration')");
        sb.AppendLine("param enableVnetIntegration bool = false");
        sb.AppendLine();
        sb.AppendLine("@description('Enable Private Endpoint')");
        sb.AppendLine("param enablePrivateEndpoint bool = false");
        sb.AppendLine();
        sb.AppendLine("@description('FTP State')");
        sb.AppendLine("@allowed(['AllAllowed', 'FtpsOnly', 'Disabled'])");
        sb.AppendLine("param ftpsState string = 'FtpsOnly'");
        sb.AppendLine();
        sb.AppendLine("@description('Minimum TLS Version')");
        sb.AppendLine("@allowed(['1.0', '1.1', '1.2', '1.3'])");
        sb.AppendLine("param minTlsVersion string = '1.2'");
        sb.AppendLine();
        sb.AppendLine("@description('Enable Managed Identity')");
        sb.AppendLine("param enableManagedIdentity bool = true");
        sb.AppendLine();
        sb.AppendLine("@description('Enable Client Certificate (Mutual TLS)')");
        sb.AppendLine("param enableClientCertificate bool = false");
        sb.AppendLine();
        sb.AppendLine("@description('Client Certificate Mode')");
        sb.AppendLine("@allowed(['Optional', 'OptionalInteractiveUser', 'Required'])");
        sb.AppendLine("param clientCertMode string = 'Optional'");
        sb.AppendLine();
        sb.AppendLine("@description('Enable Detailed Error Messages')");
        sb.AppendLine("param enableDetailedErrorMessages bool = false");
        sb.AppendLine();
        sb.AppendLine("@description('Enable HTTP Logging')");
        sb.AppendLine("param enableHttpLogging bool = false");
        sb.AppendLine();
        sb.AppendLine("@description('IP Security Restrictions')");
        sb.AppendLine("param ipSecurityRestrictions array = []");
        sb.AppendLine();
        sb.AppendLine("var commonTags = {");
        sb.AppendLine("  Environment: environment");
        sb.AppendLine("  Service: serviceName");
        sb.AppendLine("  ManagedBy: 'bicep'");
        sb.AppendLine("  Platform: 'AppService'");
        sb.AppendLine("}");
        sb.AppendLine();
        
        if (includeNetworking)
        {
            sb.AppendLine("// Network Infrastructure");
            sb.AppendLine("module network './modules/network.bicep' = {");
            sb.AppendLine("  name: '${serviceName}-${environment}-network'");
            sb.AppendLine("  params: {");
            sb.AppendLine("    serviceName: serviceName");
            sb.AppendLine("    location: location");
            sb.AppendLine("    tags: commonTags");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        sb.AppendLine("// Application Insights");
        sb.AppendLine("module applicationInsights './modules/application-insights.bicep' = if (enableApplicationInsights) {");
        sb.AppendLine("  name: '${serviceName}-${environment}-appinsights'");
        sb.AppendLine("  params: {");
        sb.AppendLine("    serviceName: serviceName");
        sb.AppendLine("    environment: environment");
        sb.AppendLine("    location: location");
        sb.AppendLine("    tags: commonTags");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        sb.AppendLine("// Key Vault");
        sb.AppendLine("module keyVault './modules/key-vault.bicep' = {");
        sb.AppendLine("  name: '${serviceName}-${environment}-keyvault'");
        sb.AppendLine("  params: {");
        sb.AppendLine("    serviceName: serviceName");
        sb.AppendLine("    environment: environment");
        sb.AppendLine("    location: location");
        sb.AppendLine("    tags: commonTags");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        sb.AppendLine("// App Service Plan");
        sb.AppendLine("module appServicePlan './modules/app-service-plan.bicep' = {");
        sb.AppendLine("  name: '${serviceName}-${environment}-plan'");
        sb.AppendLine("  params: {");
        sb.AppendLine("    serviceName: serviceName");
        sb.AppendLine("    environment: environment");
        sb.AppendLine("    location: location");
        sb.AppendLine("    sku: appServicePlanSku");
        sb.AppendLine("    tags: commonTags");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        sb.AppendLine("// Web App");
        sb.AppendLine("module webApp './modules/web-app.bicep' = {");
        sb.AppendLine("  name: '${serviceName}-${environment}-webapp'");
        sb.AppendLine("  params: {");
        sb.AppendLine("    serviceName: serviceName");
        sb.AppendLine("    environment: environment");
        sb.AppendLine("    location: location");
        sb.AppendLine("    appServicePlanId: appServicePlan.outputs.planId");
        sb.AppendLine("    runtimeStack: runtimeStack");
        sb.AppendLine("    applicationInsightsConnectionString: enableApplicationInsights ? applicationInsights.outputs.connectionString : ''");
        sb.AppendLine("    applicationInsightsInstrumentationKey: enableApplicationInsights ? applicationInsights.outputs.instrumentationKey : ''");
        sb.AppendLine("    keyVaultName: keyVault.outputs.keyVaultName");
        sb.AppendLine("    alwaysOn: alwaysOn");
        sb.AppendLine("    httpsOnly: httpsOnly");
        sb.AppendLine("    enableVnetIntegration: enableVnetIntegration");
        sb.AppendLine(includeNetworking 
            ? "    vnetSubnetId: enableVnetIntegration ? network.outputs.appServiceSubnetId : ''" 
            : "    vnetSubnetId: ''");
        sb.AppendLine("    enablePrivateEndpoint: enablePrivateEndpoint");
        sb.AppendLine(includeNetworking 
            ? "    privateEndpointSubnetId: enablePrivateEndpoint ? network.outputs.privateEndpointSubnetId : ''" 
            : "    privateEndpointSubnetId: ''");
        sb.AppendLine("    ftpsState: ftpsState");
        sb.AppendLine("    minTlsVersion: minTlsVersion");
        sb.AppendLine("    enableManagedIdentity: enableManagedIdentity");
        sb.AppendLine("    enableClientCertificate: enableClientCertificate");
        sb.AppendLine("    clientCertMode: clientCertMode");
        sb.AppendLine("    enableDetailedErrorMessages: enableDetailedErrorMessages");
        sb.AppendLine("    enableHttpLogging: enableHttpLogging");
        sb.AppendLine("    ipSecurityRestrictions: ipSecurityRestrictions");
        sb.AppendLine("    tags: commonTags");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        sb.AppendLine("// Grant Web App access to Key Vault");
        sb.AppendLine("module keyVaultAccess 'br/public:avm/res/authorization/role-assignment:0.1.0' = {");
        sb.AppendLine("  name: '${serviceName}-${environment}-kv-access'");
        sb.AppendLine("  params: {");
        sb.AppendLine("    principalId: webApp.outputs.systemAssignedIdentityPrincipalId");
        sb.AppendLine("    roleDefinitionIdOrName: 'Key Vault Secrets User'");
        sb.AppendLine("    principalType: 'ServicePrincipal'");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        
        if (includeNetworking)
        {
            sb.AppendLine("// Private Endpoint (if enabled)");
            sb.AppendLine("module privateEndpoint './modules/private-endpoint.bicep' = if (enablePrivateEndpoint) {");
            sb.AppendLine("  name: '${serviceName}-${environment}-pe'");
            sb.AppendLine("  params: {");
            sb.AppendLine("    serviceName: serviceName");
            sb.AppendLine("    environment: environment");
            sb.AppendLine("    location: location");
            sb.AppendLine("    webAppId: webApp.outputs.webAppId");
            sb.AppendLine("    subnetId: network.outputs.privateEndpointSubnetId");
            sb.AppendLine("    virtualNetworkId: network.outputs.vnetId");
            sb.AppendLine("    tags: commonTags");
            sb.AppendLine("  }");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        sb.AppendLine("// Outputs");
        sb.AppendLine("output webAppUrl string = webApp.outputs.defaultHostName");
        sb.AppendLine("output webAppName string = webApp.outputs.name");
        sb.AppendLine("output appServicePlanId string = appServicePlan.outputs.planId");
        sb.AppendLine("output applicationInsightsId string = enableApplicationInsights ? applicationInsights.outputs.id : ''");
        sb.AppendLine("output keyVaultName string = keyVault.outputs.keyVaultName");
        sb.AppendLine("output systemAssignedIdentityPrincipalId string = webApp.outputs.systemAssignedIdentityPrincipalId");
        
        if (includeNetworking)
        {
            sb.AppendLine("output vnetId string = network.outputs.vnetId");
            sb.AppendLine("output vnetName string = network.outputs.vnetName");
        }
        
        return sb.ToString();
    }
    
    private string GenerateAppServicePlanBicep(TemplateGenerationRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// App Service Plan Configuration");
        sb.AppendLine("// Implements zone redundancy and auto-scaling");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine("param location string");
        sb.AppendLine("param sku string");
        sb.AppendLine("param tags object");
        sb.AppendLine();
        sb.AppendLine("var planName = '${serviceName}-${environment}-plan'");
        sb.AppendLine();
        sb.AppendLine("resource appServicePlan 'Microsoft.Web/serverfarms@2023-01-01' = {");
        sb.AppendLine("  name: planName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  sku: {");
        sb.AppendLine("    name: sku");
        sb.AppendLine("  }");
        sb.AppendLine("  kind: 'linux'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    reserved: true // Required for Linux");
        sb.AppendLine("    zoneRedundant: contains(['P1v3', 'P2v3', 'P3v3'], sku) // Zone redundancy for Premium v3");
        sb.AppendLine("    elasticScaleEnabled: contains(['P1v3', 'P2v3', 'P3v3'], sku)");
        sb.AppendLine("    maximumElasticWorkerCount: 10");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Auto-scale settings for production workloads");
        sb.AppendLine("resource autoScaleSettings 'Microsoft.Insights/autoscalesettings@2022-10-01' = if (contains(['P1v3', 'P2v3', 'P3v3', 'P1v2', 'P2v2', 'P3v2'], sku)) {");
        sb.AppendLine("  name: '${planName}-autoscale'");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    enabled: true");
        sb.AppendLine("    targetResourceUri: appServicePlan.id");
        sb.AppendLine("    profiles: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'Default autoscale condition'");
        sb.AppendLine("        capacity: {");
        sb.AppendLine("          minimum: '1'");
        sb.AppendLine("          maximum: '10'");
        sb.AppendLine("          default: '2'");
        sb.AppendLine("        }");
        sb.AppendLine("        rules: [");
        sb.AppendLine("          {");
        sb.AppendLine("            metricTrigger: {");
        sb.AppendLine("              metricName: 'CpuPercentage'");
        sb.AppendLine("              metricResourceUri: appServicePlan.id");
        sb.AppendLine("              timeGrain: 'PT1M'");
        sb.AppendLine("              statistic: 'Average'");
        sb.AppendLine("              timeWindow: 'PT5M'");
        sb.AppendLine("              timeAggregation: 'Average'");
        sb.AppendLine("              operator: 'GreaterThan'");
        sb.AppendLine("              threshold: 70");
        sb.AppendLine("            }");
        sb.AppendLine("            scaleAction: {");
        sb.AppendLine("              direction: 'Increase'");
        sb.AppendLine("              type: 'ChangeCount'");
        sb.AppendLine("              value: '1'");
        sb.AppendLine("              cooldown: 'PT5M'");
        sb.AppendLine("            }");
        sb.AppendLine("          }");
        sb.AppendLine("          {");
        sb.AppendLine("            metricTrigger: {");
        sb.AppendLine("              metricName: 'CpuPercentage'");
        sb.AppendLine("              metricResourceUri: appServicePlan.id");
        sb.AppendLine("              timeGrain: 'PT1M'");
        sb.AppendLine("              statistic: 'Average'");
        sb.AppendLine("              timeWindow: 'PT5M'");
        sb.AppendLine("              timeAggregation: 'Average'");
        sb.AppendLine("              operator: 'LessThan'");
        sb.AppendLine("              threshold: 30");
        sb.AppendLine("            }");
        sb.AppendLine("            scaleAction: {");
        sb.AppendLine("              direction: 'Decrease'");
        sb.AppendLine("              type: 'ChangeCount'");
        sb.AppendLine("              value: '1'");
        sb.AppendLine("              cooldown: 'PT5M'");
        sb.AppendLine("            }");
        sb.AppendLine("          }");
        sb.AppendLine("        ]");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("output planId string = appServicePlan.id");
        sb.AppendLine("output planName string = appServicePlan.name");
        
        return sb.ToString();
    }
    
    private string GenerateWebAppBicep(TemplateGenerationRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Web App Configuration");
        sb.AppendLine("// Implements managed identity, deployment slots, and security best practices");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine("param location string");
        sb.AppendLine("param appServicePlanId string");
        sb.AppendLine("param runtimeStack string");
        sb.AppendLine("param applicationInsightsConnectionString string");
        sb.AppendLine("param applicationInsightsInstrumentationKey string");
        sb.AppendLine("param keyVaultName string");
        sb.AppendLine("param alwaysOn bool");
        sb.AppendLine("param httpsOnly bool");
        sb.AppendLine("param enableVnetIntegration bool = false");
        sb.AppendLine("param vnetSubnetId string = ''");
        sb.AppendLine("param enablePrivateEndpoint bool = false");
        sb.AppendLine("param privateEndpointSubnetId string = ''");
        sb.AppendLine("param ftpsState string = 'FtpsOnly'");
        sb.AppendLine("param minTlsVersion string = '1.2'");
        sb.AppendLine("param enableManagedIdentity bool = true");
        sb.AppendLine("param enableClientCertificate bool = false");
        sb.AppendLine("param clientCertMode string = 'Optional'");
        sb.AppendLine("param enableDetailedErrorMessages bool = false");
        sb.AppendLine("param enableHttpLogging bool = false");
        sb.AppendLine("param ipSecurityRestrictions array = []");
        sb.AppendLine("param tags object");
        sb.AppendLine();
        sb.AppendLine("var appName = '${serviceName}-${environment}'");
        sb.AppendLine("var keyVaultUri = 'https://${keyVaultName}.vault.azure.net/'");
        sb.AppendLine();
        sb.AppendLine("resource webApp 'Microsoft.Web/sites@2023-01-01' = {");
        sb.AppendLine("  name: appName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  kind: 'app,linux'");
        sb.AppendLine("  identity: enableManagedIdentity ? {");
        sb.AppendLine("    type: 'SystemAssigned'");
        sb.AppendLine("  } : null");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    serverFarmId: appServicePlanId");
        sb.AppendLine("    httpsOnly: httpsOnly");
        sb.AppendLine("    clientAffinityEnabled: false");
        sb.AppendLine("    virtualNetworkSubnetId: enableVnetIntegration && !empty(vnetSubnetId) ? vnetSubnetId : null");
        sb.AppendLine("    clientCertEnabled: enableClientCertificate");
        sb.AppendLine("    clientCertMode: clientCertMode");
        sb.AppendLine("    ");
        sb.AppendLine("    siteConfig: {");
        sb.AppendLine("      linuxFxVersion: runtimeStack");
        sb.AppendLine("      alwaysOn: alwaysOn");
        sb.AppendLine("      ftpsState: ftpsState");
        sb.AppendLine("      minTlsVersion: minTlsVersion");
        sb.AppendLine("      http20Enabled: true");
        sb.AppendLine("      detailedErrorLoggingEnabled: enableDetailedErrorMessages");
        sb.AppendLine("      httpLoggingEnabled: enableHttpLogging");
        sb.AppendLine("      ");
        sb.AppendLine("      // Health check");
        sb.AppendLine("      healthCheckPath: '/health'");
        sb.AppendLine("      ");
        sb.AppendLine("      // Application settings");
        sb.AppendLine("      appSettings: [");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'");
        sb.AppendLine("          value: applicationInsightsConnectionString");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'ApplicationInsightsAgent_EXTENSION_VERSION'");
        sb.AppendLine("          value: '~3'");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'XDT_MicrosoftApplicationInsights_Mode'");
        sb.AppendLine("          value: 'Recommended'");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'APPINSIGHTS_INSTRUMENTATIONKEY'");
        sb.AppendLine("          value: applicationInsightsInstrumentationKey");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'KEY_VAULT_URI'");
        sb.AppendLine("          value: keyVaultUri");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'ASPNETCORE_ENVIRONMENT'");
        sb.AppendLine("          value: environment");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'NODE_ENV'");
        sb.AppendLine("          value: environment == 'prod' ? 'production' : 'development'");
        sb.AppendLine("        }");
        sb.AppendLine("      ]");
        sb.AppendLine("      ");
        sb.AppendLine("      // CORS settings");
        sb.AppendLine("      cors: {");
        sb.AppendLine("        allowedOrigins: [");
        sb.AppendLine("          '*' // Configure based on your requirements");
        sb.AppendLine("        ]");
        sb.AppendLine("        supportCredentials: false");
        sb.AppendLine("      }");
        sb.AppendLine("      ");
        sb.AppendLine("      // IP security restrictions");
        sb.AppendLine("      ipSecurityRestrictions: !empty(ipSecurityRestrictions) ? ipSecurityRestrictions : [");
        sb.AppendLine("        {");
        sb.AppendLine("          action: 'Allow'");
        sb.AppendLine("          priority: 100");
        sb.AppendLine("          name: 'Allow all'");
        sb.AppendLine("          ipAddress: 'Any'");
        sb.AppendLine("        }");
        sb.AppendLine("      ]");
        sb.AppendLine("      ");
        sb.AppendLine("      // SCM IP security restrictions");
        sb.AppendLine("      scmIpSecurityRestrictions: !empty(ipSecurityRestrictions) ? ipSecurityRestrictions : [");
        sb.AppendLine("        {");
        sb.AppendLine("          action: 'Allow'");
        sb.AppendLine("          priority: 100");
        sb.AppendLine("          name: 'Allow all'");
        sb.AppendLine("          ipAddress: 'Any'");
        sb.AppendLine("        }");
        sb.AppendLine("      ]");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Staging slot for blue-green deployments");
        sb.AppendLine("resource stagingSlot 'Microsoft.Web/sites/slots@2023-01-01' = {");
        sb.AppendLine("  parent: webApp");
        sb.AppendLine("  name: 'staging'");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  kind: 'app,linux'");
        sb.AppendLine("  identity: enableManagedIdentity ? {");
        sb.AppendLine("    type: 'SystemAssigned'");
        sb.AppendLine("  } : null");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    serverFarmId: appServicePlanId");
        sb.AppendLine("    httpsOnly: httpsOnly");
        sb.AppendLine("    clientCertEnabled: enableClientCertificate");
        sb.AppendLine("    clientCertMode: clientCertMode");
        sb.AppendLine("    ");
        sb.AppendLine("    siteConfig: {");
        sb.AppendLine("      linuxFxVersion: runtimeStack");
        sb.AppendLine("      alwaysOn: alwaysOn");
        sb.AppendLine("      ftpsState: ftpsState");
        sb.AppendLine("      minTlsVersion: minTlsVersion");
        sb.AppendLine("      detailedErrorLoggingEnabled: enableDetailedErrorMessages");
        sb.AppendLine("      httpLoggingEnabled: enableHttpLogging");
        sb.AppendLine("      ");
        sb.AppendLine("      appSettings: [");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'");
        sb.AppendLine("          value: applicationInsightsConnectionString");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'ASPNETCORE_ENVIRONMENT'");
        sb.AppendLine("          value: 'Staging'");
        sb.AppendLine("        }");
        sb.AppendLine("        {");
        sb.AppendLine("          name: 'KEY_VAULT_URI'");
        sb.AppendLine("          value: keyVaultUri");
        sb.AppendLine("        }");
        sb.AppendLine("      ]");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Diagnostic settings");
        sb.AppendLine("resource diagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {");
        sb.AppendLine("  name: '${appName}-diagnostics'");
        sb.AppendLine("  scope: webApp");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    logs: [");
        sb.AppendLine("      {");
        sb.AppendLine("        category: 'AppServiceHTTPLogs'");
        sb.AppendLine("        enabled: true");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        category: 'AppServiceConsoleLogs'");
        sb.AppendLine("        enabled: true");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        category: 'AppServiceAppLogs'");
        sb.AppendLine("        enabled: true");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        category: 'AppServicePlatformLogs'");
        sb.AppendLine("        enabled: true");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("    metrics: [");
        sb.AppendLine("      {");
        sb.AppendLine("        category: 'AllMetrics'");
        sb.AppendLine("        enabled: true");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("output name string = webApp.name");
        sb.AppendLine("output id string = webApp.id");
        sb.AppendLine("output webAppId string = webApp.id");
        sb.AppendLine("output defaultHostName string = webApp.properties.defaultHostName");
        sb.AppendLine("output systemAssignedIdentityPrincipalId string = enableManagedIdentity ? webApp.identity.principalId : ''");
        sb.AppendLine("output stagingSlotName string = stagingSlot.name");
        sb.AppendLine("output stagingSlotHostName string = stagingSlot.properties.defaultHostName");
        
        return sb.ToString();
    }
    
    private string GenerateApplicationInsightsBicep(TemplateGenerationRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Application Insights Configuration");
        sb.AppendLine("// Implements application performance monitoring");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine("param location string");
        sb.AppendLine("param tags object");
        sb.AppendLine();
        sb.AppendLine("var appInsightsName = '${serviceName}-${environment}-ai'");
        sb.AppendLine("var workspaceName = '${serviceName}-${environment}-logs'");
        sb.AppendLine();
        sb.AppendLine("// Log Analytics Workspace");
        sb.AppendLine("resource workspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {");
        sb.AppendLine("  name: workspaceName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    sku: {");
        sb.AppendLine("      name: 'PerGB2018'");
        sb.AppendLine("    }");
        sb.AppendLine("    retentionInDays: 30");
        sb.AppendLine("    features: {");
        sb.AppendLine("      enableLogAccessUsingOnlyResourcePermissions: true");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Application Insights");
        sb.AppendLine("resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {");
        sb.AppendLine("  name: appInsightsName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  kind: 'web'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    Application_Type: 'web'");
        sb.AppendLine("    WorkspaceResourceId: workspace.id");
        sb.AppendLine("    IngestionMode: 'LogAnalytics'");
        sb.AppendLine("    publicNetworkAccessForIngestion: 'Enabled'");
        sb.AppendLine("    publicNetworkAccessForQuery: 'Enabled'");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("output id string = applicationInsights.id");
        sb.AppendLine("output name string = applicationInsights.name");
        sb.AppendLine("output instrumentationKey string = applicationInsights.properties.InstrumentationKey");
        sb.AppendLine("output connectionString string = applicationInsights.properties.ConnectionString");
        sb.AppendLine("output workspaceId string = workspace.id");
        
        return sb.ToString();
    }
    
    private Dictionary<string, string> GetOrGenerateKeyVaultFiles(TemplateGenerationRequest request)
    {
        if (_cachedKeyVaultFiles == null)
        {
            var kvGenerator = new KeyVault.BicepKeyVaultModuleGenerator();
            _cachedKeyVaultFiles = kvGenerator.GenerateModule(request);
        }
        return _cachedKeyVaultFiles;
    }

    private string GenerateKeyVaultBicep(TemplateGenerationRequest request)
    {
        // Use cached Key Vault files to avoid regenerating multiple times
        return GetOrGenerateKeyVaultFiles(request)["infra/modules/keyvault/key-vault.bicep"];
    }
    
    private Dictionary<string, string> GetOrGenerateNetworkFiles(TemplateGenerationRequest request)
    {
        if (_cachedNetworkFiles == null)
        {
            var networkGenerator = new Infrastructure.BicepNetworkModuleGenerator();
            _cachedNetworkFiles = networkGenerator.GenerateModule(request);
        }
        return _cachedNetworkFiles;
    }
    
    private string GenerateParametersJson(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName.ToLowerInvariant();
        var application = request.Application ?? new ApplicationSpec();
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var observability = request.Observability ?? new ObservabilitySpec();
        var runtime = GetRuntimeStack(application.Language);
        
        // Determine intelligent defaults
        var isProduction = request.TemplateType?.ToLower().Contains("prod") ?? false;
        var enableAppInsights = observability.ApplicationInsights || observability.StructuredLogging;
        
        var sb = new StringBuilder();
        
        sb.AppendLine("{");
        sb.AppendLine("  \"$schema\": \"https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#\",");
        sb.AppendLine("  \"contentVersion\": \"1.0.0.0\",");
        sb.AppendLine("  \"parameters\": {");
        sb.AppendLine("    \"serviceName\": {");
        sb.AppendLine($"      \"value\": \"{serviceName}\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"environment\": {");
        sb.AppendLine("      \"value\": \"dev\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"location\": {");
        sb.AppendLine($"      \"value\": \"{infrastructure.Region}\"");
        sb.AppendLine("    },");
        sb.AppendLine();
        sb.AppendLine("    // === App Service Configuration ===");
        sb.AppendLine("    \"appServicePlanSku\": {");
        sb.AppendLine("      \"value\": \"P1v3\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"runtimeStack\": {");
        sb.AppendLine($"      \"value\": \"{runtime}\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"alwaysOn\": {");
        sb.AppendLine("      \"value\": true");
        sb.AppendLine("    },");
        sb.AppendLine();
        sb.AppendLine("    // === Security Parameters ===");
        sb.AppendLine("    \"httpsOnly\": {");
        sb.AppendLine("      \"value\": true");
        sb.AppendLine("    },");
        sb.AppendLine("    \"enableVnetIntegration\": {");
        sb.AppendLine($"      \"value\": {isProduction.ToString().ToLower()}");
        sb.AppendLine("    },");
        sb.AppendLine("    \"vnetSubnetId\": {");
        sb.AppendLine("      \"value\": \"\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"enablePrivateEndpoint\": {");
        sb.AppendLine($"      \"value\": {isProduction.ToString().ToLower()}");
        sb.AppendLine("    },");
        sb.AppendLine("    \"ftpsState\": {");
        sb.AppendLine("      \"value\": \"FtpsOnly\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"minTlsVersion\": {");
        sb.AppendLine("      \"value\": \"1.2\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"enableManagedIdentity\": {");
        sb.AppendLine("      \"value\": true");
        sb.AppendLine("    },");
        sb.AppendLine();
        sb.AppendLine("    // === Monitoring Parameters ===");
        sb.AppendLine("    \"enableApplicationInsights\": {");
        sb.AppendLine($"      \"value\": {enableAppInsights.ToString().ToLower()}");
        sb.AppendLine("    },");
        sb.AppendLine("    \"enableDetailedErrorMessages\": {");
        sb.AppendLine("      \"value\": false");
        sb.AppendLine("    },");
        sb.AppendLine("    \"enableHttpLogging\": {");
        sb.AppendLine($"      \"value\": {enableAppInsights.ToString().ToLower()}");
        sb.AppendLine("    },");
        sb.AppendLine();
        sb.AppendLine("    // === Advanced Security ===");
        sb.AppendLine("    \"enableClientCertificate\": {");
        sb.AppendLine("      \"value\": false");
        sb.AppendLine("    },");
        sb.AppendLine("    \"clientCertMode\": {");
        sb.AppendLine("      \"value\": \"Optional\"");
        sb.AppendLine("    },");
        sb.AppendLine("    \"ipSecurityRestrictions\": {");
        sb.AppendLine("      \"value\": []");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    private string GeneratePrivateEndpointBicep(TemplateGenerationRequest request)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Private Endpoint for App Service");
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        sb.AppendLine("param serviceName string");
        sb.AppendLine("param environment string");
        sb.AppendLine("param location string");
        sb.AppendLine("param webAppId string");
        sb.AppendLine("param subnetId string");
        sb.AppendLine("param virtualNetworkId string");
        sb.AppendLine("param tags object");
        sb.AppendLine();
        sb.AppendLine("var privateEndpointName = '${serviceName}-${environment}-pe'");
        sb.AppendLine("var privateDnsZoneName = 'privatelink.azurewebsites.net'");
        sb.AppendLine("var pvtEndpointDnsGroupName = '${privateEndpointName}/default'");
        sb.AppendLine();
        sb.AppendLine("resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = {");
        sb.AppendLine("  name: privateEndpointName");
        sb.AppendLine("  location: location");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    subnet: {");
        sb.AppendLine("      id: subnetId");
        sb.AppendLine("    }");
        sb.AppendLine("    privateLinkServiceConnections: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: '${serviceName}-${environment}-plsc'");
        sb.AppendLine("        properties: {");
        sb.AppendLine("          privateLinkServiceId: webAppId");
        sb.AppendLine("          groupIds: ['sites']");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' = {");
        sb.AppendLine("  name: privateDnsZoneName");
        sb.AppendLine("  location: 'global'");
        sb.AppendLine("  tags: tags");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {");
        sb.AppendLine("  parent: privateDnsZone");
        sb.AppendLine("  name: '${serviceName}-${environment}-dns-link'");
        sb.AppendLine("  location: 'global'");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    registrationEnabled: false");
        sb.AppendLine("    virtualNetwork: {");
        sb.AppendLine("      id: virtualNetworkId");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("resource pvtEndpointDnsGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = {");
        sb.AppendLine("  name: pvtEndpointDnsGroupName");
        sb.AppendLine("  properties: {");
        sb.AppendLine("    privateDnsZoneConfigs: [");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'config1'");
        sb.AppendLine("        properties: {");
        sb.AppendLine("          privateDnsZoneId: privateDnsZone.id");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine("    ]");
        sb.AppendLine("  }");
        sb.AppendLine("  dependsOn: [");
        sb.AppendLine("    privateEndpoint");
        sb.AppendLine("  ]");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("output privateEndpointId string = privateEndpoint.id");
        sb.AppendLine("output privateDnsZoneId string = privateDnsZone.id");
        
        return sb.ToString();
    }
    
    private string GenerateNetworkBicep(TemplateGenerationRequest request)
    {
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        var networkConfig = infrastructure.NetworkConfig ?? CreateDefaultNetworkConfig();
        
        // Check if using existing network or creating new
        if (networkConfig.Mode == NetworkMode.UseExisting)
        {
            return GenerateExistingNetworkReferencesBicep(networkConfig);
        }
        
        // Delegate to specialized BicepNetworkModuleGenerator for consistency and use cached results
        return GetOrGenerateNetworkFiles(request)["modules/network/main.bicep"];
    }
    
    private string GenerateExistingNetworkReferencesBicep(NetworkingConfiguration networkConfig)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("// Reference Existing Network Resources");
        sb.AppendLine("// Generated by Platform Engineering Copilot");
        sb.AppendLine();
        sb.AppendLine("targetScope = 'resourceGroup'");
        sb.AppendLine();
        
        // Parameters
        sb.AppendLine("@description('Service name')");
        sb.AppendLine("param serviceName string");
        sb.AppendLine();
        sb.AppendLine("@description('Existing VNet name')");
        sb.AppendLine($"param vnetName string = '{networkConfig.ExistingVNetName}'");
        sb.AppendLine();
        sb.AppendLine("@description('Existing VNet resource group')");
        sb.AppendLine($"param vnetResourceGroup string = '{networkConfig.ExistingVNetResourceGroup}'");
        sb.AppendLine();
        sb.AppendLine("@description('Location for new resources')");
        sb.AppendLine("param location string = resourceGroup().location");
        sb.AppendLine();
        sb.AppendLine("@description('Tags to apply to resources')");
        sb.AppendLine("param tags object = {}");
        sb.AppendLine();
        
        // Reference existing VNet
        sb.AppendLine("// Reference existing Virtual Network");
        sb.AppendLine($"resource vnet 'Microsoft.Network/virtualNetworks@2023-05-01' existing = {{");
        sb.AppendLine($"  name: vnetName");
        sb.AppendLine($"  scope: resourceGroup(vnetResourceGroup)");
        sb.AppendLine("}");
        sb.AppendLine();
        
        // Find subnets
        var appSubnet = networkConfig.ExistingSubnets.FirstOrDefault(s => 
            s.Purpose == SubnetPurpose.Application || s.Name.Contains("appservice"));
        var peSubnet = networkConfig.ExistingSubnets.FirstOrDefault(s => 
            s.Purpose == SubnetPurpose.PrivateEndpoints || s.Name.Contains("private"));
        
        if (appSubnet != null)
        {
            sb.AppendLine("// Reference existing App Service subnet");
            sb.AppendLine($"resource appServiceSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {{");
            sb.AppendLine($"  parent: vnet");
            sb.AppendLine($"  name: '{appSubnet.Name}'");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        if (peSubnet != null && networkConfig.EnablePrivateEndpoint)
        {
            sb.AppendLine("// Reference existing Private Endpoint subnet");
            sb.AppendLine($"resource privateEndpointSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {{");
            sb.AppendLine($"  parent: vnet");
            sb.AppendLine($"  name: '{peSubnet.Name}'");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Optionally create NSG if needed
        if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
        {
            sb.AppendLine("// Network Security Group");
            sb.AppendLine($"resource nsg 'Microsoft.Network/networkSecurityGroups@2023-05-01' = {{");
            sb.AppendLine($"  name: 'nsg-${{serviceName}}'");
            sb.AppendLine($"  location: location");
            sb.AppendLine($"  tags: tags");
            sb.AppendLine($"  properties: {{");
            sb.AppendLine($"    securityRules: [");
            
            foreach (var rule in networkConfig.NsgRules)
            {
                sb.AppendLine($"      {{");
                sb.AppendLine($"        name: '{rule.Name}'");
                sb.AppendLine($"        properties: {{");
                sb.AppendLine($"          priority: {rule.Priority}");
                sb.AppendLine($"          direction: '{rule.Direction}'");
                sb.AppendLine($"          access: '{rule.Access}'");
                sb.AppendLine($"          protocol: '{rule.Protocol}'");
                sb.AppendLine($"          sourcePortRange: '{rule.SourcePortRange}'");
                sb.AppendLine($"          destinationPortRange: '{rule.DestinationPortRange}'");
                sb.AppendLine($"          sourceAddressPrefix: '{rule.SourceAddressPrefix}'");
                sb.AppendLine($"          destinationAddressPrefix: '{rule.DestinationAddressPrefix}'");
                sb.AppendLine($"          description: '{rule.Description}'");
                sb.AppendLine($"        }}");
                sb.AppendLine($"      }}");
            }
            
            sb.AppendLine($"    ]");
            sb.AppendLine($"  }}");
            sb.AppendLine("}");
            sb.AppendLine();
        }
        
        // Outputs
        sb.AppendLine("// Outputs");
        sb.AppendLine("output vnetId string = vnet.id");
        
        if (appSubnet != null)
        {
            sb.AppendLine("output appServiceSubnetId string = appServiceSubnet.id");
        }
        
        if (peSubnet != null)
        {
            sb.AppendLine("output privateEndpointSubnetId string = privateEndpointSubnet.id");
        }
        
        if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
        {
            sb.AppendLine("output nsgId string = nsg.id");
        }
        
        return sb.ToString();
    }
    
    private NetworkingConfiguration CreateDefaultNetworkConfig()
    {
        return new NetworkingConfiguration
        {
            Mode = NetworkMode.CreateNew,
            VNetName = "vnet-${serviceName}",
            VNetAddressSpace = "10.0.0.0/16",
            Subnets = new List<SubnetConfiguration>
            {
                new SubnetConfiguration
                {
                    Name = "appservice-subnet",
                    AddressPrefix = "10.0.1.0/24",
                    Delegation = "Microsoft.Web/serverFarms",
                    Purpose = SubnetPurpose.Application
                },
                new SubnetConfiguration
                {
                    Name = "privateendpoints-subnet",
                    AddressPrefix = "10.0.2.0/24",
                    Purpose = SubnetPurpose.PrivateEndpoints
                }
            },
            EnableNetworkSecurityGroup = true,
            EnablePrivateEndpoint = true,
            EnableServiceEndpoints = false,
            EnableDDoSProtection = false,
            EnablePrivateDns = true,
            PrivateDnsZoneName = "privatelink.azurewebsites.net",
            PrivateEndpointSubnetName = "privateendpoints-subnet"
        };
    }
    
    private string GetRuntimeStack(ProgrammingLanguage language)
    {
        return language switch
        {
            ProgrammingLanguage.NodeJS => "NODE|20-lts",
            ProgrammingLanguage.Python => "PYTHON|3.11",
            ProgrammingLanguage.DotNet => "DOTNETCORE|8.0",
            ProgrammingLanguage.Java => "JAVA|17-java17",
            ProgrammingLanguage.PHP => "PHP|8.2",
            ProgrammingLanguage.Ruby => "RUBY|3.2",
            _ => "NODE|20-lts"
        };
    }
}
