using System.Text;
using Platform.Engineering.Copilot.Core.Interfaces;
using Platform.Engineering.Copilot.Core.Interfaces.TemplateGeneration;
using Platform.Engineering.Copilot.Core.Models;
using Platform.Engineering.Copilot.Core.Models.TemplateGeneration;

namespace Platform.Engineering.Copilot.Core.Services.Generators.AppService;

/// <summary>
/// Bicep module generator for Azure App Service infrastructure
/// Implements IResourceModuleGenerator for composition-based generation
/// Cross-cutting concerns (PE, diagnostics, RBAC) are handled by reusable generators
/// </summary>
public class BicepAppServiceResourceModuleGenerator : IResourceModuleGenerator
{
    public InfrastructureFormat Format => InfrastructureFormat.Bicep;
    public ComputePlatform Platform => ComputePlatform.AppService;
    public CloudProvider Provider => CloudProvider.Azure;
    
    /// <summary>
    /// Resource types this generator handles
    /// </summary>
    public string[] SupportedResourceTypes => new[] 
    { 
        "app-service", 
        "appservice", 
        "web-app", 
        "webapp",
        "azure-app-service"
    };
    
    /// <summary>
    /// Cross-cutting capabilities supported by App Service
    /// </summary>
    public CrossCuttingType[] SupportedCrossCutting => new[]
    {
        CrossCuttingType.PrivateEndpoint,
        CrossCuttingType.DiagnosticSettings,
        CrossCuttingType.RBACAssignment,
        CrossCuttingType.ManagedIdentity
    };
    
    /// <summary>
    /// Azure resource type for App Service
    /// </summary>
    public string AzureResourceType => "Microsoft.Web/sites";

    /// <summary>
    /// Generate ONLY the core App Service resource - cross-cutting modules are composed by orchestrator
    /// </summary>
    public ResourceModuleResult GenerateCoreResource(TemplateGenerationRequest request)
    {
        var files = new Dictionary<string, string>();
        var serviceName = request.ServiceName ?? "webapp";
        var application = request.Application ?? new ApplicationSpec();

        // Generate core App Service module files
        files["app-service.bicep"] = GenerateAppServiceBicep(request);
        files["app-service-plan.bicep"] = GenerateAppServicePlanBicep(request);
        files["main.bicep"] = GenerateCoreMainBicep(request);
        files["README.md"] = GenerateReadme(request);

        return new ResourceModuleResult
        {
            Files = files,
            ResourceReference = "appService", // Module name for cross-cutting references
            ResourceType = "Microsoft.Web/sites",
            OutputNames = new List<string>
            {
                "appServiceId",
                "appServiceName",
                "appServiceHostname",
                "appServicePlanId",
                "principalId",
                "resourceId",
                "resourceName"
            },
            SupportedCrossCutting = new List<CrossCuttingType>
            {
                CrossCuttingType.PrivateEndpoint,
                CrossCuttingType.DiagnosticSettings,
                CrossCuttingType.RBACAssignment,
                CrossCuttingType.ManagedIdentity
            }
        };
    }

    /// <summary>
    /// Legacy GenerateModule - delegates to legacy generator for full template generation
    /// </summary>
    public Dictionary<string, string> GenerateModule(TemplateGenerationRequest request)
    {
        var result = GenerateCoreResource(request);
        return result.Files;
    }
    
    /// <summary>
    /// Check if this generator can handle the request
    /// </summary>
    public bool CanGenerate(TemplateGenerationRequest request)
    {
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        return infrastructure.Format == InfrastructureFormat.Bicep &&
               infrastructure.Provider == CloudProvider.Azure &&
               infrastructure.ComputePlatform == ComputePlatform.AppService;
    }

    /// <summary>
    /// Generate core App Service Bicep module (without cross-cutting concerns)
    /// </summary>
    private string GenerateAppServiceBicep(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "webapp";
        var application = request.Application ?? new ApplicationSpec();
        var runtime = GetRuntimeStack(application.Language);

        return $@"// Azure App Service - Core Resource Module
// FedRAMP Controls: SC-8 (TLS), AC-3 (Access Control), AU-2 (Audit)
// Generated by Platform Engineering Copilot

@description('Name of the web app')
param webAppName string

@description('Resource ID of the App Service Plan')
param appServicePlanId string

@description('Azure region')
param location string = resourceGroup().location

@description('Runtime stack')
param runtimeStack string = '{runtime}'

@description('Enable managed identity')
param enableManagedIdentity bool = true

@description('HTTPS Only')
param httpsOnly bool = true

@description('Always On')
param alwaysOn bool = true

@description('Minimum TLS Version')
param minTlsVersion string = '1.2'

@description('Tags')
param tags object = {{}}

// Web App Resource
resource webApp 'Microsoft.Web/sites@2023-01-01' = {{
  name: webAppName
  location: location
  tags: tags
  identity: enableManagedIdentity ? {{
    type: 'SystemAssigned'
  }} : null
  properties: {{
    serverFarmId: appServicePlanId
    httpsOnly: httpsOnly
    siteConfig: {{
      linuxFxVersion: runtimeStack
      alwaysOn: alwaysOn
      minTlsVersion: minTlsVersion
      ftpsState: 'Disabled'
      http20Enabled: true
      // FedRAMP SC-8: Require TLS
      httpLoggingEnabled: true
      detailedErrorLoggingEnabled: true
      requestTracingEnabled: true
    }}
    // FedRAMP SC-7: Network isolation
    publicNetworkAccess: 'Disabled'
  }}
}}

// Outputs for cross-cutting module composition
@description('Web App Resource ID')
output appServiceId string = webApp.id

@description('Web App Name')
output appServiceName string = webApp.name

@description('Web App Default Hostname')
output appServiceHostname string = webApp.properties.defaultHostName

@description('Principal ID for RBAC assignments')
output principalId string = enableManagedIdentity ? webApp.identity.principalId : ''

@description('Resource ID (alias)')
output resourceId string = webApp.id

@description('Resource Name (alias)')
output resourceName string = webApp.name
";
    }

    /// <summary>
    /// Generate App Service Plan Bicep module
    /// </summary>
    private string GenerateAppServicePlanBicep(TemplateGenerationRequest request)
    {
        return @"// Azure App Service Plan - Core Resource Module
// FedRAMP Controls: SC-5 (DoS Protection via scaling)
// Generated by Platform Engineering Copilot

@description('Name of the App Service Plan')
param planName string

@description('Azure region')
param location string = resourceGroup().location

@description('SKU name')
@allowed([
  'B1'
  'B2'
  'B3'
  'S1'
  'S2'
  'S3'
  'P1v2'
  'P2v2'
  'P3v2'
  'P1v3'
  'P2v3'
  'P3v3'
])
param skuName string = 'P1v3'

@description('Is Linux')
param isLinux bool = true

@description('Tags')
param tags object = {}

// App Service Plan Resource
resource appServicePlan 'Microsoft.Web/serverfarms@2023-01-01' = {
  name: planName
  location: location
  tags: tags
  kind: isLinux ? 'linux' : 'app'
  sku: {
    name: skuName
  }
  properties: {
    reserved: isLinux
    // FedRAMP SC-5: Zone redundancy for availability
    zoneRedundant: skuName startsWith 'P' ? true : false
  }
}

// Outputs
@description('App Service Plan ID')
output appServicePlanId string = appServicePlan.id

@description('App Service Plan Name')
output appServicePlanName string = appServicePlan.name
";
    }

    /// <summary>
    /// Generate core main.bicep that composes the App Service modules
    /// </summary>
    private string GenerateCoreMainBicep(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "webapp";

        return $@"// App Service - Main Module (Core Resources Only)
// Cross-cutting concerns are composed by CompositeInfrastructureGenerator
// Generated by Platform Engineering Copilot

targetScope = 'resourceGroup'

@description('Service name')
param serviceName string = '{serviceName}'

@description('Environment')
param environment string = 'dev'

@description('Azure region')
param location string = resourceGroup().location

@description('App Service Plan SKU')
param appServicePlanSku string = 'P1v3'

@description('Enable managed identity')
param enableManagedIdentity bool = true

// Variables
var resourcePrefix = '${{serviceName}}-${{environment}}'
var planName = '${{resourcePrefix}}-plan'
var webAppName = '${{resourcePrefix}}-app'

var tags = {{
  service: serviceName
  environment: environment
  managedBy: 'platform-engineering-copilot'
}}

// App Service Plan
module appServicePlan 'app-service-plan.bicep' = {{
  name: 'deploy-app-service-plan'
  params: {{
    planName: planName
    location: location
    skuName: appServicePlanSku
    tags: tags
  }}
}}

// Web App
module appService 'app-service.bicep' = {{
  name: 'deploy-app-service'
  params: {{
    webAppName: webAppName
    appServicePlanId: appServicePlan.outputs.appServicePlanId
    location: location
    enableManagedIdentity: enableManagedIdentity
    tags: tags
  }}
}}

// Outputs for cross-cutting module composition
output appServiceId string = appService.outputs.appServiceId
output appServiceName string = appService.outputs.appServiceName
output appServiceHostname string = appService.outputs.appServiceHostname
output appServicePlanId string = appServicePlan.outputs.appServicePlanId
output principalId string = appService.outputs.principalId
output resourceId string = appService.outputs.resourceId
output resourceName string = appService.outputs.resourceName
";
    }

    /// <summary>
    /// Generate README for the module
    /// </summary>
    private string GenerateReadme(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "webapp";

        return $@"# Azure App Service Bicep Module

## Overview
This module deploys an Azure App Service with FedRAMP-compliant security controls.

## Resources Created
- App Service Plan (Microsoft.Web/serverfarms)
- Web App (Microsoft.Web/sites)

## FedRAMP Controls Implemented
- **SC-8**: TLS 1.2+ enforcement, HTTPS only
- **AC-3**: Managed Identity for authentication
- **AU-2**: Logging enabled (HTTP, detailed errors, request tracing)
- **SC-7**: Public network access disabled (requires Private Endpoint)
- **SC-5**: Zone redundancy for Premium SKUs

## Cross-Cutting Concerns
This module exposes outputs for composition with:
- Private Endpoint (network isolation)
- Diagnostic Settings (Log Analytics integration)
- RBAC Assignments (access control)

## Usage
```bicep
module appService 'main.bicep' = {{
  name: 'deploy-{serviceName}'
  params: {{
    serviceName: '{serviceName}'
    environment: 'dev'
    appServicePlanSku: 'P1v3'
    enableManagedIdentity: true
  }}
}}
```

## Outputs
| Name | Description |
|------|-------------|
| appServiceId | Resource ID of the Web App |
| appServiceName | Name of the Web App |
| appServiceHostname | Default hostname |
| appServicePlanId | Resource ID of the App Service Plan |
| principalId | Managed Identity principal ID |
";
    }

    /// <summary>
    /// Get runtime stack based on language
    /// </summary>
    private string GetRuntimeStack(ProgrammingLanguage language)
    {
        return language switch
        {
            ProgrammingLanguage.DotNet => "DOTNETCORE|8.0",
            ProgrammingLanguage.NodeJS => "NODE|20-lts",
            ProgrammingLanguage.Python => "PYTHON|3.11",
            ProgrammingLanguage.Java => "JAVA|17-java17",
            ProgrammingLanguage.Go => "GO|1.21",
            ProgrammingLanguage.PHP => "PHP|8.2",
            ProgrammingLanguage.Ruby => "RUBY|3.2",
            ProgrammingLanguage.Rust => "DOTNETCORE|8.0", // Rust via custom container
            _ => "DOTNETCORE|8.0"
        };
    }
}
