using System.Text;
using Platform.Engineering.Copilot.Core.Interfaces;
using Platform.Engineering.Copilot.Core.Interfaces.TemplateGeneration;
using Platform.Engineering.Copilot.Core.Models;
using Platform.Engineering.Copilot.Core.Models.TemplateGeneration;

namespace Platform.Engineering.Copilot.Core.Services.Generators.AppService;

/// <summary>
/// Terraform module generator for Azure App Service infrastructure
/// Implements IResourceModuleGenerator for composition-based generation
/// Cross-cutting concerns (PE, diagnostics, RBAC) are handled by reusable generators
/// </summary>
public class TerraformAppServiceResourceModuleGenerator : IResourceModuleGenerator
{
    public InfrastructureFormat Format => InfrastructureFormat.Terraform;
    public ComputePlatform Platform => ComputePlatform.AppService;
    public CloudProvider Provider => CloudProvider.Azure;

    /// <summary>
    /// Resource types this generator handles
    /// </summary>
    public string[] SupportedResourceTypes => new[]
    {
        "app-service",
        "appservice",
        "web-app",
        "webapp",
        "azure-app-service"
    };

    /// <summary>
    /// Cross-cutting capabilities supported by App Service
    /// </summary>
    public CrossCuttingType[] SupportedCrossCutting => new[]
    {
        CrossCuttingType.PrivateEndpoint,
        CrossCuttingType.DiagnosticSettings,
        CrossCuttingType.RBACAssignment,
        CrossCuttingType.ManagedIdentity
    };

    /// <summary>
    /// Azure resource type for App Service
    /// </summary>
    public string AzureResourceType => "Microsoft.Web/sites";

    /// <summary>
    /// Generate ONLY the core App Service resource - cross-cutting modules are composed by orchestrator
    /// </summary>
    public ResourceModuleResult GenerateCoreResource(TemplateGenerationRequest request)
    {
        var files = new Dictionary<string, string>();
        var serviceName = request.ServiceName ?? "webapp";

        // Generate core App Service module files
        files["modules/appservice/main.tf"] = GenerateCoreMainTf(request);
        files["modules/appservice/variables.tf"] = GenerateCoreVariablesTf(request);
        files["modules/appservice/outputs.tf"] = GenerateCoreOutputsTf(request);
        files["modules/webapp/main.tf"] = GenerateWebAppMainTf(request);
        files["modules/webapp/variables.tf"] = GenerateWebAppVariablesTf(request);
        files["modules/webapp/outputs.tf"] = GenerateWebAppOutputsTf(request);
        files["main.tf"] = GenerateRootMainTf(request);
        files["README.md"] = GenerateReadme(request);

        return new ResourceModuleResult
        {
            Files = files,
            ResourceReference = "module.webapp.azurerm_linux_web_app.app", // Terraform resource reference
            ResourceType = "Microsoft.Web/sites",
            OutputNames = new List<string>
            {
                "app_service_id",
                "app_service_name",
                "app_service_hostname",
                "app_service_plan_id",
                "principal_id"
            },
            SupportedCrossCutting = new List<CrossCuttingType>
            {
                CrossCuttingType.PrivateEndpoint,
                CrossCuttingType.DiagnosticSettings,
                CrossCuttingType.RBACAssignment,
                CrossCuttingType.ManagedIdentity
            }
        };
    }

    /// <summary>
    /// GenerateModule - generates the full module including core and cross-cutting concerns
    /// </summary>
    public Dictionary<string, string> GenerateModule(TemplateGenerationRequest request)
    {
        var result = GenerateCoreResource(request);
        return result.Files;
    }

    /// <summary>
    /// Check if this generator can handle the request
    /// </summary>
    public bool CanGenerate(TemplateGenerationRequest request)
    {
        var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
        return infrastructure.Format == InfrastructureFormat.Terraform &&
               infrastructure.Provider == CloudProvider.Azure &&
               infrastructure.ComputePlatform == ComputePlatform.AppService;
    }

    /// <summary>
    /// Generate core App Service Plan main.tf
    /// </summary>
    private string GenerateCoreMainTf(TemplateGenerationRequest request)
    {
        return @"# Azure App Service Plan - Core Resource Module
# FedRAMP Controls: SC-5 (DoS Protection via scaling)
# Generated by Platform Engineering Copilot

resource ""azurerm_service_plan"" ""plan"" {
  name                = var.plan_name
  resource_group_name = var.resource_group_name
  location            = var.location
  os_type             = var.os_type
  sku_name            = var.sku_name

  # FedRAMP SC-5: Zone redundancy for availability (Premium SKUs)
  zone_balancing_enabled = var.zone_redundant

  tags = var.tags
}
";
    }

    /// <summary>
    /// Generate core App Service Plan variables.tf
    /// </summary>
    private string GenerateCoreVariablesTf(TemplateGenerationRequest request)
    {
        return @"# App Service Plan Variables

variable ""plan_name"" {
  description = ""Name of the App Service Plan""
  type        = string
}

variable ""resource_group_name"" {
  description = ""Name of the resource group""
  type        = string
}

variable ""location"" {
  description = ""Azure region""
  type        = string
}

variable ""os_type"" {
  description = ""OS type (Linux or Windows)""
  type        = string
  default     = ""Linux""
}

variable ""sku_name"" {
  description = ""SKU name for the App Service Plan""
  type        = string
  default     = ""P1v3""

  validation {
    condition     = contains([""B1"", ""B2"", ""B3"", ""S1"", ""S2"", ""S3"", ""P1v2"", ""P2v2"", ""P3v2"", ""P1v3"", ""P2v3"", ""P3v3""], var.sku_name)
    error_message = ""SKU must be a valid App Service Plan SKU.""
  }
}

variable ""zone_redundant"" {
  description = ""Enable zone redundancy""
  type        = bool
  default     = true
}

variable ""tags"" {
  description = ""Tags to apply to resources""
  type        = map(string)
  default     = {}
}
";
    }

    /// <summary>
    /// Generate core App Service Plan outputs.tf
    /// </summary>
    private string GenerateCoreOutputsTf(TemplateGenerationRequest request)
    {
        return @"# App Service Plan Outputs

output ""app_service_plan_id"" {
  description = ""ID of the App Service Plan""
  value       = azurerm_service_plan.plan.id
}

output ""app_service_plan_name"" {
  description = ""Name of the App Service Plan""
  value       = azurerm_service_plan.plan.name
}
";
    }

    /// <summary>
    /// Generate Web App main.tf
    /// </summary>
    private string GenerateWebAppMainTf(TemplateGenerationRequest request)
    {
        var application = request.Application ?? new ApplicationSpec();
        var runtime = GetTerraformRuntime(application.Language);

        return $@"# Azure Web App - Core Resource Module
# FedRAMP Controls: SC-8 (TLS), AC-3 (Access Control), AU-2 (Audit), SC-7 (Network Isolation)
# Generated by Platform Engineering Copilot

resource ""azurerm_linux_web_app"" ""app"" {{
  name                = var.web_app_name
  resource_group_name = var.resource_group_name
  location            = var.location
  service_plan_id     = var.service_plan_id

  # FedRAMP SC-8: HTTPS enforcement
  https_only = true

  # FedRAMP AC-3: Managed Identity
  identity {{
    type = var.enable_managed_identity ? ""SystemAssigned"" : ""None""
  }}

  site_config {{
    # FedRAMP SC-8: TLS 1.2 minimum
    minimum_tls_version = ""1.2""

    # Runtime configuration
    application_stack {{
      {runtime}
    }}

    # FedRAMP AU-2: Logging
    http2_enabled = true

    # FedRAMP SC-8: Disable insecure protocols
    ftps_state = ""Disabled""

    # Always On for production
    always_on = var.always_on
  }}

  # FedRAMP SC-7: Network isolation
  public_network_access_enabled = var.public_network_access_enabled

  tags = var.tags
}}
";
    }

    /// <summary>
    /// Generate Web App variables.tf
    /// </summary>
    private string GenerateWebAppVariablesTf(TemplateGenerationRequest request)
    {
        return @"# Web App Variables

variable ""web_app_name"" {
  description = ""Name of the Web App""
  type        = string
}

variable ""resource_group_name"" {
  description = ""Name of the resource group""
  type        = string
}

variable ""location"" {
  description = ""Azure region""
  type        = string
}

variable ""service_plan_id"" {
  description = ""ID of the App Service Plan""
  type        = string
}

variable ""enable_managed_identity"" {
  description = ""Enable system-assigned managed identity""
  type        = bool
  default     = true
}

variable ""always_on"" {
  description = ""Enable Always On""
  type        = bool
  default     = true
}

variable ""public_network_access_enabled"" {
  description = ""Allow public network access (disable for Private Endpoint only)""
  type        = bool
  default     = false
}

variable ""tags"" {
  description = ""Tags to apply to resources""
  type        = map(string)
  default     = {}
}
";
    }

    /// <summary>
    /// Generate Web App outputs.tf
    /// </summary>
    private string GenerateWebAppOutputsTf(TemplateGenerationRequest request)
    {
        return @"# Web App Outputs

output ""app_service_id"" {
  description = ""ID of the Web App""
  value       = azurerm_linux_web_app.app.id
}

output ""app_service_name"" {
  description = ""Name of the Web App""
  value       = azurerm_linux_web_app.app.name
}

output ""app_service_hostname"" {
  description = ""Default hostname of the Web App""
  value       = azurerm_linux_web_app.app.default_hostname
}

output ""principal_id"" {
  description = ""Principal ID of the managed identity""
  value       = try(azurerm_linux_web_app.app.identity[0].principal_id, """")
}

output ""resource_id"" {
  description = ""Resource ID (alias for app_service_id)""
  value       = azurerm_linux_web_app.app.id
}
";
    }

    /// <summary>
    /// Generate root main.tf that composes the modules
    /// </summary>
    private string GenerateRootMainTf(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "webapp";

        return $@"# App Service - Main Terraform Configuration (Core Resources Only)
# Cross-cutting concerns are composed by CompositeInfrastructureGenerator
# Generated by Platform Engineering Copilot

terraform {{
  required_version = "">= 1.5.0""

  required_providers {{
    azurerm = {{
      source  = ""hashicorp/azurerm""
      version = ""~> 3.0""
    }}
  }}
}}

provider ""azurerm"" {{
  features {{}}
}}

# Variables
variable ""service_name"" {{
  description = ""Name of the service""
  type        = string
  default     = ""{serviceName}""
}}

variable ""environment"" {{
  description = ""Environment (dev, staging, prod)""
  type        = string
  default     = ""dev""
}}

variable ""location"" {{
  description = ""Azure region""
  type        = string
  default     = ""eastus""
}}

variable ""resource_group_name"" {{
  description = ""Name of the resource group""
  type        = string
}}

variable ""app_service_plan_sku"" {{
  description = ""SKU for the App Service Plan""
  type        = string
  default     = ""P1v3""
}}

# Local variables
locals {{
  resource_prefix = ""${{var.service_name}}-${{var.environment}}""
  plan_name       = ""${{local.resource_prefix}}-plan""
  web_app_name    = ""${{local.resource_prefix}}-app""

  tags = {{
    service     = var.service_name
    environment = var.environment
    managed_by  = ""platform-engineering-copilot""
  }}
}}

# App Service Plan
module ""appservice"" {{
  source = ""./modules/appservice""

  plan_name           = local.plan_name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku_name            = var.app_service_plan_sku
  tags                = local.tags
}}

# Web App
module ""webapp"" {{
  source = ""./modules/webapp""

  web_app_name        = local.web_app_name
  resource_group_name = var.resource_group_name
  location            = var.location
  service_plan_id     = module.appservice.app_service_plan_id
  tags                = local.tags

  depends_on = [module.appservice]
}}

# Outputs for cross-cutting module composition
output ""app_service_id"" {{
  value = module.webapp.app_service_id
}}

output ""app_service_name"" {{
  value = module.webapp.app_service_name
}}

output ""app_service_hostname"" {{
  value = module.webapp.app_service_hostname
}}

output ""app_service_plan_id"" {{
  value = module.appservice.app_service_plan_id
}}

output ""principal_id"" {{
  value = module.webapp.principal_id
}}
";
    }

    /// <summary>
    /// Generate README for the module
    /// </summary>
    private string GenerateReadme(TemplateGenerationRequest request)
    {
        var serviceName = request.ServiceName ?? "webapp";

        return $@"# Azure App Service Terraform Module

## Overview
This module deploys an Azure App Service with FedRAMP-compliant security controls.

## Resources Created
- App Service Plan (azurerm_service_plan)
- Linux Web App (azurerm_linux_web_app)

## FedRAMP Controls Implemented
- **SC-8**: TLS 1.2+ enforcement, HTTPS only, FTPS disabled
- **AC-3**: Managed Identity for authentication
- **AU-2**: HTTP/2 enabled, logging configured
- **SC-7**: Public network access disabled (requires Private Endpoint)
- **SC-5**: Zone redundancy for Premium SKUs

## Cross-Cutting Concerns
This module exposes outputs for composition with:
- Private Endpoint (network isolation)
- Diagnostic Settings (Log Analytics integration)
- RBAC Assignments (access control)

## Usage
```hcl
module ""appservice"" {{
  source = ""./modules/appservice""

  service_name        = ""{serviceName}""
  environment         = ""dev""
  resource_group_name = azurerm_resource_group.main.name
  location            = ""eastus""
  app_service_plan_sku = ""P1v3""
}}
```

## Outputs
| Name | Description |
|------|-------------|
| app_service_id | Resource ID of the Web App |
| app_service_name | Name of the Web App |
| app_service_hostname | Default hostname |
| app_service_plan_id | Resource ID of the App Service Plan |
| principal_id | Managed Identity principal ID |
";
    }

    /// <summary>
    /// Get Terraform runtime configuration based on language
    /// </summary>
    private string GetTerraformRuntime(ProgrammingLanguage language)
    {
        return language switch
        {
            ProgrammingLanguage.DotNet => "dotnet_version = \"8.0\"",
            ProgrammingLanguage.NodeJS => "node_version = \"20-lts\"",
            ProgrammingLanguage.Python => "python_version = \"3.11\"",
            ProgrammingLanguage.Java => "java_version = \"17\"",
            ProgrammingLanguage.Go => "go_version = \"1.21\"",
            ProgrammingLanguage.PHP => "php_version = \"8.2\"",
            ProgrammingLanguage.Ruby => "ruby_version = \"3.2\"",
            _ => "dotnet_version = \"8.0\""
        };
    }
}
