using System.Text;
using System.Linq;
using System.Collections.Generic;
using Platform.Engineering.Copilot.Core.Models;

namespace Platform.Engineering.Copilot.Core.Services.Generators.Kubernetes;

/// <summary>
/// Generates Azure Kubernetes Service (AKS) Bicep module files
/// Implements Azure best practices including Workload Identity, Azure CNI, and Azure Monitor
/// </summary>
public class BicepAKSModuleGenerator
{
  /// <summary>
  /// Generate complete AKS module with cluster, networking, identity, and monitoring
  /// </summary>
  public Dictionary<string, string> GenerateAKSModule(TemplateGenerationRequest request)
  {
    var files = new Dictionary<string, string>();
    var serviceName = request.ServiceName.ToLowerInvariant();
    var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
    var deployment = request.Deployment ?? new DeploymentSpec();
    var security = request.Security ?? new SecuritySpec();
    var observability = request.Observability ?? new ObservabilitySpec();

    var modulePath = "modules";

    // Generate module files
    files["main.bicep"] = GenerateMainBicep(request);
    files["parameters.json"] = GenerateParametersJson(request);

    // Generate module components
    files[$"{modulePath}/cluster.bicep"] = GenerateClusterBicep(request);
    files[$"{modulePath}/network.bicep"] = GenerateNetworkBicep(request);
    files[$"{modulePath}/identity.bicep"] = GenerateIdentityBicep(request);
    files[$"{modulePath}/monitoring.bicep"] = GenerateMonitoringBicep(request);
    files[$"{modulePath}/security.bicep"] = GenerateSecurityBicep(request);
    files[$"{modulePath}/acr.bicep"] = GenerateACRBicep(request);
    files[$"{modulePath}/acr-private-endpoint.bicep"] = GenerateACRPrivateEndpointBicep(request);    
    files[$"{modulePath}/pod-security-policies.yaml"] = GeneratePodSecurityPolicies();
    files[$"{modulePath}/network-policies.yaml"] = GenerateNetworkPolicies();
    files[$"{modulePath}/azure-policy-assignments.bicep"] = GenerateAzurePolicyAssignments();

    return files;
  }

  private string GenerateMainBicep(TemplateGenerationRequest request)
  {
    var sb = new StringBuilder();
    var serviceName = request.ServiceName.ToLowerInvariant();
    var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
    var security = request.Security ?? new SecuritySpec();
    var observability = request.Observability ?? new ObservabilitySpec();

    // Extract configuration values with intelligent defaults
    var environment = infrastructure.Environment ?? "dev";
    var kubernetesVersion = infrastructure.KubernetesVersion ?? "1.30";
    var nodeCount = infrastructure.NodeCount > 0 ? infrastructure.NodeCount : 3;
    var vmSize = infrastructure.VmSize ?? "Standard_D4s_v3";

    // Security settings
    var enableWorkloadIdentity = security.EnableWorkloadIdentity;
    var enableAzurePolicy = security.EnableAzurePolicy;
    var enablePrivateEndpoint = security.EnablePrivateEndpoint;
    var enableKeyVault = security.EnableKeyVault;

    // Monitoring settings
    var enableMonitoring = observability.ApplicationInsights || observability.Prometheus;

    var modulePath = "./modules";

    // Header
    sb.AppendLine("// AKS Cluster Module - Main Entry Point - FedRAMP Compliant");
    sb.AppendLine("// Implements: AC-3 (RBAC), AU-2 (Auditing), SC-7 (Network Segmentation), SC-28 (Encryption), SI-4 (Security Monitoring)");
    sb.AppendLine("// Generated by Platform Engineering Copilot");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();

    // Parameters
    sb.AppendLine("@description('Name of the service')");
    sb.AppendLine("param serviceName string");
    sb.AppendLine();
    sb.AppendLine("@description('Environment (dev, staging, prod)')");
    sb.AppendLine("param environment string");
    sb.AppendLine();
    sb.AppendLine("@description('Azure region')");
    sb.AppendLine("param location string = resourceGroup().location");
    sb.AppendLine();
    sb.AppendLine("@description('Kubernetes version')");
    sb.AppendLine($"param kubernetesVersion string = '{kubernetesVersion}'");
    sb.AppendLine();
    sb.AppendLine("@description('Enable Workload Identity')");
    sb.AppendLine($"param enableWorkloadIdentity bool = {enableWorkloadIdentity.ToString().ToLower()}");
    sb.AppendLine();
    sb.AppendLine("@description('Enable Azure Monitor')");
    sb.AppendLine($"param enableMonitoring bool = {enableMonitoring.ToString().ToLower()}");
    sb.AppendLine();
    sb.AppendLine("@description('Enable Azure Policy')");
    sb.AppendLine($"param enableAzurePolicy bool = {enableAzurePolicy.ToString().ToLower()}");
    sb.AppendLine();
    sb.AppendLine("@description('Enable Private Endpoint for ACR (recommended for Zero Trust)')");
    sb.AppendLine($"param enablePrivateEndpointACR bool = {enablePrivateEndpoint.ToString().ToLower()}");
    sb.AppendLine();
    sb.AppendLine("@description('Enable Key Vault')");
    sb.AppendLine($"param enableKeyVault bool = {enableKeyVault.ToString().ToLower()}");
    sb.AppendLine();
    sb.AppendLine("@description('Node pool size')");
    sb.AppendLine($"param nodeCount int = {nodeCount}");
    sb.AppendLine();
    sb.AppendLine("@description('Node VM size')");
    sb.AppendLine($"param nodeVmSize string = '{vmSize}'");
    sb.AppendLine();

    // Variables
    sb.AppendLine("var commonTags = {");
    sb.AppendLine("  Environment: environment");
    sb.AppendLine("  Service: serviceName");
    sb.AppendLine("  ManagedBy: 'bicep'");
    sb.AppendLine("  Platform: 'AKS'");
    sb.AppendLine("}");
    sb.AppendLine();

    // Network module
    sb.AppendLine("// Network module");
    sb.AppendLine($"module network '{modulePath}/network.bicep' = {{");
    sb.AppendLine("  name: '${serviceName}-${environment}-network'");
    sb.AppendLine("  params: {");
    sb.AppendLine("    serviceName: serviceName");
    sb.AppendLine("    environment: environment");
    sb.AppendLine("    location: location");
    sb.AppendLine("    tags: commonTags");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Identity module
    sb.AppendLine("// Identity module (Managed Identity + Workload Identity)");
    sb.AppendLine($"module identity '{modulePath}/identity.bicep' = {{");
    sb.AppendLine("  name: '${serviceName}-${environment}-identity'");
    sb.AppendLine("  params: {");
    sb.AppendLine("    serviceName: serviceName");
    sb.AppendLine("    environment: environment");
    sb.AppendLine("    location: location");
    sb.AppendLine("    enableWorkloadIdentity: enableWorkloadIdentity");
    sb.AppendLine("    tags: commonTags");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // AKS Cluster module
    sb.AppendLine("// AKS Cluster");
    sb.AppendLine($"module cluster '{modulePath}/cluster.bicep' = {{");
    sb.AppendLine("  name: '${serviceName}-${environment}-cluster'");
    sb.AppendLine("  params: {");
    sb.AppendLine("    serviceName: serviceName");
    sb.AppendLine("    environment: environment");
    sb.AppendLine("    location: location");
    sb.AppendLine("    kubernetesVersion: kubernetesVersion");
    sb.AppendLine("    nodeCount: nodeCount");
    sb.AppendLine("    nodeVmSize: nodeVmSize");
    sb.AppendLine("    subnetId: network.outputs.aksSubnetId");
    sb.AppendLine("    identityId: identity.outputs.managedIdentityId");
    sb.AppendLine("    enableWorkloadIdentity: enableWorkloadIdentity");
    sb.AppendLine("    enableAzurePolicy: enableAzurePolicy");
    sb.AppendLine("    tags: commonTags");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Azure Container Registry module
    sb.AppendLine("// Azure Container Registry");
    sb.AppendLine($"module acr '{modulePath}/acr.bicep' = {{");
    sb.AppendLine("  name: '${serviceName}-${environment}-acr'");
    sb.AppendLine("  params: {");
    sb.AppendLine("    serviceName: serviceName");
    sb.AppendLine("    environment: environment");
    sb.AppendLine("    location: location");
    sb.AppendLine("    clusterPrincipalId: cluster.outputs.kubeletIdentityObjectId");
    sb.AppendLine("    enablePrivateEndpoint: enablePrivateEndpointACR");
    sb.AppendLine("    tags: commonTags");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // ACR Private Endpoint (conditional)
    sb.AppendLine("// ACR Private Endpoint (if enabled)");
    sb.AppendLine($"module acrPrivateEndpoint '{modulePath}/acr-private-endpoint.bicep' = if (enablePrivateEndpointACR) {{");
    sb.AppendLine("  name: '${serviceName}-${environment}-acr-pe'");
    sb.AppendLine("  params: {");
    sb.AppendLine("    serviceName: serviceName");
    sb.AppendLine("    environment: environment");
    sb.AppendLine("    location: location");
    sb.AppendLine("    acrResourceId: acr.outputs.acrResourceId");
    sb.AppendLine("    subnetId: network.outputs.pesubnetSubnetId");
    sb.AppendLine("    virtualNetworkId: network.outputs.vnetId");
    sb.AppendLine("    tags: commonTags");
    sb.AppendLine("  }");
    sb.AppendLine("  dependsOn: [");
    sb.AppendLine("    acr");
    sb.AppendLine("  ]");
    sb.AppendLine("}");
    sb.AppendLine();

    // Security module (conditional on Key Vault)
    sb.AppendLine("// Security (Key Vault + Policies)");
    sb.AppendLine($"module security '{modulePath}/security.bicep' = if (enableKeyVault) {{");
    sb.AppendLine("  name: '${serviceName}-${environment}-security'");
    sb.AppendLine("  params: {");
    sb.AppendLine("    serviceName: serviceName");
    sb.AppendLine("    environment: environment");
    sb.AppendLine("    location: location");
    sb.AppendLine("    subnetId: network.outputs.aksSubnetId");
    sb.AppendLine("    clusterPrincipalId: cluster.outputs.kubeletIdentityObjectId");
    sb.AppendLine("    tags: commonTags");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Monitoring module (conditional)
    sb.AppendLine("// Monitoring (Log Analytics + Azure Monitor)");
    sb.AppendLine($"module monitoring '{modulePath}/monitoring.bicep' = if (enableMonitoring) {{");
    sb.AppendLine("  name: '${serviceName}-${environment}-monitoring'");
    sb.AppendLine("  params: {");
    sb.AppendLine("    serviceName: serviceName");
    sb.AppendLine("    environment: environment");
    sb.AppendLine("    location: location");
    sb.AppendLine("    clusterId: cluster.outputs.clusterId");
    sb.AppendLine("    tags: commonTags");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Outputs
    sb.AppendLine("// Outputs");
    sb.AppendLine("output clusterId string = cluster.outputs.clusterId");
    sb.AppendLine("output clusterName string = cluster.outputs.clusterName");
    sb.AppendLine("output clusterFqdn string = cluster.outputs.clusterFqdn");
    sb.AppendLine("output kubeletIdentityObjectId string = cluster.outputs.kubeletIdentityObjectId");
    sb.AppendLine("output acrLoginServer string = acr.outputs.loginServer");
    sb.AppendLine("output acrName string = acr.outputs.name");
    sb.AppendLine("output vnetId string = network.outputs.vnetId");
    sb.AppendLine("output keyVaultName string = enableKeyVault ? security.outputs.keyVaultName : ''");
    sb.AppendLine("output workspaceId string = enableMonitoring ? monitoring.outputs.workspaceId : ''");

    return sb.ToString();
  }

  private string GenerateClusterBicep(TemplateGenerationRequest request)
  {
    var sb = new StringBuilder();
    var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
    var security = request.Security ?? new SecuritySpec();
    var observability = request.Observability ?? new ObservabilitySpec();

    // Extract configuration values with intelligent defaults
    var environment = infrastructure.Environment ?? "dev";
    var kubernetesVersion = infrastructure.KubernetesVersion ?? "1.30";
    var nodeCount = infrastructure.NodeCount > 0 ? infrastructure.NodeCount : 3;
    var vmSize = infrastructure.VmSize ?? "Standard_D4s_v3";
    var minNodeCount = infrastructure.MinNodeCount;
    var maxNodeCount = infrastructure.MaxNodeCount;
    var userMinNodeCount = infrastructure.UserMinNodeCount;
    var userMaxNodeCount = infrastructure.UserMaxNodeCount;
    var maxPodsPerNode = infrastructure.MaxPodsPerNode;
    var osSku = infrastructure.OsSku;

    // Network configuration
    var serviceCidr = infrastructure.ServiceCidr;
    var dnsServiceIP = infrastructure.DnsServiceIP;
    var networkPlugin = infrastructure.NetworkPlugin;
    var networkPolicy = security.NetworkPolicyProvider;
    var loadBalancerSku = infrastructure.LoadBalancerSku;
    var outboundType = infrastructure.OutboundType;

    // SKU and support configuration
    var aksSkuTier = infrastructure.AksSkuTier;
    var supportPlan = infrastructure.SupportPlan;
    var upgradeChannel = infrastructure.UpgradeChannel;
    var nodeOsUpgradeChannel = infrastructure.NodeOsUpgradeChannel;

    // Security settings
    var enablePrivateCluster = security.EnablePrivateCluster;
    var enableWorkloadIdentity = security.EnableWorkloadIdentity;
    var enableAzurePolicy = security.EnableAzurePolicy;
    var enableImageCleaner = security.EnableImageCleaner;
    var enableDefender = security.EnableDefender;
    var enableKeyVaultProvider = security.EnableKeyVaultSecretsProvider;
    var disableLocalAccounts = security.DisableLocalAccounts;
    var authorizedIPRanges = security.AuthorizedIPRanges ?? new List<string>();
    var diskEncryptionSetId = security.DiskEncryptionSetId;
    var enableSecretRotation = security.EnableSecretRotation;
    var secretRotationPollInterval = security.SecretRotationPollInterval;

    // Monitoring settings
    var enableMonitoring = observability.ApplicationInsights || observability.Prometheus;

    // Header
    sb.AppendLine("// AKS Cluster Configuration - ZERO TRUST / FedRAMP ARCHITECTURE");
    sb.AppendLine("// FedRAMP Controls: AC-3 (RBAC), AU-2 (Audit Logging), SC-7 (Network Segmentation), SC-28 (Encryption), SI-4 (Defender)");
    sb.AppendLine("// Implements comprehensive Zero Trust security controls");
    sb.AppendLine("// - Private API Server with authorized IP ranges");
    sb.AppendLine("// - Pod Security Admission (restricted)");
    sb.AppendLine("// - Image scanning and vulnerability assessment");
    sb.AppendLine("// - Encryption at rest with customer-managed keys");
    sb.AppendLine("// - Comprehensive audit logging");
    sb.AppendLine("// - Network micro-segmentation");
    sb.AppendLine("// - Runtime threat detection with Microsoft Defender");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();

    // Parameters
    sb.AppendLine("param serviceName string");
    sb.AppendLine("param environment string");
    sb.AppendLine("param location string");
    sb.AppendLine($"param kubernetesVersion string = '{kubernetesVersion}'");
    sb.AppendLine($"param nodeCount int = {nodeCount}");
    sb.AppendLine($"param nodeVmSize string = '{vmSize}'");
    sb.AppendLine("param subnetId string");
    sb.AppendLine("param identityId string");
    sb.AppendLine($"param enableWorkloadIdentity bool = {enableWorkloadIdentity.ToString().ToLower()}");
    sb.AppendLine($"param enableAzurePolicy bool = {enableAzurePolicy.ToString().ToLower()}");
    sb.AppendLine("param tags object");
    sb.AppendLine();
    sb.AppendLine("@description('Enable Private Cluster (recommended for Zero Trust)')");
    sb.AppendLine($"param enablePrivateCluster bool = {enablePrivateCluster.ToString().ToLower()}");
    sb.AppendLine();

    if (authorizedIPRanges.Any())
    {
      sb.AppendLine("@description('Authorized IP ranges for API server access (if not private)')");
      sb.Append("param authorizedIPRanges array = [");
      sb.Append(string.Join(", ", authorizedIPRanges.Select(ip => $"'{ip}'")));
      sb.AppendLine("]");
    }
    else
    {
      sb.AppendLine("@description('Authorized IP ranges for API server access (if not private)')");
      sb.AppendLine("param authorizedIPRanges array = []");
    }
    sb.AppendLine();

    sb.AppendLine("@description('Log Analytics Workspace ID for monitoring')");
    sb.AppendLine("param logAnalyticsWorkspaceId string = ''");
    sb.AppendLine();
    sb.AppendLine("@description('Enable image cleaner')");
    sb.AppendLine($"param enableImageCleaner bool = {enableImageCleaner.ToString().ToLower()}");
    sb.AppendLine();

    if (!string.IsNullOrEmpty(diskEncryptionSetId))
    {
      sb.AppendLine("@description('Disk encryption set ID for customer-managed keys')");
      sb.AppendLine($"param diskEncryptionSetId string = '{diskEncryptionSetId}'");
    }
    else
    {
      sb.AppendLine("@description('Disk encryption set ID for customer-managed keys')");
      sb.AppendLine("param diskEncryptionSetId string = ''");
    }
    sb.AppendLine();

    // Variables
    sb.AppendLine("var clusterName = '${serviceName}-${environment}-aks'");
    sb.AppendLine();

    // AKS Cluster Resource
    sb.AppendLine("// AKS Cluster Configuration");
    sb.AppendLine("resource aksCluster 'Microsoft.ContainerService/managedClusters@2023-10-01' = {");
    sb.AppendLine("  name: clusterName");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  identity: {");
    sb.AppendLine("    type: 'UserAssigned'");
    sb.AppendLine("    userAssignedIdentities: {");
    sb.AppendLine("      '${identityId}': {}");
    sb.AppendLine("    }");
    sb.AppendLine("  }");
    sb.AppendLine("  sku: {");
    sb.AppendLine("    name: 'Base'");
    sb.AppendLine($"    tier: '{aksSkuTier}'");
    sb.AppendLine("  }");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    dnsPrefix: '${serviceName}-${environment}'");
    sb.AppendLine("    kubernetesVersion: kubernetesVersion");
    sb.AppendLine("    enableRBAC: true");
    sb.AppendLine("    ");

    // Network Configuration (Azure CNI - always enabled for best practices)
    sb.AppendLine("    // Network Configuration (Azure CNI)");
    sb.AppendLine("    networkProfile: {");
    sb.AppendLine($"      networkPlugin: '{networkPlugin}'");
    sb.AppendLine($"      networkPolicy: '{networkPolicy}'");
    sb.AppendLine($"      serviceCidr: '{serviceCidr}'");
    sb.AppendLine($"      dnsServiceIP: '{dnsServiceIP}'");
    sb.AppendLine($"      loadBalancerSku: '{loadBalancerSku}'");
    sb.AppendLine($"      outboundType: '{outboundType}'");
    sb.AppendLine("    }");
    sb.AppendLine("    ");

    // Default Node Pool (System)
    sb.AppendLine("    // Default Node Pool (System)");
    sb.AppendLine("    agentPoolProfiles: [");
    sb.AppendLine("      {");
    sb.AppendLine("        name: 'system'");
    sb.AppendLine("        count: nodeCount");
    sb.AppendLine("        vmSize: nodeVmSize");
    sb.AppendLine("        mode: 'System'");
    sb.AppendLine("        osType: 'Linux'");
    sb.AppendLine($"        osSKU: '{osSku}'");
    sb.AppendLine("        vnetSubnetID: subnetId");
    sb.AppendLine("        enableAutoScaling: true");
    sb.AppendLine($"        minCount: {minNodeCount}");
    sb.AppendLine($"        maxCount: {maxNodeCount}");
    sb.AppendLine($"        maxPods: {maxPodsPerNode}");
    sb.AppendLine("        type: 'VirtualMachineScaleSets'");
    sb.AppendLine("        availabilityZones: [");
    sb.AppendLine("          '1'");
    sb.AppendLine("          '2'");
    sb.AppendLine("          '3'");
    sb.AppendLine("        ]");
    sb.AppendLine("        enableNodePublicIP: false");
    sb.AppendLine("        tags: tags");
    sb.AppendLine("      }");
    sb.AppendLine("    ]");
    sb.AppendLine("    ");

    // Azure AD Integration (always enabled for Zero Trust)
    sb.AppendLine("    // Azure AD Integration");
    sb.AppendLine("    aadProfile: {");
    sb.AppendLine("      managed: true");
    sb.AppendLine("      enableAzureRBAC: true");
    sb.AppendLine("      tenantID: subscription().tenantId");
    sb.AppendLine("    }");
    sb.AppendLine("    ");

    // Security Profile (conditional features)
    sb.AppendLine("    // ZERO TRUST: Workload Identity + Image Integrity + Encryption");
    sb.AppendLine("    securityProfile: {");

    if (enableWorkloadIdentity)
    {
      sb.AppendLine("      workloadIdentity: {");
      sb.AppendLine("        enabled: enableWorkloadIdentity");
      sb.AppendLine("      }");
    }

    if (enableDefender)
    {
      sb.AppendLine("      defender: {");
      sb.AppendLine("        logAnalyticsWorkspaceResourceId: logAnalyticsWorkspaceId");
      sb.AppendLine("        securityMonitoring: {");
      sb.AppendLine("          enabled: true");
      sb.AppendLine("        }");
      sb.AppendLine("      }");
    }

    if (enableImageCleaner)
    {
      sb.AppendLine("      imageCleaner: {");
      sb.AppendLine("        enabled: enableImageCleaner");
      sb.AppendLine("        intervalHours: 168 // Weekly cleanup");
      sb.AppendLine("      }");
    }

    if (enableAzurePolicy)
    {
      sb.AppendLine("      // Pod Security Admission (replaces Pod Security Policy)");
      sb.AppendLine("      // Enforces restricted pod security standards");
      sb.AppendLine("      azurePolicyServerProfile: {");
      sb.AppendLine("        enabled: enableAzurePolicy");
      sb.AppendLine("      }");
    }

    sb.AppendLine("    }");
    sb.AppendLine("    ");

    // Encryption at rest (conditional)
    if (!string.IsNullOrEmpty(diskEncryptionSetId))
    {
      sb.AppendLine("    // Encryption at rest with customer-managed keys");
      sb.AppendLine("    diskEncryptionSetID: !empty(diskEncryptionSetId) ? diskEncryptionSetId : null");
      sb.AppendLine("    ");
    }

    // OIDC Issuer (conditional on workload identity)
    if (enableWorkloadIdentity)
    {
      sb.AppendLine("    // OIDC Issuer (required for Workload Identity)");
      sb.AppendLine("    oidcIssuerProfile: {");
      sb.AppendLine("      enabled: enableWorkloadIdentity");
      sb.AppendLine("    }");
      sb.AppendLine("    ");
    }

    // Auto-upgrade profile
    sb.AppendLine("    // Auto-upgrade channel with node image upgrade");
    sb.AppendLine("    autoUpgradeProfile: {");
    sb.AppendLine($"      upgradeChannel: '{upgradeChannel}'");
    sb.AppendLine($"      nodeOSUpgradeChannel: '{nodeOsUpgradeChannel}' // Auto-update node images for security patches");
    sb.AppendLine("    }");
    sb.AppendLine("    ");

    // Addon Profiles (conditional)
    sb.AppendLine("    // ZERO TRUST: Azure Policy + Key Vault + OMS Agent");
    sb.AppendLine("    addonProfiles: {");

    if (enableAzurePolicy)
    {
      sb.AppendLine("      azurepolicy: {");
      sb.AppendLine("        enabled: enableAzurePolicy");
      sb.AppendLine("        config: {");
      sb.AppendLine("          version: 'v2'");
      sb.AppendLine("        }");
      sb.AppendLine("      }");
    }

    if (enableKeyVaultProvider)
    {
      sb.AppendLine("      azureKeyvaultSecretsProvider: {");
      sb.AppendLine("        enabled: true");
      sb.AppendLine("        config: {");
      sb.AppendLine($"          enableSecretRotation: '{enableSecretRotation.ToString().ToLower()}'");
      sb.AppendLine($"          rotationPollInterval: '{secretRotationPollInterval}'");
      sb.AppendLine("        }");
      sb.AppendLine("      }");
    }

    if (enableMonitoring)
    {
      sb.AppendLine("      omsagent: !empty(logAnalyticsWorkspaceId) ? {");
      sb.AppendLine("        enabled: true");
      sb.AppendLine("        config: {");
      sb.AppendLine("          logAnalyticsWorkspaceResourceID: logAnalyticsWorkspaceId");
      sb.AppendLine("          useAADAuth: 'true'");
      sb.AppendLine("        }");
      sb.AppendLine("      } : {");
      sb.AppendLine("        enabled: false");
      sb.AppendLine("      }");
    }

    sb.AppendLine("    }");
    sb.AppendLine("    ");

    // API Server Access Profile
    sb.AppendLine("    // ZERO TRUST: Private API Server or Authorized IP Ranges");
    sb.AppendLine("    apiServerAccessProfile: {");
    sb.AppendLine("      enablePrivateCluster: enablePrivateCluster");
    sb.AppendLine("      enablePrivateClusterPublicFQDN: enablePrivateCluster");
    sb.AppendLine("      authorizedIPRanges: !enablePrivateCluster && length(authorizedIPRanges) > 0 ? authorizedIPRanges : []");
    sb.AppendLine("      enableVnetIntegration: enablePrivateCluster");
    sb.AppendLine("    }");
    sb.AppendLine("    ");

    // HTTP Application Routing (DISABLED for security)
    sb.AppendLine("    // HTTP Application Routing (DISABLED for security - use Ingress Controller)");
    sb.AppendLine("    httpApplicationRoutingEnabled: false");
    sb.AppendLine("    ");

    // Disable local accounts (conditional)
    if (disableLocalAccounts)
    {
      sb.AppendLine("    // ZERO TRUST: Disable local accounts (Azure AD only)");
      sb.AppendLine("    disableLocalAccounts: true");
      sb.AppendLine("    ");
    }

    // Storage profile with encrypted OS disks
    sb.AppendLine("    // Storage profile with encrypted OS disks");
    sb.AppendLine("    storageProfile: {");
    sb.AppendLine("      diskCSIDriver: {");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("        version: 'v1'");
    sb.AppendLine("      }");
    sb.AppendLine("      fileCSIDriver: {");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("      snapshotController: {");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("    }");
    sb.AppendLine("    ");

    // Support plan (dynamic based on environment)
    sb.AppendLine("    // Support plan (for production workloads)");
    sb.AppendLine($"    supportPlan: environment == 'prod' ? 'AKSLongTermSupport' : '{supportPlan}'");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // User Node Pool (Application workloads)
    sb.AppendLine("// User Node Pool (Application workloads)");
    sb.AppendLine("resource userNodePool 'Microsoft.ContainerService/managedClusters/agentPools@2023-10-01' = {");
    sb.AppendLine("  parent: aksCluster");
    sb.AppendLine("  name: 'user'");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    count: nodeCount");
    sb.AppendLine("    vmSize: nodeVmSize");
    sb.AppendLine("    mode: 'User'");
    sb.AppendLine("    osType: 'Linux'");
    sb.AppendLine($"    osSKU: '{osSku}'");
    sb.AppendLine("    vnetSubnetID: subnetId");
    sb.AppendLine("    enableAutoScaling: true");
    sb.AppendLine($"    minCount: {userMinNodeCount}");
    sb.AppendLine($"    maxCount: {userMaxNodeCount}");
    sb.AppendLine($"    maxPods: {maxPodsPerNode}");
    sb.AppendLine("    type: 'VirtualMachineScaleSets'");
    sb.AppendLine("    availabilityZones: [");
    sb.AppendLine("      '1'");
    sb.AppendLine("      '2'");
    sb.AppendLine("      '3'");
    sb.AppendLine("    ]");
    sb.AppendLine("    enableNodePublicIP: false");
    sb.AppendLine("    tags: union(tags, {");
    sb.AppendLine("      NodePool: 'user'");
    sb.AppendLine("      Workload: 'application'");
    sb.AppendLine("    })");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Outputs
    sb.AppendLine("output clusterId string = aksCluster.id");
    sb.AppendLine("output clusterName string = aksCluster.name");
    sb.AppendLine("output clusterFqdn string = aksCluster.properties.fqdn");
    sb.AppendLine("output kubeletIdentityObjectId string = aksCluster.properties.identityProfile.kubeletidentity.objectId");

    if (enableWorkloadIdentity)
    {
      sb.AppendLine("output oidcIssuerUrl string = enableWorkloadIdentity ? aksCluster.properties.oidcIssuerProfile.issuerURL : ''");
    }

    return sb.ToString();
  }

  private string GenerateNetworkBicep(TemplateGenerationRequest request)
  {
    var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
    var networkConfig = infrastructure.NetworkConfig ?? CreateDefaultAKSNetworkConfig();

    // Check if using existing network or creating new
    if (networkConfig.Mode == NetworkMode.UseExisting)
    {
      return GenerateExistingNetworkReferencesBicep(networkConfig);
    }

    var sb = new StringBuilder();

    sb.AppendLine("// Virtual Network Configuration for AKS");
    sb.AppendLine("// Implements network isolation with dedicated subnets");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();
    sb.AppendLine("param serviceName string");
    sb.AppendLine("param environment string");
    sb.AppendLine("param location string");
    sb.AppendLine("param tags object");
    sb.AppendLine();

    // VNet parameters
    sb.AppendLine($"@description('Virtual Network name')");
    sb.AppendLine($"param vnetName string = '{networkConfig.VNetName}'");
    sb.AppendLine();
    sb.AppendLine($"@description('Virtual Network address space')");
    sb.AppendLine($"param vnetAddressSpace string = '{networkConfig.VNetAddressSpace}'");
    sb.AppendLine();

    // DDoS Protection (if enabled)
    if (networkConfig.EnableDDoSProtection)
    {
      sb.AppendLine("@description('Enable DDoS Protection')");
      sb.AppendLine($"param enableDDoSProtection bool = {networkConfig.EnableDDoSProtection.ToString().ToLower()}");
      sb.AppendLine();
      if (!string.IsNullOrEmpty(networkConfig.DDoSProtectionPlanId))
      {
        sb.AppendLine("@description('DDoS Protection Plan ID')");
        sb.AppendLine($"param ddosProtectionPlanId string = '{networkConfig.DDoSProtectionPlanId}'");
        sb.AppendLine();
      }
    }

    // Virtual Network
    sb.AppendLine("// Virtual Network");
    sb.AppendLine("resource vnet 'Microsoft.Network/virtualNetworks@2023-05-01' = {");
    sb.AppendLine("  name: vnetName");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    addressSpace: {");
    sb.AppendLine("      addressPrefixes: [vnetAddressSpace]");
    sb.AppendLine("    }");

    if (networkConfig.EnableDDoSProtection && !string.IsNullOrEmpty(networkConfig.DDoSProtectionPlanId))
    {
      sb.AppendLine("    enableDdosProtection: enableDDoSProtection");
      sb.AppendLine("    ddosProtectionPlan: {");
      sb.AppendLine("      id: ddosProtectionPlanId");
      sb.AppendLine("    }");
    }

    // Subnets array
    sb.AppendLine("    subnets: [");
    foreach (var subnet in networkConfig.Subnets)
    {
      sb.AppendLine("      {");
      sb.AppendLine($"        name: '{subnet.Name}'");
      sb.AppendLine("        properties: {");
      sb.AppendLine($"          addressPrefix: '{subnet.AddressPrefix}'");
      sb.AppendLine("          privateEndpointNetworkPolicies: 'Disabled'");

      if (!string.IsNullOrEmpty(subnet.Delegation))
      {
        sb.AppendLine("          privateLinkServiceNetworkPolicies: 'Enabled'");
      }

      if (subnet.EnableServiceEndpoints && subnet.ServiceEndpoints.Any())
      {
        sb.AppendLine("          serviceEndpoints: [");
        foreach (var endpoint in subnet.ServiceEndpoints)
        {
          sb.AppendLine("            {");
          sb.AppendLine($"              service: '{endpoint}'");
          sb.AppendLine("            }");
        }
        sb.AppendLine("          ]");
      }

      sb.AppendLine("        }");
      sb.AppendLine("      }");
    }
    sb.AppendLine("    ]");

    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Network Security Group (if enabled)
    if (networkConfig.EnableNetworkSecurityGroup)
    {
      sb.AppendLine("// Network Security Group for AKS Subnet");
      sb.AppendLine("resource aksNsg 'Microsoft.Network/networkSecurityGroups@2023-05-01' = {");
      sb.AppendLine("  name: '${vnetName}-aks-nsg'");
      sb.AppendLine("  location: location");
      sb.AppendLine("  tags: tags");
      sb.AppendLine("  properties: {");
      sb.AppendLine("    securityRules: [");

      if (networkConfig.NsgRules.Any())
      {
        foreach (var rule in networkConfig.NsgRules)
        {
          sb.AppendLine("      {");
          sb.AppendLine($"        name: '{rule.Name}'");
          sb.AppendLine("        properties: {");
          sb.AppendLine($"          protocol: '{rule.Protocol}'");
          sb.AppendLine($"          sourcePortRange: '{rule.SourcePortRange}'");
          sb.AppendLine($"          destinationPortRange: '{rule.DestinationPortRange}'");
          sb.AppendLine($"          sourceAddressPrefix: '{rule.SourceAddressPrefix}'");
          sb.AppendLine($"          destinationAddressPrefix: '{rule.DestinationAddressPrefix}'");
          sb.AppendLine($"          access: '{rule.Access}'");
          sb.AppendLine($"          priority: {rule.Priority}");
          sb.AppendLine($"          direction: '{rule.Direction}'");
          sb.AppendLine($"          description: '{rule.Description}'");
          sb.AppendLine("        }");
          sb.AppendLine("      }");
        }
      }
      else
      {
        // Default rules for AKS
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'AllowHttpsInbound'");
        sb.AppendLine("        properties: {");
        sb.AppendLine("          protocol: 'Tcp'");
        sb.AppendLine("          sourcePortRange: '*'");
        sb.AppendLine("          destinationPortRange: '443'");
        sb.AppendLine("          sourceAddressPrefix: 'Internet'");
        sb.AppendLine("          destinationAddressPrefix: '*'");
        sb.AppendLine("          access: 'Allow'");
        sb.AppendLine("          priority: 100");
        sb.AppendLine("          direction: 'Inbound'");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
        sb.AppendLine("      {");
        sb.AppendLine("        name: 'AllowHttpInbound'");
        sb.AppendLine("        properties: {");
        sb.AppendLine("          protocol: 'Tcp'");
        sb.AppendLine("          sourcePortRange: '*'");
        sb.AppendLine("          destinationPortRange: '80'");
        sb.AppendLine("          sourceAddressPrefix: 'Internet'");
        sb.AppendLine("          destinationAddressPrefix: '*'");
        sb.AppendLine("          access: 'Allow'");
        sb.AppendLine("          priority: 110");
        sb.AppendLine("          direction: 'Inbound'");
        sb.AppendLine("        }");
        sb.AppendLine("      }");
      }

      sb.AppendLine("    ]");
      sb.AppendLine("  }");
      sb.AppendLine("}");
      sb.AppendLine();
    }

    // Outputs
    sb.AppendLine("// Outputs");
    sb.AppendLine("output vnetId string = vnet.id");
    sb.AppendLine("output vnetName string = vnet.name");

    // Output subnet IDs
    for (int i = 0; i < networkConfig.Subnets.Count; i++)
    {
      var subnet = networkConfig.Subnets[i];
      var outputName = subnet.Name.Replace("-", "").Replace("_", "") + "SubnetId";
      sb.AppendLine($"output {outputName} string = vnet.properties.subnets[{i}].id");
    }

    // Standard AKS subnet output (for compatibility)
    var aksSubnetIndex = networkConfig.Subnets.FindIndex(s => s.Name.Contains("aks") || s.Name.Contains("kubernetes"));
    if (aksSubnetIndex >= 0)
    {
      sb.AppendLine($"output aksSubnetId string = vnet.properties.subnets[{aksSubnetIndex}].id");
    }
    else if (networkConfig.Subnets.Any())
    {
      sb.AppendLine("output aksSubnetId string = vnet.properties.subnets[0].id");
    }

    return sb.ToString();
  }

  private string GenerateExistingNetworkReferencesBicep(NetworkingConfiguration networkConfig)
  {
    var sb = new StringBuilder();

    sb.AppendLine("// Reference Existing Network Resources for AKS");
    sb.AppendLine("// Generated by Platform Engineering Copilot");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();

    // Parameters
    sb.AppendLine("param serviceName string");
    sb.AppendLine("param environment string");
    sb.AppendLine($"param vnetName string = '{networkConfig.ExistingVNetName}'");
    sb.AppendLine($"param vnetResourceGroup string = '{networkConfig.ExistingVNetResourceGroup}'");
    sb.AppendLine("param location string = resourceGroup().location");
    sb.AppendLine("param tags object = {}");
    sb.AppendLine();

    // Reference existing VNet
    sb.AppendLine("// Reference existing Virtual Network");
    sb.AppendLine($"resource vnet 'Microsoft.Network/virtualNetworks@2023-05-01' existing = {{");
    sb.AppendLine($"  name: vnetName");
    sb.AppendLine($"  scope: resourceGroup(vnetResourceGroup)");
    sb.AppendLine("}");
    sb.AppendLine();

    // Find AKS and AppGW subnets
    var aksSubnet = networkConfig.ExistingSubnets.FirstOrDefault(s =>
        s.Purpose == SubnetPurpose.Application || s.Name.Contains("aks"));
    var appgwSubnet = networkConfig.ExistingSubnets.FirstOrDefault(s =>
        s.Purpose == SubnetPurpose.ApplicationGateway || s.Name.Contains("appgw") || s.Name.Contains("gateway"));

    if (aksSubnet != null)
    {
      sb.AppendLine("// Reference existing AKS subnet");
      sb.AppendLine($"resource aksSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {{");
      sb.AppendLine($"  parent: vnet");
      sb.AppendLine($"  name: '{aksSubnet.Name}'");
      sb.AppendLine("}");
      sb.AppendLine();
    }

    if (appgwSubnet != null)
    {
      sb.AppendLine("// Reference existing Application Gateway subnet");
      sb.AppendLine($"resource appgwSubnet 'Microsoft.Network/virtualNetworks/subnets@2023-05-01' existing = {{");
      sb.AppendLine($"  parent: vnet");
      sb.AppendLine($"  name: '{appgwSubnet.Name}'");
      sb.AppendLine("}");
      sb.AppendLine();
    }

    // Optionally create NSG if needed
    if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
    {
      sb.AppendLine("// Network Security Group for AKS");
      sb.AppendLine($"resource nsg 'Microsoft.Network/networkSecurityGroups@2023-05-01' = {{");
      sb.AppendLine($"  name: 'nsg-${{serviceName}}-${{environment}}-aks'");
      sb.AppendLine($"  location: location");
      sb.AppendLine($"  tags: tags");
      sb.AppendLine($"  properties: {{");
      sb.AppendLine($"    securityRules: [");

      foreach (var rule in networkConfig.NsgRules)
      {
        sb.AppendLine($"      {{");
        sb.AppendLine($"        name: '{rule.Name}'");
        sb.AppendLine($"        properties: {{");
        sb.AppendLine($"          priority: {rule.Priority}");
        sb.AppendLine($"          direction: '{rule.Direction}'");
        sb.AppendLine($"          access: '{rule.Access}'");
        sb.AppendLine($"          protocol: '{rule.Protocol}'");
        sb.AppendLine($"          sourcePortRange: '{rule.SourcePortRange}'");
        sb.AppendLine($"          destinationPortRange: '{rule.DestinationPortRange}'");
        sb.AppendLine($"          sourceAddressPrefix: '{rule.SourceAddressPrefix}'");
        sb.AppendLine($"          destinationAddressPrefix: '{rule.DestinationAddressPrefix}'");
        sb.AppendLine($"          description: '{rule.Description}'");
        sb.AppendLine($"        }}");
        sb.AppendLine($"      }}");
      }

      sb.AppendLine($"    ]");
      sb.AppendLine($"  }}");
      sb.AppendLine("}");
      sb.AppendLine();
    }

    // Outputs
    sb.AppendLine("// Outputs");
    sb.AppendLine("output vnetId string = vnet.id");

    if (aksSubnet != null)
    {
      sb.AppendLine("output aksSubnetId string = aksSubnet.id");
    }

    if (appgwSubnet != null)
    {
      sb.AppendLine("output appgwSubnetId string = appgwSubnet.id");
    }

    if (networkConfig.EnableNetworkSecurityGroup && networkConfig.NsgRules.Any())
    {
      sb.AppendLine("output nsgId string = nsg.id");
    }

    return sb.ToString();
  }

  private NetworkingConfiguration CreateDefaultAKSNetworkConfig()
  {
    return new NetworkingConfiguration
    {
      Mode = NetworkMode.CreateNew,
      VNetName = "${serviceName}-${environment}-vnet",
      VNetAddressSpace = "10.0.0.0/16",
      Subnets = new List<SubnetConfiguration>
            {
                new SubnetConfiguration
                {
                    Name = "aks-subnet",
                    AddressPrefix = "10.0.0.0/20",
                    Purpose = SubnetPurpose.Application,
                    EnableServiceEndpoints = true,
                    ServiceEndpoints = new List<string>
                    {
                        "Microsoft.Storage",
                        "Microsoft.KeyVault",
                        "Microsoft.ContainerRegistry"
                    }
                },
                new SubnetConfiguration
                {
                    Name = "appgw-subnet",
                    AddressPrefix = "10.0.16.0/24",
                    Purpose = SubnetPurpose.ApplicationGateway
                },
                new SubnetConfiguration
                {
                    Name = "pe-subnet",
                    AddressPrefix = "10.0.17.0/24",
                    Purpose = SubnetPurpose.PrivateEndpoints
                }
            },
      EnableNetworkSecurityGroup = true,
      EnablePrivateEndpoint = false,
      EnableServiceEndpoints = true,
      EnableDDoSProtection = false,
      EnablePrivateDns = false
    };
  }

  private string GenerateIdentityBicep(TemplateGenerationRequest request)
  {
    var sb = new StringBuilder();
    var security = request.Security ?? new SecuritySpec();

    // Extract configuration
    var enableWorkloadIdentity = security.EnableWorkloadIdentity;

    // Header
    sb.AppendLine("// Managed Identity Configuration for AKS");
    sb.AppendLine("// Implements Workload Identity for pod-level authentication");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();

    // Parameters
    sb.AppendLine("param serviceName string");
    sb.AppendLine("param environment string");
    sb.AppendLine("param location string");
    sb.AppendLine($"param enableWorkloadIdentity bool = {enableWorkloadIdentity.ToString().ToLower()}");
    sb.AppendLine("param tags object");
    sb.AppendLine();

    // Variables
    sb.AppendLine("var identityName = '${serviceName}-${environment}-identity'");
    sb.AppendLine();

    // User-Assigned Managed Identity for AKS Cluster (always required)
    sb.AppendLine("// User-Assigned Managed Identity for AKS Cluster");
    sb.AppendLine("resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {");
    sb.AppendLine("  name: identityName");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("}");
    sb.AppendLine();

    // Workload Identity (conditional)
    sb.AppendLine("// Workload Identity for application pods (conditional)");
    sb.AppendLine("resource workloadIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = if (enableWorkloadIdentity) {");
    sb.AppendLine("  name: '${serviceName}-${environment}-workload-identity'");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: union(tags, {");
    sb.AppendLine("    Purpose: 'WorkloadIdentity'");
    sb.AppendLine("  })");
    sb.AppendLine("}");
    sb.AppendLine();

    // Comment about federated identity credential
    sb.AppendLine("// Federated Identity Credential (for Workload Identity)");
    sb.AppendLine("// This will be created after cluster provisioning with actual OIDC issuer URL");
    sb.AppendLine("// Example: kubectl apply -f federated-credential.yaml");
    sb.AppendLine();

    // Outputs
    sb.AppendLine("output managedIdentityId string = managedIdentity.id");
    sb.AppendLine("output managedIdentityPrincipalId string = managedIdentity.properties.principalId");
    sb.AppendLine("output managedIdentityClientId string = managedIdentity.properties.clientId");
    sb.AppendLine("output workloadIdentityId string = enableWorkloadIdentity ? workloadIdentity.id : ''");
    sb.AppendLine("output workloadIdentityPrincipalId string = enableWorkloadIdentity ? workloadIdentity.properties.principalId : ''");
    sb.AppendLine("output workloadIdentityClientId string = enableWorkloadIdentity ? workloadIdentity.properties.clientId : ''");

    return sb.ToString();
  }

  private string GenerateMonitoringBicep(TemplateGenerationRequest request)
  {
    var sb = new StringBuilder();
    var observability = request.Observability ?? new ObservabilitySpec();

    // Extract configuration
    var enableApplicationInsights = observability.ApplicationInsights;
    var enablePrometheus = observability.Prometheus;
    var enableContainerInsights = enableApplicationInsights; // Container Insights depends on App Insights

    // Header
    sb.AppendLine("// Azure Monitor Configuration for AKS");
    sb.AppendLine("// Implements Container Insights and Prometheus monitoring");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();

    // Parameters
    sb.AppendLine("param serviceName string");
    sb.AppendLine("param environment string");
    sb.AppendLine("param location string");
    sb.AppendLine("param clusterId string");
    sb.AppendLine("param tags object");
    sb.AppendLine();
    sb.AppendLine($"@description('Enable Container Insights')");
    sb.AppendLine($"param enableContainerInsights bool = {enableContainerInsights.ToString().ToLower()}");
    sb.AppendLine();
    sb.AppendLine($"@description('Enable Prometheus monitoring')");
    sb.AppendLine($"param enablePrometheus bool = {enablePrometheus.ToString().ToLower()}");
    sb.AppendLine();

    // Variables
    sb.AppendLine("var workspaceName = '${serviceName}-${environment}-logs'");
    sb.AppendLine();

    // Log Analytics Workspace (always created for monitoring)
    sb.AppendLine("// Log Analytics Workspace");
    sb.AppendLine("resource workspace 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {");
    sb.AppendLine("  name: workspaceName");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    sku: {");
    sb.AppendLine("      name: 'PerGB2018'");
    sb.AppendLine("    }");
    sb.AppendLine("    retentionInDays: 30");
    sb.AppendLine("    features: {");
    sb.AppendLine("      enableLogAccessUsingOnlyResourcePermissions: true");
    sb.AppendLine("    }");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Container Insights Solution (conditional)
    sb.AppendLine("// Container Insights Solution (conditional)");
    sb.AppendLine("resource containerInsights 'Microsoft.OperationsManagement/solutions@2015-11-01-preview' = if (enableContainerInsights) {");
    sb.AppendLine("  name: 'ContainerInsights(${workspace.name})'");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    workspaceResourceId: workspace.id");
    sb.AppendLine("  }");
    sb.AppendLine("  plan: {");
    sb.AppendLine("    name: 'ContainerInsights(${workspace.name})'");
    sb.AppendLine("    product: 'OMSGallery/ContainerInsights'");
    sb.AppendLine("    publisher: 'Microsoft'");
    sb.AppendLine("    promotionCode: ''");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Azure Monitor Workspace for Prometheus (conditional)
    sb.AppendLine("// Azure Monitor Workspace (for Prometheus - conditional)");
    sb.AppendLine("resource azureMonitorWorkspace 'Microsoft.Monitor/accounts@2023-04-03' = if (enablePrometheus) {");
    sb.AppendLine("  name: '${serviceName}-${environment}-monitor'");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  properties: {}");
    sb.AppendLine("}");
    sb.AppendLine();

    // Data Collection Endpoint (conditional on Prometheus)
    sb.AppendLine("// Data Collection Endpoint (conditional on Prometheus)");
    sb.AppendLine("resource dataCollectionEndpoint 'Microsoft.Insights/dataCollectionEndpoints@2022-06-01' = if (enablePrometheus) {");
    sb.AppendLine("  name: '${serviceName}-${environment}-dce'");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    networkAcls: {");
    sb.AppendLine("      publicNetworkAccess: 'Enabled'");
    sb.AppendLine("    }");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Data Collection Rule for Prometheus (conditional)
    sb.AppendLine("// Data Collection Rule (for Prometheus metrics - conditional)");
    sb.AppendLine("resource dataCollectionRule 'Microsoft.Insights/dataCollectionRules@2022-06-01' = if (enablePrometheus) {");
    sb.AppendLine("  name: '${serviceName}-${environment}-dcr'");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    dataCollectionEndpointId: dataCollectionEndpoint.id");
    sb.AppendLine("    dataSources: {");
    sb.AppendLine("      prometheusForwarder: [");
    sb.AppendLine("        {");
    sb.AppendLine("          name: 'PrometheusDataSource'");
    sb.AppendLine("          streams: [");
    sb.AppendLine("            'Microsoft-PrometheusMetrics'");
    sb.AppendLine("          ]");
    sb.AppendLine("        }");
    sb.AppendLine("      ]");
    sb.AppendLine("    }");
    sb.AppendLine("    destinations: {");
    sb.AppendLine("      monitoringAccounts: [");
    sb.AppendLine("        {");
    sb.AppendLine("          accountResourceId: azureMonitorWorkspace.id");
    sb.AppendLine("          name: 'MonitoringAccount'");
    sb.AppendLine("        }");
    sb.AppendLine("      ]");
    sb.AppendLine("    }");
    sb.AppendLine("    dataFlows: [");
    sb.AppendLine("      {");
    sb.AppendLine("        streams: [");
    sb.AppendLine("          'Microsoft-PrometheusMetrics'");
    sb.AppendLine("        ]");
    sb.AppendLine("        destinations: [");
    sb.AppendLine("          'MonitoringAccount'");
    sb.AppendLine("        ]");
    sb.AppendLine("      }");
    sb.AppendLine("    ]");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Diagnostic Settings for AKS (always enabled for audit logging)
    sb.AppendLine("// Diagnostic Settings for AKS (audit logging)");
    sb.AppendLine("resource diagnosticSettings 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {");
    sb.AppendLine("  name: '${serviceName}-${environment}-diagnostics'");
    sb.AppendLine("  scope: resourceGroup()");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    workspaceId: workspace.id");
    sb.AppendLine("    logs: [");
    sb.AppendLine("      {");
    sb.AppendLine("        category: 'kube-apiserver'");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("      {");
    sb.AppendLine("        category: 'kube-controller-manager'");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("      {");
    sb.AppendLine("        category: 'kube-scheduler'");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("      {");
    sb.AppendLine("        category: 'kube-audit'");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("      {");
    sb.AppendLine("        category: 'guard'");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("    ]");
    sb.AppendLine("    metrics: [");
    sb.AppendLine("      {");
    sb.AppendLine("        category: 'AllMetrics'");
    sb.AppendLine("        enabled: true");
    sb.AppendLine("      }");
    sb.AppendLine("    ]");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Outputs
    sb.AppendLine("output workspaceId string = workspace.id");
    sb.AppendLine("output workspaceName string = workspace.name");
    sb.AppendLine("output azureMonitorWorkspaceId string = enablePrometheus ? azureMonitorWorkspace.id : ''");
    sb.AppendLine("output dataCollectionRuleId string = enablePrometheus ? dataCollectionRule.id : ''");

    return sb.ToString();
  }

  private string GenerateSecurityBicep(TemplateGenerationRequest request)
  {
    var sb = new StringBuilder();
    var security = request.Security ?? new SecuritySpec();

    // Extract configuration
    var enablePrivateEndpoint = security.EnablePrivateEndpoint;

    // Header
    sb.AppendLine("// Security Configuration - Key Vault and Policies");
    sb.AppendLine("// Implements Azure Key Vault with Secrets Provider integration");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();

    // Parameters
    sb.AppendLine("param serviceName string");
    sb.AppendLine("param environment string");
    sb.AppendLine("param location string");
    sb.AppendLine("param subnetId string");
    sb.AppendLine("param clusterPrincipalId string");
    sb.AppendLine("param tags object");
    sb.AppendLine();
    sb.AppendLine($"@description('Enable private endpoint network policies')");
    sb.AppendLine($"param enablePrivateEndpoint bool = {enablePrivateEndpoint.ToString().ToLower()}");
    sb.AppendLine();

    // Variables
    sb.AppendLine("var keyVaultName = '${serviceName}-${environment}-kv'");
    sb.AppendLine();

    // Azure Key Vault
    sb.AppendLine("// Azure Key Vault");
    sb.AppendLine("resource keyVault 'Microsoft.KeyVault/vaults@2023-02-01' = {");
    sb.AppendLine("  name: take(replace(keyVaultName, '-', ''), 24) // Key Vault names max 24 chars, no hyphens");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    sku: {");
    sb.AppendLine("      family: 'A'");
    sb.AppendLine("      name: 'standard'");
    sb.AppendLine("    }");
    sb.AppendLine("    tenantId: subscription().tenantId");
    sb.AppendLine("    enableRbacAuthorization: true");
    sb.AppendLine("    enableSoftDelete: true");
    sb.AppendLine("    softDeleteRetentionInDays: 90");
    sb.AppendLine("    enablePurgeProtection: true");

    // Network ACLs (conditional based on private endpoint)
    if (enablePrivateEndpoint)
    {
      sb.AppendLine("    networkAcls: {");
      sb.AppendLine("      bypass: 'AzureServices'");
      sb.AppendLine("      defaultAction: 'Deny'");
      sb.AppendLine("      virtualNetworkRules: [");
      sb.AppendLine("        {");
      sb.AppendLine("          id: subnetId");
      sb.AppendLine("          ignoreMissingVnetServiceEndpoint: false");
      sb.AppendLine("        }");
      sb.AppendLine("      ]");
      sb.AppendLine("    }");
    }
    else
    {
      sb.AppendLine("    networkAcls: {");
      sb.AppendLine("      bypass: 'AzureServices'");
      sb.AppendLine("      defaultAction: 'Allow'");
      sb.AppendLine("    }");
    }

    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Key Vault Secrets Officer role for AKS
    sb.AppendLine("// Key Vault Secrets Officer role for AKS");
    sb.AppendLine("resource keyVaultSecretsOfficer 'Microsoft.Authorization/roleAssignments@2022-04-01' = {");
    sb.AppendLine("  name: guid(keyVault.id, clusterPrincipalId, 'Key Vault Secrets Officer')");
    sb.AppendLine("  scope: keyVault");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7') // Key Vault Secrets Officer");
    sb.AppendLine("    principalId: clusterPrincipalId");
    sb.AppendLine("    principalType: 'ServicePrincipal'");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Example secrets (to be populated by deployment pipeline)
    sb.AppendLine("// Example secrets (to be populated by deployment pipeline)");
    sb.AppendLine("resource exampleSecret 'Microsoft.KeyVault/vaults/secrets@2023-02-01' = {");
    sb.AppendLine("  parent: keyVault");
    sb.AppendLine("  name: 'database-connection-string'");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    value: 'placeholder-update-via-pipeline'");
    sb.AppendLine("    contentType: 'text/plain'");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Outputs
    sb.AppendLine("output keyVaultId string = keyVault.id");
    sb.AppendLine("output keyVaultName string = keyVault.name");
    sb.AppendLine("output keyVaultUri string = keyVault.properties.vaultUri");

    return sb.ToString();
  }

  private string GenerateACRBicep(TemplateGenerationRequest request)
  {
    var sb = new StringBuilder();
    var serviceName = request.ServiceName.ToLowerInvariant();
    var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
    var security = request.Security ?? new SecuritySpec();

    // Extract configuration
    var environment = infrastructure.Environment ?? "dev";
    var enablePrivateEndpoint = security.EnablePrivateEndpoint;

    // SKU based on environment (Premium for prod, Standard for others)
    var acrSku = environment == "prod" ? "Premium" : "Standard";

    // Zone redundancy only for Premium SKU
    var enableZoneRedundancy = acrSku == "Premium";

    // Header
    sb.AppendLine("// Azure Container Registry Configuration");
    sb.AppendLine("// Implements Premium tier with geo-replication and security features");
    sb.AppendLine();
    sb.AppendLine("targetScope = 'resourceGroup'");
    sb.AppendLine();

    // Parameters
    sb.AppendLine("param serviceName string");
    sb.AppendLine("param environment string");
    sb.AppendLine("param location string");
    sb.AppendLine("param clusterPrincipalId string");
    sb.AppendLine($"param enablePrivateEndpoint bool = {enablePrivateEndpoint.ToString().ToLower()}");
    sb.AppendLine("param tags object");
    sb.AppendLine();
    sb.AppendLine($"@description('ACR SKU tier')");
    sb.AppendLine($"param acrSku string = '{acrSku}'");
    sb.AppendLine();

    // Variables
    sb.AppendLine("var acrName = replace('${serviceName}${environment}acr', '-', '')");
    sb.AppendLine();

    // Azure Container Registry
    sb.AppendLine("// Azure Container Registry");
    sb.AppendLine("resource acr 'Microsoft.ContainerRegistry/registries@2023-07-01' = {");
    sb.AppendLine("  name: take(acrName, 50) // ACR names max 50 chars");
    sb.AppendLine("  location: location");
    sb.AppendLine("  tags: tags");
    sb.AppendLine("  sku: {");
    sb.AppendLine("    name: acrSku");
    sb.AppendLine("  }");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    adminUserEnabled: false");
    sb.AppendLine("    publicNetworkAccess: enablePrivateEndpoint ? 'Disabled' : 'Enabled'");
    sb.AppendLine("    networkRuleBypassOptions: 'AzureServices'");

    if (enableZoneRedundancy)
    {
      sb.AppendLine("    zoneRedundancy: 'Enabled'");
    }

    sb.AppendLine("    ");
    sb.AppendLine("    // Anonymous pull (disabled for security)");
    sb.AppendLine("    anonymousPullEnabled: false");
    sb.AppendLine("    ");
    sb.AppendLine("    // Data endpoint (for zone redundancy)");
    sb.AppendLine("    dataEndpointEnabled: true");
    sb.AppendLine("    ");
    sb.AppendLine("    // Policies");
    sb.AppendLine("    policies: {");
    sb.AppendLine("      quarantinePolicy: {");
    sb.AppendLine("        status: 'enabled'");
    sb.AppendLine("      }");
    sb.AppendLine("      trustPolicy: {");
    sb.AppendLine("        type: 'Notary'");
    sb.AppendLine("        status: 'enabled'");
    sb.AppendLine("      }");
    sb.AppendLine("      retentionPolicy: {");
    sb.AppendLine("        days: 30");
    sb.AppendLine("        status: 'enabled'");
    sb.AppendLine("      }");
    sb.AppendLine("      azureADAuthenticationAsArmPolicy: {");
    sb.AppendLine("        status: 'enabled'");
    sb.AppendLine("      }");
    sb.AppendLine("      softDeletePolicy: {");
    sb.AppendLine("        retentionDays: 7");
    sb.AppendLine("        status: 'enabled'");
    sb.AppendLine("      }");
    sb.AppendLine("    }");
    sb.AppendLine("    ");
    sb.AppendLine("    // Encryption");
    sb.AppendLine("    encryption: {");
    sb.AppendLine("      status: 'disabled' // Can enable with customer-managed keys");
    sb.AppendLine("    }");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // AcrPull role for AKS kubelet identity
    sb.AppendLine("// AcrPull role for AKS kubelet identity");
    sb.AppendLine("resource acrPullRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {");
    sb.AppendLine("  name: guid(acr.id, clusterPrincipalId, 'AcrPull')");
    sb.AppendLine("  scope: acr");
    sb.AppendLine("  properties: {");
    sb.AppendLine("    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d') // AcrPull");
    sb.AppendLine("    principalId: clusterPrincipalId");
    sb.AppendLine("    principalType: 'ServicePrincipal'");
    sb.AppendLine("  }");
    sb.AppendLine("}");
    sb.AppendLine();

    // Outputs
    sb.AppendLine("output loginServer string = acr.properties.loginServer");
    sb.AppendLine("output name string = acr.name");
    sb.AppendLine("output id string = acr.id");
    sb.AppendLine("output acrResourceId string = acr.id");

    return sb.ToString();
  }

  private string GenerateACRPrivateEndpointBicep(TemplateGenerationRequest request)
  {
    return @"// Private Endpoint for Azure Container Registry
// Allows ACR to be accessible only via private network

targetScope = 'resourceGroup'

param serviceName string
param environment string
param location string
param acrResourceId string
param subnetId string
param virtualNetworkId string
param tags object

var privateEndpointName = '${serviceName}-${environment}-acr-pe'
var privateDnsZoneName = 'privatelink.azurecr.io'
var pvtEndpointDnsGroupName = '${privateEndpointName}/default'

resource privateEndpoint 'Microsoft.Network/privateEndpoints@2023-05-01' = {
  name: privateEndpointName
  location: location
  tags: tags
  properties: {
    subnet: {
      id: subnetId
    }
    privateLinkServiceConnections: [
      {
        name: '${serviceName}-${environment}-acr-plsc'
        properties: {
          privateLinkServiceId: acrResourceId
          groupIds: ['registry']
        }
      }
    ]
  }
}

resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' = {
  name: privateDnsZoneName
  location: 'global'
  tags: tags
}

resource privateDnsZoneLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2020-06-01' = {
  parent: privateDnsZone
  name: '${serviceName}-${environment}-acr-dns-link'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: virtualNetworkId
    }
  }
}

resource pvtEndpointDnsGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2023-05-01' = {
  name: pvtEndpointDnsGroupName
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'config1'
        properties: {
          privateDnsZoneId: privateDnsZone.id
        }
      }
    ]
  }
  dependsOn: [
    privateEndpoint
  ]
}

output privateEndpointId string = privateEndpoint.id
output privateDnsZoneId string = privateDnsZone.id
output privateEndpointIP string = privateEndpoint.properties.customDnsConfigs[0].ipAddresses[0]
";
  }

  private string GenerateParametersJson(TemplateGenerationRequest request)
  {
    var sb = new StringBuilder();
    var serviceName = request.ServiceName.ToLowerInvariant();
    var infrastructure = request.Infrastructure ?? new InfrastructureSpec();
    var security = request.Security ?? new SecuritySpec();
    var observability = request.Observability ?? new ObservabilitySpec();

    // Extract configuration values with intelligent defaults
    var environment = infrastructure.Environment ?? "dev";
    var region = infrastructure.Region ?? "eastus";
    var kubernetesVersion = infrastructure.KubernetesVersion ?? "1.30";
    var nodeCount = infrastructure.NodeCount > 0 ? infrastructure.NodeCount : 3;
    var vmSize = infrastructure.VmSize ?? "Standard_D4s_v3";

    // Security settings
    var enablePrivateCluster = security.EnablePrivateCluster;
    var enableWorkloadIdentity = security.EnableWorkloadIdentity;
    var enableAzurePolicy = security.EnableAzurePolicy;
    var enableImageCleaner = security.EnableImageCleaner;
    var enablePrivateEndpoint = security.EnablePrivateEndpoint;
    var authorizedIPRanges = security.AuthorizedIPRanges ?? new List<string>();
    var diskEncryptionSetId = security.DiskEncryptionSetId ?? "";

    // Monitoring settings
    var enableMonitoring = observability.ApplicationInsights || observability.Prometheus;

    // Environment-based defaults
    var isProduction = environment.ToLower() == "prod" || environment.ToLower() == "production";

    // Build JSON
    sb.AppendLine("{");
    sb.AppendLine("  \"$schema\": \"https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#\",");
    sb.AppendLine("  \"contentVersion\": \"1.0.0.0\",");
    sb.AppendLine("  \"parameters\": {");
    sb.AppendLine("    \"serviceName\": {");
    sb.AppendLine($"      \"value\": \"{serviceName}\"");
    sb.AppendLine("    },");
    sb.AppendLine("    \"environment\": {");
    sb.AppendLine($"      \"value\": \"{environment}\"");
    sb.AppendLine("    },");
    sb.AppendLine("    \"location\": {");
    sb.AppendLine($"      \"value\": \"{region}\"");
    sb.AppendLine("    },");
    sb.AppendLine("    ");
    sb.AppendLine("    // === Security & Identity Parameters ===");
    sb.AppendLine("    \"enablePrivateCluster\": {");
    sb.AppendLine($"      \"value\": {enablePrivateCluster.ToString().ToLower()}");
    sb.AppendLine("    },");
    sb.AppendLine("    \"enableWorkloadIdentity\": {");
    sb.AppendLine($"      \"value\": {enableWorkloadIdentity.ToString().ToLower()}");
    sb.AppendLine("    },");

    if (authorizedIPRanges.Any())
    {
      sb.AppendLine("    \"authorizedIPRanges\": {");
      sb.Append("      \"value\": [");
      sb.Append(string.Join(", ", authorizedIPRanges.Select(ip => $"\"{ip}\"")));
      sb.AppendLine("]");
      sb.AppendLine("    },");
    }
    else
    {
      sb.AppendLine("    \"authorizedIPRanges\": {");
      sb.AppendLine("      \"value\": []");
      sb.AppendLine("    },");
    }

    sb.AppendLine("    ");
    sb.AppendLine("    // === Monitoring Parameters ===");
    sb.AppendLine("    \"enableMonitoring\": {");
    sb.AppendLine($"      \"value\": {enableMonitoring.ToString().ToLower()}");
    sb.AppendLine("    },");
    sb.AppendLine("    \"logAnalyticsWorkspaceId\": {");
    sb.AppendLine("      \"value\": \"\"");
    sb.AppendLine("    },");
    sb.AppendLine("    \"enableAzurePolicy\": {");
    sb.AppendLine($"      \"value\": {enableAzurePolicy.ToString().ToLower()}");
    sb.AppendLine("    },");
    sb.AppendLine("    ");
    sb.AppendLine("    // === Cluster Configuration Parameters ===");
    sb.AppendLine("    \"kubernetesVersion\": {");
    sb.AppendLine($"      \"value\": \"{kubernetesVersion}\"");
    sb.AppendLine("    },");
    sb.AppendLine("    \"nodeCount\": {");
    sb.AppendLine($"      \"value\": {nodeCount}");
    sb.AppendLine("    },");
    sb.AppendLine("    \"nodeVmSize\": {");
    sb.AppendLine($"      \"value\": \"{vmSize}\"");
    sb.AppendLine("    },");
    sb.AppendLine("    ");
    sb.AppendLine("    // === Advanced Security Parameters ===");
    sb.AppendLine("    \"enableImageCleaner\": {");
    sb.AppendLine($"      \"value\": {enableImageCleaner.ToString().ToLower()}");
    sb.AppendLine("    },");
    sb.AppendLine("    \"diskEncryptionSetId\": {");
    sb.AppendLine($"      \"value\": \"{diskEncryptionSetId}\"");
    sb.AppendLine("    },");
    sb.AppendLine("    \"enablePrivateEndpointACR\": {");
    sb.AppendLine($"      \"value\": {enablePrivateEndpoint.ToString().ToLower()}");
    sb.AppendLine("    },");
    sb.AppendLine("    \"enableKeyVault\": {");
    sb.AppendLine($"      \"value\": {security.EnableKeyVault.ToString().ToLower()}");
    sb.AppendLine("    }");
    sb.AppendLine("  }");
    sb.AppendLine("}");

    return sb.ToString();
  }

  private string GeneratePodSecurityPolicies()
  {
    return @"# Pod Security Standards - Restricted Profile
# Enforces most restrictive security controls for Zero Trust
# Apply this to production namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
# Example: Secure Pod with non-root user, read-only filesystem
apiVersion: v1
kind: Pod
metadata:
  name: secure-app-example
  namespace: production
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: app
    image: myapp:latest
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop:
        - ALL
    resources:
      limits:
        cpu: ""1""
        memory: ""512Mi""
      requests:
        cpu: ""100m""
        memory: ""128Mi""
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}
";
  }

  private string GenerateNetworkPolicies()
  {
    return @"# Zero Trust Network Policies
# Implements default-deny and explicit-allow micro-segmentation
---
# Default Deny All Ingress and Egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# Allow DNS Resolution
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: production
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
---
# Allow Frontend to Backend Communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 8080
---
# Allow Backend to Database
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-to-database
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend
    ports:
    - protocol: TCP
      port: 5432
---
# Allow Ingress Controller Traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
---
# Allow Egress to Azure Services (Key Vault, Storage, etc.)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-azure-services
  namespace: production
spec:
  podSelector:
    matchLabels:
      azure-service-access: enabled
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 443
";
  }

  private string GenerateAzurePolicyAssignments()
  {
    return @"// Azure Policy Assignments for AKS - Zero Trust Compliance
// Enforces security, compliance, and operational best practices
targetScope = 'resourceGroup'

param clusterName string
param location string

// Reference the AKS cluster
resource aksCluster 'Microsoft.ContainerService/managedClusters@2023-10-01' existing = {
  name: clusterName
}

// Policy: Kubernetes cluster containers should only use allowed images
resource allowedContainerImagesPolicy 'Microsoft.Authorization/policyAssignments@2023-04-01' = {
  name: 'aks-allowed-images-${clusterName}'
  location: location
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/febd0533-8e55-448f-b837-bd0e06f16469'
    parameters: {
      excludedNamespaces: {
        value: [
          'kube-system'
          'gatekeeper-system'
          'azure-arc'
        ]
      }
      namespaces: {
        value: []
      }
      labelSelector: {
        value: {}
      }
      allowedContainerImagesRegex: {
        value: '^.+\\\\.azurecr\\\\.io/.+$|^mcr\\\\.microsoft\\\\.com/.+$'
      }
    }
    displayName: 'Allowed Container Images (ACR and MCR only)'
    description: 'Restricts container images to approved registries'
  }
  identity: {
    type: 'SystemAssigned'
  }
}

// Policy: Do not allow privileged containers
resource noPrivilegedContainersPolicy 'Microsoft.Authorization/policyAssignments@2023-04-01' = {
  name: 'aks-no-priv-containers-${take(clusterName, 40)}'
  location: location
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/95edb821-ddaf-4404-9732-666045e056b4'
    parameters: {
      excludedNamespaces: {
        value: [
          'kube-system'
          'gatekeeper-system'
        ]
      }
    }
    displayName: 'Do not allow privileged containers'
    description: 'Prevents privilege escalation attacks'
  }
  identity: {
    type: 'SystemAssigned'
  }
}

// Policy: Enforce HTTPS ingress
resource httpsIngressPolicy 'Microsoft.Authorization/policyAssignments@2023-04-01' = {
  name: 'aks-https-ingress-${take(clusterName, 47)}'
  location: location
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/1a5b4dca-0b6f-4cf5-907c-56316bc1bf3d'
    parameters: {
      excludedNamespaces: {
        value: [
          'kube-system'
        ]
      }
    }
    displayName: 'Enforce HTTPS ingress'
    description: 'Ensures all ingress uses HTTPS/TLS'
  }
  identity: {
    type: 'SystemAssigned'
  }
}

// Policy: Enforce internal load balancers
resource internalLoadBalancerPolicy 'Microsoft.Authorization/policyAssignments@2023-04-01' = {
  name: 'aks-internal-lb-${take(clusterName, 50)}'
  location: location
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/3fc4dc25-5baf-40d8-9b05-7fe74c1bc64e'
    parameters: {
      excludedNamespaces: {
        value: [
          'kube-system'
          'ingress-nginx'
        ]
      }
    }
    displayName: 'Enforce internal load balancers'
    description: 'Prevents public load balancers except in allowed namespaces'
  }
  identity: {
    type: 'SystemAssigned'
  }
}

// Policy: Containers must use allowed AppArmor profiles
resource appArmorPolicy 'Microsoft.Authorization/policyAssignments@2023-04-01' = {
  name: 'aks-apparmor-${take(clusterName, 54)}'
  location: location
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/511f5417-5d12-434d-ab2e-816901e72a5e'
    parameters: {
      excludedNamespaces: {
        value: [
          'kube-system'
        ]
      }
      allowedProfiles: {
        value: [
          'runtime/default'
          'docker/default'
        ]
      }
    }
    displayName: 'Enforce AppArmor profiles'
    description: 'Restricts containers to approved AppArmor security profiles'
  }
  identity: {
    type: 'SystemAssigned'
  }
}

// Policy: Container CPU and memory limits
resource resourceLimitsPolicy 'Microsoft.Authorization/policyAssignments@2023-04-01' = {
  name: 'aks-resource-limits-${take(clusterName, 47)}'
  location: location
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/e345eecc-fa47-480f-9e88-67dcc122b164'
    parameters: {
      excludedNamespaces: {
        value: [
          'kube-system'
          'gatekeeper-system'
        ]
      }
      cpuLimit: {
        value: '2000m'
      }
      memoryLimit: {
        value: '4Gi'
      }
    }
    displayName: 'Enforce resource limits'
    description: 'Prevents resource exhaustion attacks'
  }
  identity: {
    type: 'SystemAssigned'
  }
}

// Policy: Read-only root filesystem
resource readOnlyRootFSPolicy 'Microsoft.Authorization/policyAssignments@2023-04-01' = {
  name: 'aks-readonly-rootfs-${take(clusterName, 46)}'
  location: location
  properties: {
    policyDefinitionId: '/providers/Microsoft.Authorization/policyDefinitions/df49d893-a74c-421d-bc95-c663042e5b80'
    parameters: {
      excludedNamespaces: {
        value: [
          'kube-system'
        ]
      }
      excludedContainers: {
        value: []
      }
    }
    displayName: 'Enforce read-only root filesystem'
    description: 'Prevents runtime file system tampering'
  }
  identity: {
    type: 'SystemAssigned'
  }
}

output policyAssignmentIds array = [
  allowedContainerImagesPolicy.id
  noPrivilegedContainersPolicy.id
  httpsIngressPolicy.id
  internalLoadBalancerPolicy.id
  appArmorPolicy.id
  resourceLimitsPolicy.id
  readOnlyRootFSPolicy.id
]
";
  }
}
