// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platform.Engineering.Copilot.Core.Data.Context;

#nullable disable

namespace Platform.Engineering.Copilot.Core.Data.Migrations
{
    [DbContext(typeof(PlatformEngineeringCopilotContext))]
    [Migration("20251006124514_AddServiceCreationRequests")]
    partial class AddServiceCreationRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Platform.Engineering.Copilot.Core.Models.ServiceCreation.ServiceCreationRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessJustification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("UNCLASS");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ComplianceFrameworksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("DataResidency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("US");

                    b.Property<decimal>("EstimatedDataVolumeTB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedMonthlyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimatedUserCount")
                        .HasColumnType("int");

                    b.Property<string>("FundingSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<int>("MissionDurationMonths")
                        .HasColumnType("int");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MissionOwner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MissionOwnerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MissionOwnerRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NotificationHistoryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime?>("ProvisionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProvisionedResourceGroupId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProvisionedResourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisionedSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProvisionedVNetId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProvisioningError")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("usgovvirginia");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedSubscriptionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestedVNetCidr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequiredServicesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAto")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresCac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RequiresPki")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UseCase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationLevel")
                        .HasDatabaseName("IX_ServiceCreationRequests_ClassificationLevel");

                    b.HasIndex("Command")
                        .HasDatabaseName("IX_ServiceCreationRequests_Command");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ServiceCreationRequests_CreatedAt");

                    b.HasIndex("MissionOwnerEmail")
                        .HasDatabaseName("IX_ServiceCreationRequests_MissionOwnerEmail");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ServiceCreationRequests_Status");

                    b.HasIndex("Status", "Priority", "CreatedAt")
                        .HasDatabaseName("IX_ServiceCreationRequests_Status_Priority_CreatedAt");

                    b.ToTable("ServiceCreationRequests");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ComplianceFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ControlId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAutomaticallyFixable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemediable")
                        .HasColumnType("bit");

                    b.Property<string>("Remediation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResourceName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsRemediable");

                    b.HasIndex("RuleId");

                    b.HasIndex("Status");

                    b.HasIndex("ScanId", "Severity");

                    b.ToTable("ComplianceFindings");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ComplianceScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ComplianceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("FailedChecks")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PassedChecks")
                        .HasColumnType("int");

                    b.Property<string>("Recommendations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Results")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalChecks")
                        .HasColumnType("int");

                    b.Property<int>("WarningChecks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceScore");

                    b.HasIndex("DeploymentId", "StartedAt");

                    b.HasIndex("Standard", "Status");

                    b.HasIndex("DeploymentId", "Standard", "CompletedAt")
                        .HasDatabaseName("IX_ComplianceScans_Deployment_Standard_Completed");

                    b.ToTable("ComplianceScans");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.DeploymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Status");

                    b.HasIndex("DeploymentId", "StartedAt");

                    b.ToTable("DeploymentHistory");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EnvironmentLifecycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.HasIndex("UserId");

                    b.HasIndex("EnvironmentLifecycleId", "Timestamp");

                    b.ToTable("EnvironmentActivities");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentClone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloneOperationLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataMaskingRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcludedResources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IncludeData")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeSecrets")
                        .HasColumnType("bit");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("MaskSensitiveData")
                        .HasColumnType("bit");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TargetEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("TargetEnvironmentId");

                    b.HasIndex("SourceEnvironmentId", "TargetEnvironmentId");

                    b.ToTable("EnvironmentClones");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentCostTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingResourceGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CostBreakdown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CumulativeCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DailyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnvironmentLifecycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DailyCost");

                    b.HasIndex("Date");

                    b.HasIndex("Date", "DailyCost")
                        .HasDatabaseName("IX_EnvironmentCostTrackings_Date_Cost");

                    b.HasIndex("EnvironmentLifecycleId", "Date");

                    b.ToTable("EnvironmentCostTrackings");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualMonthlyCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<TimeSpan?>("CurrentPollingInterval")
                        .HasColumnType("time");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeployedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("EstimatedMonthlyCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<TimeSpan?>("EstimatedTimeRemaining")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPollingActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PollingAttempts")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ResourceGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("ResourceGroupName");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("EnvironmentType", "Status");

                    b.HasIndex("SubscriptionId", "ResourceGroupName", "Status")
                        .HasDatabaseName("IX_EnvironmentDeployments_Subscription_ResourceGroup_Status");

                    b.ToTable("EnvironmentDeployments");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentLifecycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AutoDestroyPolicy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("CostThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InactivityThresholdHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LifecycleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NotificationEmails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationHours")
                        .HasColumnType("int");

                    b.Property<bool>("NotifyBeforeDestroy")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerTeam")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Project")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ScheduledEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("LastActivityAt");

                    b.HasIndex("OwnerTeam");

                    b.HasIndex("Project");

                    b.HasIndex("ScheduledEndTime");

                    b.HasIndex("LifecycleType", "Status");

                    b.HasIndex("OwnerTeam", "Project", "Status")
                        .HasDatabaseName("IX_EnvironmentLifecycles_Team_Project_Status");

                    b.ToTable("EnvironmentLifecycles");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Labels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MetricName", "Timestamp");

                    b.HasIndex("DeploymentId", "MetricType", "Timestamp")
                        .HasDatabaseName("IX_EnvironmentMetrics_Deployment_Type_Time");

                    b.ToTable("EnvironmentMetrics");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentSynchronization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConflictResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSyncLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NextSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SyncFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SyncRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TargetEnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextSyncAt");

                    b.HasIndex("SyncType");

                    b.HasIndex("TargetEnvironmentId");

                    b.HasIndex("SourceEnvironmentId", "TargetEnvironmentId");

                    b.ToTable("EnvironmentSynchronizations");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoScalingEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("AzureService")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeploymentTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DisasterRecoverySupported")
                        .HasColumnType("bit");

                    b.Property<int>("FilesCount")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HighAvailabilitySupported")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("MainFileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("MonitoringEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("MultiRegionSupported")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TemplateType", "DeploymentTier");

                    b.ToTable("EnvironmentTemplates");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.IntentFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectIntentAction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorrectIntentCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorrectParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedbackType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProvidedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IntentId", "FeedbackType");

                    b.ToTable("IntentFeedback");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.IntentPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntentAction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntentCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ParameterExtractionRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SuccessRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SuccessRate");

                    b.HasIndex("IntentCategory", "IntentAction");

                    b.ToTable("IntentPatterns");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ScalingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NewReplicas")
                        .HasColumnType("int");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PreviousReplicas")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TriggerDetails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Status");

                    b.HasIndex("PolicyId", "CreatedAt");

                    b.ToTable("ScalingEvents");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ScalingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoScalingEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("CostOptimizationEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxReplicas")
                        .HasColumnType("int");

                    b.Property<int>("MinReplicas")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScaleDownCooldown")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ScaleUpCooldown")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Schedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetCpuUtilization")
                        .HasColumnType("int");

                    b.Property<int>("TargetMemoryUtilization")
                        .HasColumnType("int");

                    b.Property<bool>("TrafficBasedScalingEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("DeploymentId", "PolicyType");

                    b.ToTable("ScalingPolicies");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.SemanticIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntentAction")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntentCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResolvedToolCall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserInput")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("WasSuccessful");

                    b.HasIndex("IntentCategory", "IntentAction");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SemanticIntents");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.TemplateFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEntryPoint")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateFiles");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeLog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TemplateId", "Version")
                        .IsUnique();

                    b.ToTable("TemplateVersions");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ComplianceFinding", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.ComplianceScan", "Scan")
                        .WithMany("Findings")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ComplianceScan", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "Deployment")
                        .WithMany("ComplianceScans")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.DeploymentHistory", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "Deployment")
                        .WithMany("History")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentActivity", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentLifecycle", "EnvironmentLifecycle")
                        .WithMany("Activities")
                        .HasForeignKey("EnvironmentLifecycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvironmentLifecycle");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentClone", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "SourceEnvironment")
                        .WithMany()
                        .HasForeignKey("SourceEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "TargetEnvironment")
                        .WithMany()
                        .HasForeignKey("TargetEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceEnvironment");

                    b.Navigation("TargetEnvironment");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentCostTracking", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentLifecycle", "EnvironmentLifecycle")
                        .WithMany("CostTrackings")
                        .HasForeignKey("EnvironmentLifecycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvironmentLifecycle");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentTemplate", "Template")
                        .WithMany("Deployments")
                        .HasForeignKey("TemplateId");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentLifecycle", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentMetrics", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "Deployment")
                        .WithMany("Metrics")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentSynchronization", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "SourceEnvironment")
                        .WithMany()
                        .HasForeignKey("SourceEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "TargetEnvironment")
                        .WithMany()
                        .HasForeignKey("TargetEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceEnvironment");

                    b.Navigation("TargetEnvironment");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.IntentFeedback", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.SemanticIntent", "Intent")
                        .WithMany("Feedback")
                        .HasForeignKey("IntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intent");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ScalingEvent", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.ScalingPolicy", "Policy")
                        .WithMany("ScalingEvents")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ScalingPolicy", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", "Deployment")
                        .WithMany("ScalingPolicies")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deployment");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.TemplateFile", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentTemplate", "Template")
                        .WithMany("Files")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.TemplateVersion", b =>
                {
                    b.HasOne("Platform.Engineering.Copilot.Data.Entities.EnvironmentTemplate", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ComplianceScan", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentDeployment", b =>
                {
                    b.Navigation("ComplianceScans");

                    b.Navigation("History");

                    b.Navigation("Metrics");

                    b.Navigation("ScalingPolicies");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentLifecycle", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CostTrackings");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.EnvironmentTemplate", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("Files");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.ScalingPolicy", b =>
                {
                    b.Navigation("ScalingEvents");
                });

            modelBuilder.Entity("Platform.Engineering.Copilot.Data.Entities.SemanticIntent", b =>
                {
                    b.Navigation("Feedback");
                });
#pragma warning restore 612, 618
        }
    }
}
